### ISSUE TITLE
TemplateHaskell not included for components when building RunOptimizedProdServer?

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1009]
I ran into a build error with IHP 0.12.0, but not with `./start`, only with `make build/bin/RunOptimizedProdServer` on the production server, when my component (literally the "counter" test component given in the components example) didn't explicitly have the `TemplateHaskell` language pragma. Sorry if this has been reported / fixed already. Adding the pragma allowed me to build it.

**Comment by mpscholten** [comment]
Good catch :) I only enabled this in the `applicationGhciConfig` for dev mode. My test components still had `{-# LANGUAGE TemplateHaskell #-}` at the top of the file, that's why the bug hasn't happen to me previously. It's now fixed on master 👍

**Comment by CSchank** [comment]
Perfect, no problem! This is similar to having "hidden environment" on your local machine others don't, except not very hidden, but still a bit hard to catch when you only run those tests :)
