### ISSUE TITLE
Bad Error Message when inputValue is missing

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1013]
This code:

```haskell
 renderForm :: Proposal -> Team -> Html
renderForm proposal team = formFor proposal [hsx|
    {(textField #title)}
    {(textField #description)}
    <input type="hidden" name="teamId" value={(get #id team)} />
    {submitButton}
|]
```

triggers an error like 

```
Could not deduce (IHP.RouterSupport.AutoRoute (Id' "teams")) arising from a use of ‘IHP.HSX.QQ.applyAttribute’ from the context: ?context::ControllerContext
```

which can be fixed by replacing `(get #id team)` with `inputValue (get #id team)`

We should improve the confusing error message

**Comment by CSchank** [comment]
I ran into this too, and using `show` worked, but then when I saw this I changed it to `inputValue` because that seems like the more correct way to do it.

**Comment by geofflangenderfer** [comment]
related stackoverflow: https://stackoverflow.com/questions/77424179/could-not-deduce-ihp-routersupport-autoroute-id-hardwarevendors/77442084#77442084
