### ISSUE TITLE
Add help text to enum creation modal when trying to add a camel cased value

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1020]
I created an enum `PublishExtent` with the values `Public`, `PublishUser` and `PublishGroup` but when the code is generated, it looks like: `data PublishExtent = Public | Publishuser | Publishgroup deriving (Eq, Show, Read, Enum)`. 

Is this a bug? It's kind of annoying imo.

**Comment by CSchank** [comment]
The web UI for creating the enums still shows the capitalization that I originally intended. It's just the code generation that seems to change the casing.

**Comment by mpscholten** [comment]
can you share the sql code of the enum? Enum values should typically be written in `snake_case` instead of `CamelCase` :)

**Comment by CSchank** [comment]
Here it is: `CREATE TYPE PublishType AS ENUM ('ViewCompiledProgram', 'AbilityToFork', 'AbilityToImport');` Ah, snake case. My bad. My Haskell is really showing!

**Comment by CSchank** [comment]
Okay, it works when I change to snake case! Thanks. So, if you don't want to change the behaviour for camel case, perhaps we should add a `helpText` to the bottom of the enum modal, like on the table creation modal.

**Comment by mpscholten** [comment]
Yes, will add it 👍

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/commit/0e4c4d7d773cd69ce8fdf56dd70aa753a8a2120d
