### ISSUE TITLE
Blog demo app: passing malformed UUID causes page to not reload

### ISSUE THREAD

**Issue by dharmatech** [digitallyinduced/ihp#1028]
Hey y'all!

This is regarding the blog demo app from the guide.

In the file `Web/View/Comments/Index.hs`, we're instructed to remove the code that calls `NewCommentAction`.

If I add back in, a call to `NewCommentAction` with a hardcoded UUID like this:

    <a href={NewCommentAction "0f671934-0971-402e-ab70-f17e91b56a82"}>abc</a>

that works fine and the page renders properly with the new link.

However, if I remove a character from the UUID (the first one in this case) making it a malformed UUID:

    <a href={NewCommentAction "f671934-0971-402e-ab70-f17e91b56a82"}>abc</a>

the page does not reload. If I manually reload the page, the page doesn't load at all.

In my experience so far with IHP, I'd normally expect an error message if there was a problem running the application. So this behaviour seems unusual.

Here's a video demonstrating the issue:

https://youtu.be/9TlUOGasXWU

Just wondering, is this the expected behaviour? Or would it be possible to provide an error message to the user in a case like this?

Is there somewhere else in the logs that makes the page reload issue apparent?

Thanks!

**Comment by mpscholten** [comment]
Hey, thanks for the great error report! :) This is a bug. I'll take a look in a few minutes.

**Comment by mpscholten** [comment]
This is now fixed via https://github.com/digitallyinduced/ihp/commit/e6b1b642746005bb035cf533b42faaa1418a1e2b :) The issue was that the error was thrown too late in the request handling lifecycle because of lazyness. We've disabled a bit of the lazyness in dev mode to be able to handle the error with the normal IHP error tooling.

**Comment by dharmatech** [comment]
@mpscholten,

Well that was fast! :-) Thanks! And thanks for the explanation.
