### ISSUE TITLE
join SQL error: "column reference \"id\" is ambiguous"

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1035]
I am trying to join two tables `ModulePublish` and `Snapshot`. `ModulePublish` has a foreign key `snapshotId`. So I was trying to join on all instances where the `snapshotId` from the `ModulePublish` table is the `id` of the `snapshot`. But I am receiving a runtime (but not type) error. From the following code: 

```haskell
modulePublishes <- query @ModulePublish
        |> filterWhereIn  (#id, moduleGroupPublishes ++ moduleUserPublishes)
        |> innerJoin @Snapshot (#snapshotId, #id)
        |> filterWhereNotJoinedTable @Snapshot (#elmModuleId, elmModuleId)
        |> fetch
        >>= collectionFetchRelated #snapshotId
```

I am receiving the error 

```haskell
SqlError {sqlState = "42702", sqlExecStatus = FatalError, sqlErrorMsg = "column reference \"id\" is ambiguous", sqlErrorDetail = "", sqlErrorHint = ""}
```

**Comment by CSchank** [comment]
@hllizi tagging you again :)

**Comment by hllizi** [comment]
Done.

**Comment by CSchank** [comment]
Great, thank you!

**Comment by CSchank** [comment]
Should we close this now that it's merged? Maybe let me try running my code against this first.

**Comment by CSchank** [comment]
My query seems to work like a charm now. Coupled with pagination work on this, this just cleaned up my code for this action considerably. :) I'll close. Feel free to reopen if other problems crop up.
