### ISSUE TITLE
fd:28: hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by hendi** [digitallyinduced/ihp#1036]
When updating the DB. Trying again seemed to work.

**Comment by s0kil** [comment]
If I'm not mistaken, also got this error when IHP failed to parse the Schema.sql file.

**Comment by CSchank** [comment]
I ran into this problem in my own IHP project when trying to read a file a few days ago (but only on Linux, my project worked fine on macOS!) using `Data.Text.IO.readFile/writeFile` directly. I ended up having to manually open the file handle:

```haskell
readFile :: FilePath -> IO Text
readFile filePath = do
    h <- System.IO.openFile filePath System.IO.ReadMode
    System.IO.hSetEncoding h System.IO.utf8
    TIO.hGetContents h

writeFile :: FilePath -> Text -> IO ()
writeFile filePath contents = do
    h <- System.IO.openFile filePath System.IO.WriteMode
    System.IO.hSetEncoding h System.IO.utf8
    TIO.hPutStr h contents
    System.IO.hClose h
```

**Comment by mpscholten** [comment]
This bug was very likely fixed via https://github.com/digitallyinduced/ihp/commit/ff5276bf34f4614df9d9853b6cc64007d014f15e
