### ISSUE TITLE
Gitpod still has no hot reload

### ISSUE THREAD

**Issue by janat08** [digitallyinduced/ihp#1083]
The gitpod template that ive tried still won't hot reload.

**Comment by mpscholten** [comment]
Thanks for reporting :) the technical issue that caused the live reloading to not work has already been fixed on master. The gitpod template was on the v0.14 release. I just updated the gitpod template to the latest master commit which should fix it.

**Comment by mpscholten** [comment]
Thanks for reporting :) the technical issue that caused the live reloading to not work has already been fixed on master. The gitpod template was on the v0.14 release. I just updated the gitpod template to the latest master commit which should fix it.

**Comment by mpscholten** [comment]
Just tested it :) it works 🎉
