### ISSUE TITLE
Consider renaming setSession to setCookie (and related functions)

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/ihp#1086]
The distinction between a cookie and what IHP considers a Session is unclear (if it even exists). Renaming setSession to setCookie might avoid this confusion.

Additionally, setSession might be a useful name for a helper function to set a cookie value to a unique identifier so that users can be uniquely identified without the need of creating an account (especially useful in shops).

**Comment by jeyj0** [comment]
@nezbite

**Comment by mpscholten** [comment]
the session functionality is basically dealing only with session cookies. So it's basically a special subset of the cookie functions.

While we can think about renaming `setSession`, renaming it too `setCookie` would be wrong as it's not setting any cookie, only modifying the existing session cookie.

**Comment by mpscholten** [comment]
There's now a `setCookie` function https://github.com/digitallyinduced/ihp/blob/master/IHP/Controller/Cookie.hs#L24 So this issue can be considered obsolet.
