### ISSUE TITLE
How to render HTML in  `attachFailure`

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1093]
## Issue

I'd like to show an error message that has a link. I'm trying to use hsx for that, however this still ends up with showing the tags, instead of rendering the HTML

```haskell
import Web.View.Prelude (hsx)

-- ...

post
    |> attachFailure #title (show errorHtml)
where
    errorHtml = [hsx|
            Wrong value, please check the <a href="https://example.com">docs</a>
        |]
```

![Selection_999(236)](https://user-images.githubusercontent.com/125707/134919974-e0c6d6bb-082d-4c9c-aaf1-8fb758fcd287.jpg)

**Comment by mpscholten** [comment]
Hey, this is currently not supported. It's been requested before already, so I created a PR to add a new `attachFailureHtml` function. It can be used like this:

```haskell
post
    |> attachFailure #title [hsx|Wrong value, please check the <a href="https://example.com">docs</a>|]
```

Once the PR is merged you can follow https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-the-latest-git-commit to upgrade to the latest master. You'll also need to apply this patch to your `nixpkgs-config.nix` file https://github.com/digitallyinduced/ihp-boilerplate/commit/77b4196fd50b0abbdf7f299130fe24412426745f
