### ISSUE TITLE
Wrong `insert` of a new Row from the IDE when there's an enum type

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1098]
with the following `Schema.sql` when trying to add a row an error will occur. It seems related to the enum field, as without it, it works fine.

```sql
CREATE TYPE item_status AS ENUM ('active', 'inactive');

CREATE TABLE items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    status item_status NOT NULL,
    test UUID[] DEFAULT '{}' NOT NULL
);
```

![Selection_999(262)](https://user-images.githubusercontent.com/125707/135731257-1217ba1f-105d-4df9-9051-90ace21fe328.jpg)

![Selection_999(263)](https://user-images.githubusercontent.com/125707/135731295-b6fb449b-6f89-40dd-8d37-fc5e4943c562.jpg)

Seems like the order of the inserted values is messed up.

**Comment by mpscholten** [comment]
This is a bug 👍  will look into this

**Comment by mpscholten** [comment]
Can't reproduce this with the above schema. Am I missing something?

**Comment by amitaibu** [comment]
I can't reproduce myself :man_shrugging: . Closing for now
