### ISSUE TITLE
`isWeekend` is country specific

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1100]
A bit nitpick-y, but I'm living in Israel and our weekend is actually on Friday and Saturday. Sunday is a working day (which makes it lovely to have one day for silence, when most of our clients are at their weekend :smile: )

So maybe [isWeekend](https://github.com/digitallyinduced/ihp/blob/877ed13e1e74d37b83ce4cfd0aab8ca9c250d84d/IHP/HaskellSupport.hs#L335-L339) should be removed from IHP's core, just to make sure we don't have an incorrect function?

**Comment by mpscholten** [comment]
thanks for pointing this out! Wasn't aware about this. Love that you have sunday for coding :)

In generally I'm fine with having `isWeekend` as it is as long as the documentation makes it clear that in IHP-terms weekend means Saturday + Sunday. Most users of IHP are in the US and Norway, so for most users it's the most natural choice.

[I was looking into how other frameworks have dealt with this, and most are doing it the same.](https://github.com/rails/rails/pull/18335#issuecomment-68671309)

**Comment by amitaibu** [comment]
Alright, sounds ok. 

> Most users of IHP are in the US and Norway,

For now there's also at least one Israeli user :wink:
