### ISSUE TITLE
Support for M1 Chips

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1113]

**Comment by rvarun11** [comment]
@mpscholten I got IHP to work with Nix. Had to downgrade to version 2.3.10.

**Comment by mpscholten** [comment]
Can you check if it's using x86 emulation or running native ARM?

**Comment by rvarun11** [comment]
It's using x86 emulation.

**Comment by vajrabisj** [comment]
> @mpscholten I got IHP to work with Nix. Had to downgrade to version 2.3.10.

how to downgrade?

**Comment by rvarun11** [comment]
> how to downgrade?

@vajrabisj You can run
```
curl -L https://releases.nixos.org/nix/nix-2.3.10/install | sh 
```
You can find any suitable version [here](https://nixos.org/download.html#nix-more)

**Comment by mpscholten** [comment]
M1 support has been shipped a while ago 👍
