### ISSUE TITLE
Support to send json data via web socket

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1181]
Right now, the web socket controller only supports `sendTextData` to send data via the web socket controller and sending data via json only seems to be possible by using `Text` and then parsing the JSON in the frontend as follows:

```
.
.
.
let jsonMsg = "\"message\": \""<> msg <> "\""
let jsonCreatedAt = "\"createdAt\": \""<> (show $ get #createdAt chatMsg) <> "\""
          
sendTextData ("{" <> jsonMsg <> "," <> jsonCreatedAt <> "}") 
```

This becomes very tedious especially if you more complex data and should be supported natively by IHP.

**Comment by mpscholten** [comment]
The function is now exposed :) You can find docs here https://github.com/digitallyinduced/ihp/commit/4d93293b6cf9418373e4a01ae86485db14ed073a
