### ISSUE TITLE
Update Guide : Cherry-picking tables for Auto Refresh

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1185]
Right now, IHP tracks all the tables in an action with `autoRefresh` enabled. 

It would be better to allow cherrypicking tables in scenarios where we're processing a lot of data for a view but only only a small portion needs Auto Refresh.

**Comment by mpscholten** [comment]
Have you tried something like this:

```haskell
action MyAction = do
    expensiveModels <- query @Expensive |> fetch

    autoRefresh do
        cheap <- query @Cheap |> fetch
        render MyView { expensiveModels, cheap }
```

**Comment by rvarun11** [comment]
Yes, this works! Can you please update it in the Guide? The How it Works section says that Auto Refresh has to be activated for an Action and `trackTableRead` function in Advanced Auto Refresh section makes it a bit more confusing.
