### ISSUE TITLE
Morphdom breaking views with dynamic content

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1188]
Context:
I have view with a lot of dynamic content, one of which includes live chat. The chat is built with Auto Refresh and is using MorphDOM to update the UI. The problem is that whenever a message request is sent, MorphDOM breaks the view and loses all the unsaved content in the other parts of the view. To resolve this, I have been using `ihp:load` and `ihp:unload` to store the data to local storage and patch the view up on every request but this solution is way too expensive.

**Comment by Montmorency** [comment]
One thing you can try is looking at: [livereload](https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/static/livereload.js) which shows some hooks for overwriting which DOM elements morphdom will merge.  There is a full list of hooks [here](https://github.com/patrick-steele-idem/morphdom).

**Comment by rvarun11** [comment]
Okay. That means this could be solved without relying on IHP inherently. Thank you! I'll close the issue.

**Comment by mpscholten** [comment]
Maybe you can add your solution to the docs somewhere so it's documented for future reference :)

**Comment by rvarun11** [comment]
@Nutr1t07 Hi, we ended up dropping AutoRefresh for that view entirely and used STM to broadcast and emit messages to other clients.
