### ISSUE TITLE
SSC: "Non-exhaustive patterns in function nodeOuterHtml"

### ISSUE THREAD

**Issue by neongreen** [digitallyinduced/ihp#1192]
I have a component (a simple search box) that crashes whenever I type anything into it. The error goes `IHP/ServerSideComponent/HtmlDiff.hs:(112,1)-(114,46): Non-exhaustive patterns in function nodeOuterHtml`.

The component doesn't crash if I use `show` instead of `intercalate ","`. Here is sample result:

![image](https://user-images.githubusercontent.com/1523306/140174326-99ce9193-2f02-4356-ae1e-da8d68fa12de.png)

```haskell
module Web.Component.Switcher where

import IHP.ServerSideComponent.Types
import IHP.ServerSideComponent.ControllerFunctions
import Web.View.Prelude hiding (query, fetch)
import Web.Controller.Prelude

data Switcher = Switcher {
    switcherQuery :: !Text,
    currentResults :: ![Card]
}

data SwitcherController = SetSwitcherQuery {switcherQuery :: Text}
    deriving (Eq, Show, Data)

$(deriveSSC ''SwitcherController)

instance Component Switcher SwitcherController where
    initialState = Switcher {switcherQuery = "", currentResults = []}

    render Switcher{switcherQuery, currentResults} = [hsx|
        <div>
            <input type="text" 
                value={switcherQuery}
                onkeyup="callServerAction('SetSwitcherQuery', { switcherQuery: this.value })"
            >
            <span>{intercalate ", " $ map (get #title) currentResults}</span>
        </div>
    |]

    action state SetSwitcherQuery {switcherQuery} = do
        results <- query @Card
            |> filterWhereILike (#title, "%" <> switcherQuery <> "%")
            |> fetch
        pure $ state {
            switcherQuery = switcherQuery, 
            currentResults = results
            }
```

**Comment by neongreen** [comment]
In fact, the component crashes even if I do something like this: `<span>{if switcherQuery == "" then "" else "e" :: Text}</span>`.

However, the following works: `<span>{if switcherQuery == "" then "[]" else "'e'" :: Text}</span>`.

So it seems like it tries to parse the resulting string as.. a Haskell value?

**Comment by neongreen** [comment]
No, JS value because `true` and `<span>{if switcherQuery == "" then "[]" else "{\"a\":0}" :: Text}</span>` also work.

**Comment by mpscholten** [comment]
This is a known issue, as far as i remember it was caused by a bug in the dom diff generation, https://github.com/digitallyinduced/ihp/blob/master/IHP/ServerSideComponent/HtmlDiff.hs#L43

The "bad diff" then triggers an invalid call to `nodeOuterHtml`.

**Comment by neongreen** [comment]
Alright. Are there any workarounds?

**Comment by neongreen** [comment]
I'll try to fix it in the meantime

**Comment by neongreen** [comment]
```haskell
diffNodes' path oldNode@(Node { tagName = oldTagName, attributes = oldAttributes, children = oldChildren }) newNode@(Node { tagName = newTagName, attributes = newAttributes, children = newChildren }) =
    if oldTagName == newTagName
        then
            let
                attributeOperations = diffAttributes oldAttributes newAttributes
                childrenNodeOperations = diffNodes' path Children { children = oldChildren } Children { children = newChildren }
```

I don't understand the semantics of `path`. Shouldn't it have an index appended in the recursive call `diffNodes' path Children{..} Children{..}`?

**Comment by neongreen** [comment]
The bug seems to be in `nodeOuterHtml` not handling `TextNode` etc. The diff can't be produced because `nodeOuterHtml` is called to produce a `CreateNode`, which fails if the node we're trying to create is a text node.

The minimal testcase is `<span></span>` -> `<span>x</span>`. Why it doesn't fail with JS literals inside is an open question, I'll investigate it later.

I'm still curious about the `path` question about, though.

**Comment by neongreen** [comment]
Re/ JS literals — looks like a red herring, it's just empty vs non-empty.

**Comment by mpscholten** [comment]
> I don't understand the semantics of path. Shouldn't it have an index appended in the recursive call diffNodes' path Children{..} Children{..}?

I agree. Just tried to add an index there and then I remembered the reason why I made it that way :)

The code is:

```haskell
diffNodes' path Children { children = oldChildren } Children { children = newChildren }
```

The important is the `Children` wrapper here.

This basically  is a jump to the [`diffNodes' path Children { children = oldChildren } Children { children = newChildren } =` branch](https://github.com/digitallyinduced/ihp/blob/master/IHP/ServerSideComponent/HtmlDiff.hs#L70) of the `diffNodes'` function. [That branch will unpack the `Children` again and then apply the index there.](https://github.com/digitallyinduced/ihp/blob/master/IHP/ServerSideComponent/HtmlDiff.hs#L75)
