### ISSUE TITLE
Long delay in processing requets

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1200]
I'm trying to run concurrent requests on an IHP cloud instance. After 37 requests it halts. I know there's the garbage collector that takes action, but it seems quite slow - ~5 sec until it's released again.

https://user-images.githubusercontent.com/125707/140614857-e2a61217-dd66-45b8-8467-630335464e89.mp4

Cloud: https://appkowdtwpxtevhagjqyejbdyrwhjgor.ihpapp.com/ShowEvent?eventId=53da7da4-43e4-4665-95e3-3388c4304f86
Repo: https://github.com/Gizra/ihp-simple-seat-reservation

**Comment by zacwood9** [comment]
I'd guess the GHC RTS options IHP sets need a review. I found these two posts from NoRedInk about their journey doing that very helpful in understanding what's going on a bit better:
- https://blog.noredink.com/post/666020751977168896/tuning-haskell-rts-for-kubernetes-part-1
- https://blog.noredink.com/post/666654908557180928/tuning-haskell-rts-for-kubernetes-part-2

The settings for optimized builds are here: https://github.com/digitallyinduced/ihp/blob/8609717d7b640142739f035005a2ee7fdf57b032/lib/IHP/Makefile.dist#L84

What stands out to me is `-A=512m`. This is significantly larger than what the recommended values seem to be (default is 512k, or at least [less than size of L2 cache](https://stackoverflow.com/questions/3171922/ghcs-rts-options-for-garbage-collection/3172704#3172704)) so the first thing I'd try is decreasing that.

Related, it would be nice for IHP to provide a way to easily override these options as we build apps for different environments so we can test out our own configurations.

**Comment by mpscholten** [comment]
In IHP Cloud these rts settings are also overriden:
- if using the old deployment engine: `-A8M`
- if using the new deployment engine: it's not overriden here, so here it's using `-A512m` as defined in the Makefile

A good way to experiment with that is to use env vars:

![image](https://user-images.githubusercontent.com/2072185/140625323-cd20b4c2-d106-4546-9654-e35ed5e44ecf.png)

(That should override the `-A512m` if using the new deployment engine)

**Comment by amitaibu** [comment]
Is it likely that the pause time is so big? From the video we can see it took 7.714 sec / 50 requests = 0.153 sec per request. This is quite close to the results we got from a more bloated Drupal (PHP) running a similar logic.

**Comment by mpscholten** [comment]
I can reproduce the issue:

```
ab -c 10 -n 1000 "$url"
```

Gives me:

```
Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:       70   99  56.5     83     358
Processing:    36   52  32.2     41     201
Waiting:       35   51  32.0     41     201
Total:        110  151  85.5    125     533

Percentage of the requests served within a certain time (ms)
  50%    125
  66%    128
  75%    131
  80%    133
  90%    155
  95%    387
  98%    504
  99%    509
 100%    533 (longest request)
```

Specifically the longest request time seems strange.

**Comment by mpscholten** [comment]
When I run the `parallel` command given on the ShowEvent page it completes without any delay.

**Comment by amitaibu** [comment]
Right, it seems that when there are no more seats to assign there is no delay.

If you'd create a new Event in https://appkowdtwpxtevhagjqyejbdyrwhjgor.ihpapp.com/ShowVenue?venueId=3df7ec3c-5b4d-4ac2-bcf5-080dc68ac0f0 and use the command there you should see the gap.

So this narrows down the problem to https://github.com/Gizra/ihp-simple-seat-reservation/blob/c5dc232c99a743c86cbc9ec8cdfff6087a6208e7/Web/Job/Reservation.hs#L43-L51 . So likely the `forkIO $ sendMail` is causing this?

**Comment by mpscholten** [comment]
Can you try out `async` instead of `forkIO` and see if it makes a difference?

**Comment by amitaibu** [comment]
I'm seeing similar results with `async` (currently deployed to IHP cloud).

**Comment by amitaibu** [comment]
Actually, it seems it's not about the Mail. I've removed it, and still, I see delays. I'll re-deploy to IHPcloud

**Comment by amitaibu** [comment]
Removed the email, but then I noticed that also when all seats are taken there's still a delay. I did see once a total of ~2.5 sec instead of ~7 sec

https://user-images.githubusercontent.com/125707/140641702-d727c06a-9025-4cbf-9d8a-95e8ff460442.mp4

**Comment by amitaibu** [comment]
To clarify, the above video is the faster one, but I cannot reproduce it. Rest of the calls are ~7 sec

https://user-images.githubusercontent.com/125707/140641852-0f56b4d8-1619-4916-9451-65ceac7598e5.mp4

**Comment by amitaibu** [comment]
@mpscholten I've tried to remove the entire logic of the Job and only return `pure ()` - and the delay is still there. So I suspect it has to do with the Job runner itself.

**Comment by amitaibu** [comment]
(when a Job isn't created at all - there's no delay and it finishes in ~2.2sec)

**Comment by mpscholten** [comment]
I still cannot reproduce the delay. Maybe it's a local network issue? Could you try to run the command from some external server?

**Comment by amitaibu** [comment]
I believe you are right! I've tried to issue the parallel requests from `Gitpod` and indeed there was no delay

https://user-images.githubusercontent.com/125707/140646935-aae36302-6752-4f6f-ab13-eb6b2b46ad87.mp4

That's weird because I've never seen this issue on my local before, but :man_shrugging:

**Comment by mpscholten** [comment]
👍
