### ISSUE TITLE
libpq errors on Gitpod

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1210]
When spinning a new instance on Gitpod it's easy to come across these two errors:

![image](https://user-images.githubusercontent.com/125707/141119413-dd12059a-44d1-42cd-aa70-1ec39718558f.png)

![image](https://user-images.githubusercontent.com/125707/141119425-d8dcd8b9-8c39-448e-a33d-0d072dc5547e.png)

## Steps

1. Open [this Gitpod](https://gitpod.io/#https://github.com/Gizra/ihp-simple-seat-reservation)
2. As soon as port 8000 is available open it 
![image](https://user-images.githubusercontent.com/125707/141120810-36b5aa58-efec-4106-af33-b16c72ddeba6.png)

The error will go away after a few sec, but maybe there's a way to prevent this error and provide a nicer experience for people trying it out.

**Comment by amitaibu** [comment]
@mpscholten if you'd like, I could give you write access to my repo if that would ease debugging.

**Comment by mpscholten** [comment]
Ok, yes 👍
