### ISSUE TITLE
IHP Cloud: `sendmail: createProcess: posix_spawnp: does not exist (No such file or directory) `

### ISSUE THREAD

**Issue by anarchuser** [digitallyinduced/ihp#1219]
I've tried to get the [example mail code](https://ihp.digitallyinduced.com/Guide/mail.html) from the Guide to run.
I'm using SendGrid as described. It works flawlessly with my local development instance but deploying it over IHP Cloud throws a generic error message when trying to send.
The logs show this error message: 
```
sendmail: createProcess: posix_spawnp: does not exist (No such file or directory)
```

**Comment by mpscholten** [comment]
Thanks for reporting this 👍  [Did you add `sendmail` as a dependency in `default.nix`](https://ihp.digitallyinduced.com/Guide/package-management.html#using-a-native-dependency)?

**Comment by anarchuser** [comment]
Thanks for the quick response!
Adding `sendmail` to `default.nix` like this: 
```
    otherDeps = p: with p; [
        sendmail
    ];
```
leads to this compile time error:
```
error: undefined variable 'sendmail'
```

I'm going to check if there is some other package missing. It seems to know about `sendmail` but missing a subdependency

**Comment by mpscholten** [comment]
Try mailutils instead of sendmail as the Package Name

**Comment by anarchuser** [comment]
With `mailutils`  the project compiles but the error still remains

**Comment by anarchuser** [comment]
Until a solution is found by this, I'm looking for a workaround. I have been able to send mails from SendGrid via `sendgrid-v3`. Is there a way for me to create confirmation tokens for account confirmation myself?

**Comment by mpscholten** [comment]
Clsoing as IHP Cloud was shutdown
