### ISSUE TITLE
get an error when using Spread Values

### ISSUE THREAD

**Issue by mrsekut** [digitallyinduced/ihp#1226]
The [docs](https://ihp.digitallyinduced.com/Guide/hsx.html#:~:text=javascript%2Dsubmission%3D%22false%22/%3E-,Spread%20Values,-For%20dynamic%20use) states that the following syntax can be used in HSX, but when I actually write it, an error occurs.

```
<div { ...[ ("data-my-attribute", "Hello World!") ] } />
```

get the following error
```
    • In the quasi-quotation:
        [hsx|
    <div>
        <div { ...[ ("data-hoge", "Hello World!") ]  } />
    </div>
|]
   |
29 | render feed = [hsx|
   |                    ^...
 ```

Is this a bug?

I'm not in trouble, but I've seen it, so I'll report it in an issue.
IHP version is 0.16.0.

**Comment by mpscholten** [comment]
It looks like the error is caused by not specifying the types of the list. When you add types it will work:

```html
<div {...[ ("data-hoge" :: Text, "Hello World!" :: Text) ]}></div>
```

I'll add this to the documentation 👍 Also will push a test case for this feature in a few minutes.
