### ISSUE TITLE
`textareaField` not working as expected

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1246]
After the recent changes to the IHP Forms, the `textareaField` helper doesn't render a `<textarea>` anymore. Instead a `<input>` is generated.

**Comment by mpscholten** [comment]
cc @amitaibu

**Comment by amitaibu** [comment]
Looking at the code before my changeshttps://github.com/digitallyinduced/ihp/blob/3e311d3c78db2f2d69d934698b22c3f7a54e6159/IHP/View/CSSFramework.hs#L115-L130 it doesn't seem as if `textarea` was used before. Or maybe it's done somewhere else?

**Comment by amitaibu** [comment]
Oh, maybe that's the `fieldInput formField`.

**Comment by amitaibu** [comment]
So probably https://github.com/digitallyinduced/ihp/blob/51de9d6be69d7a176fa16998275076f7dd9da980/IHP/View/CSSFramework.hs#L140 should be changed.

**Comment by mpscholten** [comment]
Sadly there's no way to do something like `<{variableTag}` in HSX :) So I solved this by manually copying the function body

**Comment by mpscholten** [comment]
Also spotted https://github.com/digitallyinduced/ihp/issues/1248 while doing that :)
