### ISSUE TITLE
Add `fetchLatest` function

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1249]

**Comment by CSchank** [comment]
Will this assume #createdAt is a field?

**Comment by mpscholten** [comment]
Yes exactly 👍

**Comment by CSchank** [comment]
Would it be worth having a variant `fetchLatestBy` which has a proxy input?

**Comment by mpscholten** [comment]
Yes, and then `fetchLatest = fetchLatestBy #createdAt` 👍

**Comment by s0kil** [comment]
@CSchank You going to give this one a go?
