### ISSUE TITLE
DateTime field picker JS widget does not allow you to pick a time

### ISSUE THREAD

**Issue by linuxhype** [digitallyinduced/ihp#1253]
When adding a datetime field to a standard HSX form, it renders a textfield which when clicked opens a JS calendar widget to pick a datetime, however, it is only possible to pick a date in this widget?

How is the end user supposed to pick a time?

![image](https://user-images.githubusercontent.com/88370509/144627450-47875766-daa2-4f54-9603-75526eeed0df.png)
![image](https://user-images.githubusercontent.com/88370509/144627476-ec93e578-830e-44d4-98d4-d73e77400a3a.png)

**Comment by mpscholten** [comment]
Found the problem. When flatpickr (the lib used for the date time picker) was updated last time via https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/static/vendor/flatpickr.js the CSS was not updated. 

As a workaround, open `Web/View/Layout.hs` and replace `<link rel="stylesheet" href={assetPath "/vendor/flatpickr.min.css"}/>` with `<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css"/>`. Will fix this on master soon.
