### ISSUE TITLE
migration generator wants to drop job_status enum

### ISSUE THREAD

**Issue by jeyj0** [digitallyinduced/ihp#1256]

**Comment by jeyj0** [comment]
possibly a case sensitivity issue: IHP schema says `JOB_STATUS`, which might be converted to `job_status` by postres

**Comment by jeyj0** [comment]
https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/IHPSchema.sql#L5

**Comment by stianlagstad** [comment]
I ran into this here: https://ihpframework.slack.com/archives/C01DQE0F4F8/p1638281684375000

**Comment by mpscholten** [comment]
@stianlagstad good point 👍 

@jeyj0 are you running IHP v0.16 or master?

**Comment by mpscholten** [comment]
This has been fixed via https://github.com/digitallyinduced/ihp/commit/c9009dc41a0f50102f1d93780ac39db60e4a932d#diff-e789d44946917ca4ac65e2613317a591e76a11892098df81e6ab3dc0cadbefffR147
