### ISSUE TITLE
`RETURNING *` causes troubles in production

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1259]
There are a few places in IHP where we are using `RETURNING *`. This has the same issues as `SELECT * FROM`.

This mostly affects `createRecord` and `updateRecord`

Example: 

https://github.com/digitallyinduced/ihp/blob/master/IHP/SchemaCompiler.hs#L426

**Comment by amitaibu** [comment]
What kind of problems does it create?

**Comment by mpscholten** [comment]
When the order of columns in a production database is different as the one specified in the Schema.sql, this will create an error like this when using`createRecord` or `updateRecord`:

```
[INFO] [08-Dec-2021 08:08:41] Incompatible {errSQLType = "text", errSQLTableOid = Just (Oid 514429), errSQLField = "source_url", errHaskellType = "UTCTime", errMessage = ""}
```
