### ISSUE TITLE
nonEmpty form validation on files

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1304]
Hey :) 

It would be great if one could do a bit of validation of file uploads in a form.

The only thing I would like is for `nonEmpty` to work with files, or to have a `nonEmptyFile` validator.

Other than that, I think I could do more advanced file validation on the client side if needed, but of course other rules in the framework would also be welcome if possible.

**Comment by mpscholten** [comment]
Right now empty files should be ignored https://github.com/digitallyinduced/ihp/blob/master/IHP/FileStorage/ControllerFunctions.hs#L290 :) (That `not (LBS.null (get #fileContent fileInfo))` is basically complicated code for `fileContent != ""`)

Can you share a bit of the code you used that caused the problem?

**Comment by kodeFant** [comment]
Okay!

The usecase is just that I want file uploads to be mandatory before submitting the form:

```haskell
        ....
        |> validateField #licenceBackUrl nonEmpty
```

I'm just using a `fileField`

```haskell
{(fileField #licenceBackUrl){fieldLabel = "Last opp framsiden av førerkortet ditt"}}
```
This results in that the validation always fails. I'm realizing this now it's because the uploads are performed after the validation is performed.

![image](https://user-images.githubusercontent.com/9317208/148197884-9ffb7759-6dd5-443a-a7f7-722b264cd74e.png)

Found `validateFieldIO #licenceBackUrl nonEmpty`, but it doesn't work because I need a `IO ValidatorResult`. I suppose I could make a `nonEmptyIO` validation function for it!

**Comment by mpscholten** [comment]
Try something like this:

```haskell
action UpdateCompanyAction { companyId } = do
    company <- fetch companyId
    company
        |> fill @'["name"]
        |> uploadToStorage #licenceBackUrl
        >>= pure . (validateField #licenceBackUrl nonEmpty)
        >>= ifValid \case
            Left company -> render EditView { .. }
            Right company -> do
                company <- company |> updateRecord
                redirectTo EditCompanyAction { .. }
```

**Comment by amitaibu** [comment]
@kodeFant care to add this to the docs? :smile:
