### ISSUE TITLE
Setting and editing foreign key constraints does not work as expected and wipes Schema.sql

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1314]
Hi! I am having an issue using the Schema Editor in the IDE when editing foreign key constraints.

What I am trying to do is set the `user_id` in `password_resets` as a foreign key constraint for users.

![image](https://user-images.githubusercontent.com/9317208/148946406-db3c0d5e-890f-4eb8-a708-a27d80d6bbff.png)

Even though I am selecting `Cascade`, the on delete action is generated to `NO ACTION`

```sql
ALTER TABLE password_resets ADD CONSTRAINT password_resets_ref_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;
```

So then I try to edit the foreign key constraint to `Cascade`, also in the Schema Editor, and then I get this error

![image](https://user-images.githubusercontent.com/9317208/148947068-c266d954-9580-45db-a9de-7ffbc7ffe104.png)

The entire `Schema.sql` file is also completely wiped out into a blank file.

In addition, I'm seing this in the console:

```bash
pg_dump -a --inserts --column-inserts --disable-triggers -h $PWD/build/db app | sed -e '/^--/d' > Application/Fixtures.sql
No match in record selector constraintName
```

**Initial schema data to reproduce:** 

`Schema.sql`

```sql
-- Your database schema. Use the Schema Designer at http://localhost:8001/ to add some tables.
CREATE TABLE users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    locked_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    failed_login_attempts INT DEFAULT 0 NOT NULL,
    confirmation_token TEXT DEFAULT NULL,
    is_confirmed BOOLEAN DEFAULT false NOT NULL,
    google_user_id TEXT DEFAULT NULL
);
CREATE TABLE password_resets (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

```

`Fixtures.sql`

```sql


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


SET SESSION AUTHORIZATION DEFAULT;

ALTER TABLE public.users DISABLE TRIGGER ALL;



ALTER TABLE public.users ENABLE TRIGGER ALL;


ALTER TABLE public.password_resets DISABLE TRIGGER ALL;



ALTER TABLE public.password_resets ENABLE TRIGGER ALL;

```

**Comment by kodeFant** [comment]
Important note to this: 

I used a bleeding edge build. This did not happen in 0.17, so I reverted back to this. So this might be a non-issue. I assume you are working with something related to this :)

**Comment by kodeFant** [comment]
Think I'm closing this, as this most probably was related to an experimental build.

**Comment by mpscholten** [comment]
Cannot reproduce this on master anymore. So likely the bug I had yesterday was exactly the same as you described above and the fix from yesterday already fixed that.
