### ISSUE TITLE
Outdated patch file on Elm boilerplate

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1316]
The Elm boilerplate is slightly broken when running `ihp-new --elm MyProject`

Reference to the issue:
https://twitter.com/augustin82/status/1482107852592492544

**Comment by mpscholten** [comment]
Thanks for reporting 👍 Fixed via https://github.com/digitallyinduced/ihp-boilerplate/commit/7f7da91540e2b35b4a01d34e9284bfb19a4e87e5
