### ISSUE TITLE
Expose more fields in CustomerSubscriptionUpdated Stripe webhook

### ISSUE THREAD

**Issue by stephenbenedict** [digitallyinduced/ihp#1322]
When a customer updates their subscription and the `CustomerSubscriptionUpdated` webhook is triggered, only the following fields from Stripe's JSON response are exposed:

`subscriptionId`
`cancelAtPeriodEnd`
`currentPeriodEnd`

When a subscription has multiple pricing plans, however, I need to know the product or price id after the subscription is updated in order to determine if the customer has upgraded or downgraded (the subscription id does not change when a pricing plan is changed).

The raw JSON response object is available via `subscription` but myself (and I imagine other novices) will have difficulty parsing that.

**Comment by mpscholten** [comment]
I've just pushed an update to pro. Now you can access the price like this:

```haskell
on CustomerSubscriptionUpdated { subscription = stripeSubscription } = do
    let (Just price) = stripeSubscription |> get #items |> get #_data |> map (get #price) |> headMay
    let priceId = get #id price
```

**Comment by stephenbenedict** [comment]
Thanks! I just tried the latest build and it works great, except that it appears to introduce a bug when you try to open the Customer Portal:

```
JSONError "Error in $.items.data[0].price.nickname: parsing Text failed, expected String, but encountered Null"
```

When I downgrade to the IHP build I was using before, the error goes away.

Also, I do not know why, but to get your code to work I had to change `#_data` to `#data_`

**Comment by mpscholten** [comment]
> Thanks! I just tried the latest build and it works great, except that it appears to introduce a bug when you try to open the Customer Portal:


Just pushed a fix for this. The new build is building right now 👍 

> Also, to get your code to work I had to change #_data to #data_. The error I was getting before making the change:

Typo :)

**Comment by stephenbenedict** [comment]
Brilliant! Works great now. Out of curiosity, why is the underscore after `#data_` necessary? The JSON object does not appear to include the underscore so I presume this is to avoid some naming conflict?

**Comment by mpscholten** [comment]
> Brilliant! Works great now

Perfect 👍 

> Out of curiosity, why is the underscore after #data_ necessary?

`data` is a reservered keyword in haskell. So we cannot write a data structure like this:
```haskell
data SubscriptionItemsCollection = SubscriptionItemsCollection { data :: [SubscriptionItem] }
```
The `data` field will cause a compile-time error because GHC doesn't expect another data definition there. By adding an underscore it will not think this is the `data` keyword, instead it just accepts this as a normal field name then. So this works:

```haskell
data SubscriptionItemsCollection = SubscriptionItemsCollection { data_ :: [SubscriptionItem] }
```
