### ISSUE TITLE
Fails to build on NixOS 20.03 with default settings

### ISSUE THREAD

**Issue by bbuscarino** [digitallyinduced/ihp#137]
When following the getting started guide and running `ihp-new blog`, the project is scaffolded as expected and then attempts to build itself. When building, it fails with the following error:
```shell
Configuring hspec-discover-2.7.1...
CallStack (from HasCallStack):
  die', called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1022:20 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:475:12 in Cabal-3.0.1.0:Distribution.Simple.Configure
  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.0.1.0:Distribution.Simple
  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.0.1.0:Distribution.Simple.UserHooks
  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.0.1.0:Distribution.Simple
  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.0.1.0:Distribution.Simple
  defaultMain, called at Setup.lhs:3:10 in main:Main
Setup: Encountered missing or private dependencies:
hspec-meta >=2.3.2
```
Steps to reproduce:
1. `nix-env -f https://beta:beta@ihp.digitallyinduced.com/ihp-new.tar.gz -i ihp-new`
2. `idh-new blog` or `cd blog; nix-build` or `cd blog; ./start`
3. 💥

The solution that gets me a running app is bumping `nixPkgsRev` in `nixpkgs-config.nix` to `cd555fdab23426a655746798bd6e253eb8c08bd0`, which is the latest revision of nixpkgs as of writing.

I'm relatively new to Haskell in general and would still consider myself a beginner, but here are the steps I tried before bumping nixpkgs:
1. Adding `hspec-meta` to haskellDeps in default.nix. This resolves the issue with `hspec-meta`, but the same error appears but now with `case-insensitive -any`. Adding `case-insensitive` also does not change anything.
2. Adding `hspec-meta` and `case-insensitive` to `App.cabal`.
3. Changing versions of `ihp`.

System information:
* System: NixOS 20.03
* IHP: `5f6a7e7ca3a3859b7a5319625d945ecc877aa3a6`

**Comment by Laobiz** [comment]
Thanks for letting us know. We are reproducing the problem at the moment and let you know when we merge a fix for it :)

**Comment by Laobiz** [comment]
I see that you have used `nix-build` to try to start the DevServer. `nix-build` is used to build a package described inside of default.nix. We are not describing a complete package but an environment for the `nix-shell` command which can be used by our scripts. Can you try to start the Dev Server with `./start`?

**Comment by bbuscarino** [comment]
@Laobiz `./start` yields the same results.
> `nix-build` is used to build a package described inside of default.nix.
Yes that is true, running `nix-build` after updating nixpkgs doesn't result in a running DevServer, but it makes it through the build process.
