### ISSUE TITLE
Add operator for `pure . `

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1383]
Code like this:

```haskell
...
   |> withCustomErrorMessageIO "Name is already taken" validateIsUnique #name
   >>= return . validateField #name nonEmpty
```

should be able to be written with a shorter operator, e.g. `=>`:

```haskell
...
   |> withCustomErrorMessageIO "Name is already taken" validateIsUnique #name
   => validateField #name nonEmpty
```

**Comment by s0kil** [comment]
`=>` cannot be used as the compiler fails with "error: parse error on input `=>'", maybe because it's used to create type class constraints in functions?

**Comment by s0kil** [comment]
Also, what you are trying to do is already available in the `Data.Functor` module, as the [`<&>`](https://hackage.haskell.org/package/base-4.16.0.0/docs/Data-Functor.html#v:-60--38--62-) function.

**Comment by mpscholten** [comment]
For consistency i'd like to use something that looks close to the normal arrow, maybe `|>>` or `|>~`

**Comment by s0kil** [comment]
`|>>` looks good
