### ISSUE TITLE
PostgreSQL Function Accept Parameters

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#1397]
Reference: https://www.postgresql.org/docs/current/sql-createfunction.html

**Comment by mpscholten** [comment]
Can you share the sql function that didn't work?

**Comment by s0kil** [comment]
The function starts as:
```sql
CREATE FUNCTION message_thread_id(message_to TEXT, message_from TEXT) RETURNS TEXT LANGUAGE plpgsql AS $$
```

It fails because of: https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/SchemaDesigner/Parser.hs#L569

**Comment by mpscholten** [comment]
Ah got it thx 👍
