### ISSUE TITLE
IHP Cloud returns Nginx 502 Bad Gateway

### ISSUE THREAD

**Issue by rametta** [digitallyinduced/ihp#1414]
Hello, not sure if the correct place to post this issue, but my site that is hosted on ihp cloud is always returning 502 bad gateway https://retros.ihpapp.com/ it use to work fine but at some point it started failing. I tried restarting the app from admin section but that didn't help either.

Any ideas on the problem? Thank you

**Comment by mpscholten** [comment]
Might be failing because the IHP version is a bit outdated :) I'll make a PR to update it to the latest IHP version. Could you start a new deployment after the PR is merged?

**Comment by mpscholten** [comment]
PR at https://github.com/rametta/retros/pull/3 👍

**Comment by rametta** [comment]
It worked, thank you for your help @mpscholten much appreciated!
