### ISSUE TITLE
Value from selectField not passed to target ?

### ISSUE THREAD

**Issue by axelbdt** [digitallyinduced/ihp#1415]
Hello,
I am using a selectField to set a foreign key in my new view, namely selecting a client for for the creation of a bill.
Whatever I select from the list, the creation will be rejected because what is passed is an empty uuid (0000-000...).

Generated HTML:
```html
<select name="clientId" id="bill_clientId" class="form-control" value="00000000-0000-0000-0000-000000000000"><option selected="selected" disabled="disabled">Please select</option> <option value="4765b118-41cf-4735-8338-75a14daadc40">Alice</option><option value="732daf6a-5437-4129-9f03-28337d9c09e4">Bob</option></select>
```
Is there a bug in the selectField implementation?
I don't think anything from my controller or view causes this, but here is the code for reference.
Bills.hs (controller):
```haskell
action NewBillAction = do
        ensureIsUser
        currentTime <- getCurrentTime
        userClients <- query @Client
             |> filterWhere (#userId, currentUserId)
             |> fetch
        let bill = newRecord
                |> set #date (currentTime |> utctDay)
        render NewView { .. }
```

New.hs:
```haskell
renderForm bill userCLients = formFor bill [hsx|
    {(selectField #clientId userClients)}
|]

instance CanSelect Client where
    type SelectValue Client = Id Client
    selectValue client = get #id client
    selectLabel client = get #firstName client ++ " " ++ get #lastName client

```

**Comment by axelbdt** [comment]
Turns out the client_id was added to the schema after I generated the Controller, so it was missing from the list of filled fields:
```haskell
buildBill bill = bill
    |> fill @["date","userId","clientId"]
```
Apologies for unneeded issues, what I needed was a rubber duck.

**Comment by mpscholten** [comment]
No worries, we're happy to be your rubber duck 👍  :)
