### ISSUE TITLE
Don't Ignore File Upload Errors

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#1425]
Currently, if there is an error when uploading a file, it will be ignored. We should log this error:
Examples:
https://github.com/digitallyinduced/ihp/blob/master/IHP/FileStorage/ControllerFunctions.hs#L118
https://github.com/digitallyinduced/ihp/blob/master/IHP/FileStorage/ControllerFunctions.hs#L356
In both cases `runMinio` returns an Either which is ignored.

**Comment by s0kil** [comment]
The exceptions are handled when using the `uploadToStorageWithOptions` function: https://github.com/digitallyinduced/ihp/blob/master/IHP/FileStorage/ControllerFunctions.hs#L292-L299

However, using functions such as `storeFile`, it's not clear that an exception occurred, so should we explicitly return `IO (Either SomeException StoredFile)` forcing the user to handle both cases, or add documentation examples on how to handle errors?

**Comment by s0kil** [comment]
Another option is to add "overloaded" function `storeFile'` that will return `IO (Either SomeException StoredFile)`
Similar to how we have `param` and `paramOrNothing`

**Comment by mpscholten** [comment]
To work as expected we should make `storeFileWithOptions` throw an Exception in an error case. [Then it's catched here](https://github.com/digitallyinduced/ihp/blob/master/IHP/FileStorage/ControllerFunctions.hs#L295)
