### ISSUE TITLE
Issue with null coalescing unique indexes?

### ISSUE THREAD

**Issue by njaremko** [digitallyinduced/ihp#1451]
I have the following unique index setup in my schema, and IHP can't seem to parse it correctly. Any change I make to the schema or just restarting the app, causes it to say I have un-migrated changes in which it drops and recreates this index.
```sql
CREATE UNIQUE INDEX user_invite_uniqueness ON user_invites (organization_id, email, coalesce(expires_at, '0001-01-01 01:01:01-04'));
```

**Comment by mpscholten** [comment]
Cannot reproduce this with IHP v0.20. Can you check that the error still happens?

Here's also two tests that should be failing with your SQL snippet: https://github.com/digitallyinduced/ihp/pull/1522
