### ISSUE TITLE
Web/Controller: getDirectoryContents:openDirStream: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by Swordlash** [digitallyinduced/ihp#1453]
Hi,

I've just installed the new version of IHP (v0.19) which is supposed to work with M1 macs. I was super pumped. After installing `ihp-new` according to the guide and running `ihp-new blog` and `./start`, I get a following error:
<img width="806" alt="image" src="https://user-images.githubusercontent.com/26578969/167196239-c8d33529-ea2c-4315-8497-f1014178ccb9.png">

Indeed, the file mentioned in the screenshot is not present in the directory:
```
mateusz@mateuszs-mbp blog % tree
.
├── App.cabal
├── Application
│   ├── Fixtures.sql
│   ├── Helper
│   │   ├── Controller.hs
│   │   └── View.hs
│   ├── Schema.sql
│   └── Script
│       └── Prelude.hs
├── Config
│   ├── Config.hs
│   ├── client_session_key.aes
│   └── nix
│       ├── haskell-packages
│       └── nixpkgs-config.nix
├── Main.hs
├── Makefile
├── Setup.hs
├── build (lots of files here)
│   └── ihp-lib -> /nix/store/izdpnkzprlr3iiny979yz78p9nn9bl7b-ghc-8.10.7-with-packages/bin/../lib/IHP/
├── default.nix
├── hie.yaml
├── result -> /nix/store/g49yw2f3mdz3180rp25vlv6wj7mylp9i-app
├── start
└── static
    ├── app.css
    ├── app.js
    ├── favicon.ico
    └── ihp-welcome-icon.svg

39 directories, 1252 files
```
I think I had the same issue with previous version. What should I do?

**Comment by mpscholten** [comment]
It looks like the project was generated incompletely (the `Web/` directory) is missing.

Can you share the output of `ihp-new blog`? maybe there's an error message or warning in there

**Comment by Swordlash** [comment]
I removed the project and run `ihp-new blog` again and it seems to work now.

**Comment by mpscholten** [comment]
Sounds good. If the issue happens again in the future please let me know
