### ISSUE TITLE
After start ihp in wsl2, my disk IO is fulfilled

### ISSUE THREAD

**Issue by nodew** [digitallyinduced/ihp#146]
![image](https://user-images.githubusercontent.com/9988582/85720360-eeb79080-b722-11ea-96f6-639ec2f81647.png)

**Comment by nodew** [comment]
Looks like the issue of wsl2 itself.

**Comment by mpscholten** [comment]
In case you find a solution, let us know, then we can extend the docs for wsl :)

**Comment by nodew** [comment]
To prevent wsl2 take too much mem of my system, I limited the mem for wsl2 to 4G by .wslconfig. While there's no more mem, then wsl2 will try to read from disk, I don't know why, but may be caused by swap file mechanism, which cause the disk is fully occupied.
