### ISSUE TITLE
Add hint to start editor in project directory

### ISSUE THREAD

**Issue by Vlix** [digitallyinduced/ihp#1460]
I've been debugging for a few hours and getting really annoyed that HLS just didn't work out of the box, and even with tons of fiddling, it would not get the right GHC version.

Turns out, I had to start `code` from within the IHP project directory.

For someone who's never used Nix, this is not obvious, so it might be nice to give a warning/footnote about this in the guide when the beginner starts using their editor?

**Comment by mpscholten** [comment]
Did you use the nix-env-selector plugin as described in the docs? With this plugin I would expect this to work even when not started from the IHP project dir

**Comment by Vlix** [comment]
I doubt it, because `nix-env-selector` doesn't ring a bell.

After looking for it just now, I found it in the `Editors & Tooling` section. This section's a bit far down after you've pretty much gone through the entire tutorial (I didn't get that far) so my recommendation would be to put that section at/near the top of "The Basics".

I see that in `Installing IHP`, there's a section all the way at the bottom which says "Setting up your editor", but I already had VSCode installed and HLS set up for my work, so I just skipped it (again, I don't know the specifics of Nix, so had no idea anything like this would be a problem)

**Comment by mpscholten** [comment]
I've pushed some changes to the docs via https://github.com/digitallyinduced/ihp/pull/1526 Can you take a look and provide feedback?

**Comment by Vlix** [comment]
I think that looks sufficient. 👍

**Comment by mpscholten** [comment]
Perfect, just merged it 👍
