### ISSUE TITLE
Fix admin interface colors in Firefox and Orion

### ISSUE THREAD

**Issue by stephenbenedict** [digitallyinduced/ihp#1462]
The admin interface colors in 0.19 appear incorrect in Firefox and Orion. Safari and Chrome look fine.

![Screen Shot 2022-05-10 at 10 05 41 PM](https://user-images.githubusercontent.com/37129386/167635726-eb7776d7-14b6-4e11-b17f-859cd1d10e58.png)

**Comment by stephenbenedict** [comment]
You were right. Should have thought of that! Clearing cache fixed this.

**Comment by mpscholten** [comment]
Perfect 👍
