### ISSUE TITLE
Update nix install instructions? 

### ISSUE THREAD

**Issue by abathur** [digitallyinduced/ihp#1470]
Triaging a nix install issue reported against the nix repo and just wanted to let you know that the mac instructions on your site are a little out of date. I guess that comes from
https://github.com/digitallyinduced/ihp/blob/657cc941eff0bf4102e57b6d6880c03e06831257/Guide/installation.markdown#mac

One option might just be linking the official instructions (https://nixos.org/download.html#nix-install-macos), but even if you keep a local copy I would still recommend pulling the secondary instruction set that links one of my test installers. I am not sure which PR it's from, but the changes should be released by now. It'll be out of date at best, and may disappear on short notice since it's served out of a free cachix cache!

**Comment by mpscholten** [comment]
Thanks for letting us know! :) Fixed this via https://github.com/digitallyinduced/ihp/commit/04cc51ed2d181745079b5fa2cf8596ddacb516ef
