### ISSUE TITLE
Concurrent jobs are overlapping even with `maxConcurrency = 1`

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1488]
I was trying this [Seat reservation](https://github.com/Gizra/ihp-simple-seat-reservation) demo app, with latest `master`

In the past, when running multiple concurrent requests, it would get the seat reservations right. Currently, with latest `master` we get the following (notice the order and duplicate seat numbers):

![image](https://user-images.githubusercontent.com/125707/183150110-67cbd04b-e39c-4644-9233-c01980a482ef.png)

We have set [maxConcurrency = 1](https://github.com/Gizra/ihp-simple-seat-reservation/blob/316c84d6202acb05aa9398b5c5224c2058cc648c/Web/Job/Reservation.hs#L53), so the Job should be processed one after the other

## Steps to reproduce

1. Install repo
2. Goto http://localhost:8000/ShowEvent?eventId=7a7e856f-8475-48f5-977b-21bb85133a88
3. Copy the code and execute it on the command line - the code runs requets with `parallel`
![image](https://user-images.githubusercontent.com/125707/183150563-8f95918b-7f6e-43d5-935b-565fb297d996.png)

**Comment by amitaibu** [comment]
@mpscholten :wave: were you able to reproduce?

**Comment by mpscholten** [comment]
I can reproduce this 👍

**Comment by mpscholten** [comment]
Couldn't find any obvious issues yet, need to dig a bit deeper

**Comment by mpscholten** [comment]
Just found the issue and fixed it via https://github.com/digitallyinduced/ihp/commit/5927bc273c23e3207102ca4dd1700cb4c478ee7b

We had an expression `[0..(maxConcurrency @job)]` to generate a worker for each concurrency defined.  When `maxConcurrency = 1`, this yields `[0..1]` which is `[0, 1]`. This then starts two workers :) So the job worker was always running with two concurrency workers.

After I applied the fix locally everything seemed to work as expected :)

**Comment by amitaibu** [comment]
Works again :smile: 

![image](https://user-images.githubusercontent.com/125707/187037454-0c53839e-c21d-4f1a-a5cf-99f7ff7c9fc0.png)
