### ISSUE TITLE
Suggestion: Integrate "Diagnose"

### ISSUE THREAD

**Issue by ShalokShalom** [digitallyinduced/ihp#1494]
Haskell is famous for its very cryptic error messages. 

This small, wonderful library goes a huge step forward in order to solve this. 

I do suggest that you evaluate the integration of it to IHP. 

https://github.com/Mesabloo/diagnose

Much thanks 👍🏻

**Comment by mpscholten** [comment]
Do you have specific error messages in mind that we could improve with that?

**Comment by ShalokShalom** [comment]
That would improve all error messages.
