### ISSUE TITLE
IHP v1.0 release

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1501]
It's time we finally tag the 1.0 in 2022 :)

In this issue we should collect pending things to do until we're ready to launch.

- [x] Fix HSX issues introduced in v0.20
- [x] Create Release Candidate: 17.10.2022 (https://github.com/digitallyinduced/ihp/releases/tag/v1.0.0-rc1)
- [x] Announce the upcoming release date on the mailing list a few days before
- [x] Add the case study page to the IHP website
- [x] Planned release date: 24.10.2022, 18:00 CET / 9am PT

**Comment by francisdb** [comment]
Looks like this can be closed?
https://ihp.digitallyinduced.com/blog/c479f341-1374-496a-96d6-7af647005b21-ihp-1-0
