### ISSUE TITLE
Request: Update `.ghci` to include `:l Main`

### ISSUE THREAD

**Issue by Qqwy** [digitallyinduced/ihp#1506]
### Current situation

Currently, whenever `make console` is run, you end up in a GHCi shell where you do not have access to any of your app's modules yet.
Before you can do anything, you need to run `:load Main` (or `:l Main` for short). Otherwise, they will not be found by any `import ...`or `import qualified ...` commands.

This extra step might confuse people (as it certainly confused me) coming from other Haskell project management tools, or also people new to Haskell all-together.

### Request

Wanting to run GHCi in your project without all your modules having been loaded is probably rather rare.
I suggest that we amend ihp's `.ghci` to include the `:load Main` step, so this happens automatically at startup.

**Comment by Qqwy** [comment]
Is there a disadvantage to having the HLS also execute the `:l Main`? (Doesn't HLS already do this internally somewhere?)

Regardless of whether you decide if it is worth it to add this to IHP proper, I agree that improving the documentation would be a great idea! :+1:

**Comment by mpscholten** [comment]
> If I'm not mistaken, we don't load Main because .ghci is also loaded by Haskell Language Server.

HLS uses the `.hie-bios` file for loading it's configuration.

The only thing we need to be careful about is that the IHP dev server still works. The dev server itself also calls `:l Main`, so we mostly need to make sure it's not called twice (that would be slow for large projects).

I've pushed https://github.com/digitallyinduced/ihp/pull/1508 to fix this
