### ISSUE TITLE
Declarative Nix installation how-to

### ISSUE THREAD

**Issue by sir4ur0n** [digitallyinduced/ihp#1507]
Hello,

I am fiddling with IHP these days and I noticed the [installation documentation](https://ihp.digitallyinduced.com/Guide/installation.html) does not provide instructions on declarative Nix installation. The only Nix installation mode is "stateful" using `nix-env`.

I also searched in this repo's issues but found no issue about Nix (Flake) installation.

How do you feel about adding instructions to install IHP in a declarative way?

Ideally both "Legacy Nix" and "Flake" instructions would be provided.

For what it's worth/in case anyone is interested/searches for information in this repository, I seem to have managed to install IHP on my flakified NixOS (I also use Home manager but that should be irrelevant) with the following:

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    ihp = {
      url = "https://downloads.digitallyinduced.com/ihp-new.tar.gz";
      # IHP does not currently provide a `flake.nix` file, only a `default.nix`, so we will manually import it in the `outputs`
      flake = false;
    };
  };

  outputs = { self, nixpkgs, ihp }:
    let
      system = "x86_64-linux";
      ihp-overlay = final: prev: {
        # Make sure that `ihp-new` uses the same Nix packages as the rest
        ihp-new = import ihp { pkgs = nixpkgs.legacyPackages.${system}; };
      };
    in
    {
      nixosConfigurations.nixos-sir4ur0n = nixpkgs.lib.nixosSystem {
        inherit system;
        modules = [
          ({ ... }: { nixpkgs.overlays = [ ihp-overlay ]; })
          # Other modules...
        ];
        # Other attributes...
      };
    };
}
```
Then add `ihp-new` in your installed packages; be it in `configuration.nix`, `home.nix`, or wherever you configure your packages.

Thank you for your work on IHP, it looks pretty neat!

**Comment by mpscholten** [comment]
Thanks for the suggestion 👍 Making IHP easy to work with NixOS is definitely something we should do.

We could also get `ihp-new` into nixpkgs directly. That way it can be added to a NixOS system by e.g. adding it to `/etc/nixos/configuration.nix`.

Btw: Flakes also seem to be a good fit for replacing `nix-shell` inside IHP projects. Especially with the direnv integration and it's support for providing faster nix-shell's.

**Comment by sir4ur0n** [comment]
Once https://github.com/NixOS/nixpkgs/pull/189561 is merged (thank you by the way), I suggest we keep this issue open until the IHP documentation is updated, do you agree? If so, I suggest removing `Closes ...` in the PR description :sweat_smile:

**Comment by mpscholten** [comment]
yes 👍 good point, removed the `Closes` from the other issue :)

**Comment by mpscholten** [comment]
✅
