### ISSUE TITLE
Feature Request: Add support for existing databases

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1511]
Right now we are not able to connect the IHP application to existing databases that have data in them because IHP hasn't generated types for the existing relations.

**Comment by mpscholten** [comment]
Can't you dump the database schema and then put it into the `Schema.sql`?

E.g. like this:

```bash
pg_dump -s --no-owner --no-acl "postgresql://my_user:my_password@my_host/my_database" | sed -e '/^--/d' > Schema.sql
```

**Comment by rvarun11** [comment]
Yes, that should work. Closing!
