### ISSUE TITLE
Update `ihp-hsx` Hackage package

### ISSUE THREAD

**Issue by billksun** [digitallyinduced/ihp#1516]
`ihp-hsx` on Hackage is still bound to `base` >=4.1 && <=4.16. This should be updated so GHC 9.x can be used.

**Comment by mpscholten** [comment]
I've just pushed a new release to hackage https://hackage.haskell.org/package/ihp-hsx-0.20.0 Lmk if this works now :) 👍

**Comment by billksun** [comment]
Sorry for the late confirmation, I was waiting for haskell.nix's cache to update. It did today, and `ihp-hsx 0.20.0` works!

**Comment by mpscholten** [comment]
Thanks, good to hear it's working now 👍  (no worries, just wanted to close so it's out of my head :) )
