### ISSUE TITLE
Compilation breaks when selecting Float in Schema designer

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#152]
First of thanks, for building such a great piece of software. Its a nice opportunity for me to dive into Haskell! Then considering my little experience with Haskell you might need to take this issue with a grain of salt.

## Steps to reproduce
1. `ihp-new test`
2. `cd test` and `./start`
3. create new table in schema designer, add column, select datatype `Float`
4. update and push to db

## Expected

succesfull compilation

## Bug

received `Compilation error`, it seems selecting `Float` does map to `REAL`, but that in turn does not map back to the `Float` Haskell type.

I think this can be fixed by adding altering the `IHP/SchemaCompiler.hs`, where it says `"FLOAT" -> "Float"` which probably should be `"REAL" -> "Float"`

**Comment by mpscholten** [comment]
Thanks for your feedback and also thanks for reporting the bug :) This will be fixed via #154 which should be part of the next release.

If you don't want to wait til the next release (10.07.) you can also just update to the specific commit of the fix by changing line 4 in your projects `default.nix` to `rev = "e3be1302d9a256480cc243ea2f1e2e7600b1ae33";`. Then rebuild everything using `nix-shell -j auto --cores 0 --run 'make -B .envrc'`. After that you can use the project as usual by using `./start`.

**Comment by themmes** [comment]
That's great thank you, I was already wondering how to do that in Nix (I'm also new to Nix 🤦 ).

However, for now I solved it by simply `s/REAL/Float/g` in `build/Generated/Types.hs`.
