### ISSUE TITLE
The mailing list link on "Your First Project" is broken

### ISSUE THREAD

**Issue by sisyphushappy** [digitallyinduced/ihp#1525]
# Steps to reproduce

Go to the [Have Fun](https://ihp.digitallyinduced.com/Guide/your-first-project.html#have-fun) section of the "Your First Project" guide. Click the link [To stay in the loop, subscribe to the IHP release emails.](http://eepurl.com/g51zq1); it is a MailChimp 404. I couldn't find another link to the mailing list so I couldn't submit a PR, but this is the offending line of code: https://github.com/digitallyinduced/ihp/blob/master/Guide/your-first-project.markdown?plain=1#L1158.

**Comment by mpscholten** [comment]
Thx for reporting this 👍 

Just pushed a fix via https://github.com/digitallyinduced/ihp/commit/f2c359a3cf7f5c14ab934923cebdaff99f1c464b 

The new link is https://ihp.digitallyinduced.com/MailingList
