### ISSUE TITLE
Programmatically created HSX attribute values should not be escaped

### ISSUE THREAD

**Issue by billksun** [digitallyinduced/ihp#1527]
I'm running into an issue when using HSX with TailwindCSS. I want to use [arbitrary variants](https://tailwindcss.com/blog/tailwindcss-v3-1#arbitrary-values-but-for-variants), but it requires using some HTML reserved characters to construct the CSS selector. In my case, I needed to use `&`. This is fine when the `&` is entered in HSX directly:
``` haskell
html = [hsx|
  <div class="someClassName&">
    Hello World
  </div>
|]
```

However, when the attribute value is obtained from a function, the `&` is converted to the escaped form `&amp;`:

```haskell
html = [hsx|
  <div class={style}>
    Hello World
  </div>
|]
  where
    style="someClassName&"
```

The above code will generate the following HTML:

```html
<div class="someClassName&amp;">
  Hello World
</div>
```
This breaks TailwindCSS and I get the following parse error:
```
Error: Expected a backslash preceding the semicolon.
```

**Comment by billksun** [comment]
Actually I just realized this isn't specific to attributes. Same thing happens if you place `{style}` anywhere in the hsx block.

**Comment by mpscholten** [comment]
It's possible using `preEscapedTextValue` and a instance. I've added tests + docs for this via https://github.com/digitallyinduced/ihp/pull/1528
