### ISSUE TITLE
Option to generate RESTful only app

### ISSUE THREAD

**Issue by Eliot00** [digitallyinduced/ihp#1532]
I hope ihp-new could provide a new option which could generate a RESTful only template.

**Comment by mpscholten** [comment]
Could you share a bit more on what you expect from RESTful only?

**Comment by Eliot00** [comment]
Maybe like [this](https://github.com/yanpitangui/dotnet-api-boilerplate/blob/main/src/Boilerplate.Api/Controllers/UserController.cs), includes serialize/deserialize, JWT.

Also I would like to know if it is possible to use this file structure:

```
// From nestjs
// Module structure
// Add folders according to module scale. If it's small, you don't need to add folders.
+-- src/greeter
|   +-- * // folders
|   +-- greeter.constant.ts
|   +-- greeter.controller.ts
|   +-- greeter.service.ts
|   +-- greeter.module.ts
|   +-- greeter.*.ts
|   +-- index.ts
```
