### ISSUE TITLE
Responsive issues with the starter app

### ISSUE THREAD

**Issue by M-Gonzalo** [digitallyinduced/ihp#1547]
This is only a cosmetic issue.

After redimensioning its window, localhost:8000 loses the side margins in the first grey rectangle:

![image](https://user-images.githubusercontent.com/23223606/195297782-bfe7013c-5d54-48c8-ba65-e2e8919e3b8d.png)

It happens at exactly 991px window width.

**Comment by mpscholten** [comment]
Thanks for reporting 👍  Just pushed a fix:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/2072185/196249676-613fbe7a-ea0f-4d7b-8dd7-b0af4a1d30c1.png">

**Comment by DKurilo** [comment]
Oh, sorry, I created one more PR that also fixes image bellow.
Feel free just delete my PR.
