### ISSUE TITLE
Compilation breaks when naming a database field "type"

### ISSUE THREAD

**Issue by hendi** [digitallyinduced/ihp#157]
`build/Generated/Types.hs:383:71: error: parse error on input 'type'`

**Comment by mpscholten** [comment]
I guess this applies to all haskell keywords like `data`, etc. :)

**Comment by hendi** [comment]
Yes, this affects all reserved keywords in Haskell.

The easiest fix would probably be to blacklist these names, and add a JS hint and suggest renaming or appending `_`
