### ISSUE TITLE
make ghci - problem

### ISSUE THREAD

**Issue by agreif** [digitallyinduced/ihp#1574]
Hi,
just installed IHP on NixOS 22.11
and the call to:
```
make ghci
```

throws this error:
```
$ make ghci
ghci -package-env -
make: ghci: No such file or directory
make: *** [build/ihp-lib/Makefile.dist:230: ghci] Error 127
```

I am working with:
```
 $ ihp-new --version

ihp-new version: 1.3.0
```

**Comment by agreif** [comment]
got a step further, first I had to get into the `nix-shell`, where `ghci` is available.
But if I do `make ghci` as described in https://ihp.digitallyinduced.com/Guide/scripts.html then I get 
```
[nix-shell:~/project/ihp-blog]$ make ghci
Makefile:30: build/ihp-lib/Makefile.dist: No such file or directory
make: *** No rule to make target 'build/ihp-lib/Makefile.dist'.  Stop.
```

On the other hand if executing `ghci` directly, I gat this exception:
```
[nix-shell:~/project/ihp-blog]$ ghci
GHCi, version 9.2.4: https://www.haskell.org/ghc/  :? for help
*** Exception: build/ihp-lib/applicationGhciConfig: openFile: does not exist (No such file or directory)
Loaded GHCi configuration from /home/agreif/project/ihp-blog/.ghci
```
`build/ihp-lib` is a broken link to
```
[nix-shell:~/project/ihp-blog]$ ll build/ihp-lib 
lrwxrwxrwx 1 agreif agreif 82 Dec 23 18:58 build/ihp-lib -> /nix/store/vl342fva3bddhh65vsckwv0ygv0hh93g-ghc-9.2.4-with-packages/bin/../lib/IHP
```

the file is sitting here:
```
# find / -name applicationGhciConfig
/nix/store/c166q1rmz9srlhka7jr8nwlvrdv93wgw-ghc-9.2.4-with-packages/lib/IHP/applicationGhciConfig
```

**Comment by agreif** [comment]
I think I solved it...
I ran './start' that rebuilt the 'build' directory and fixed the `ihp-lib`symlink.
Now I can run `ghci` inside `nix-shell'` and also without it.

IMO this ticket can be closed :)
thanks,
Alex.

**Comment by agreif** [comment]
closed

**Comment by agreif** [comment]
no idea. I did not do a nix gc. As it was my first test project with ihp I tried a few things, but I dont know when it got wrong. Later I can make a new test and check the symlink in different scenarios. I still use the same unchanged server, so I hope the problem shows up again.

**Comment by mpscholten** [comment]
ok, thanks for trying to reproduce 👍 https://github.com/digitallyinduced/ihp/issues/1572 might make this whole thing a bit more stable in the future
