### ISSUE TITLE
Add GitHub Codespaces in Guide

### ISSUE THREAD

**Issue by rvarun11** [digitallyinduced/ihp#1602]
We should add a section about how to configure GitHub Codespaces for IHP [here](https://github.com/digitallyinduced/ihp/blob/3b22b8793e21605cde7c17f7718ea20b4b1e12d0/Guide/installation.markdown?plain=1#L148).

**Comment by rvarun11** [comment]
Can this be assigned to me?

**Comment by mpscholten** [comment]
Just assigned 👍
