### ISSUE TITLE
ihp-ssc.js replaceNode fails when trying to replace text node

### ISSUE THREAD

**Issue by duelistone** [digitallyinduced/ihp#1608]
Updating a component may request that a text node, rather than a typical DOM element, be replaced. However, my understanding (and my browser's complaining) is that text nodes do not have the querySelectorAll method. As a result, when asked to update a text node, the following function hits the error "Uncaught TypeError: nodeOperation.domNode.querySelectorAll is not a function or its return value is not iterable" in the function
```
function replaceNode(component, nodeOperation) {
    nodeOperation.domNode.outerHTML = nodeOperation.newNodeHtml;
    if (debugMode) console.log('A#######', nodeOperation.domNode);
    for (var component of nodeOperation.domNode.querySelectorAll('.ihp-ssc')) {
        initalizeSSC(component);
    }
}
```

I implemented the following fix for my project, figuring that a text node would never have a subnode with the ihp-ssc (or any) class.
```
function replaceNode(component, nodeOperation) {
    nodeOperation.domNode.outerHTML = nodeOperation.newNodeHtml;
    if (debugMode) console.log('A#######', nodeOperation.domNode);
    if (nodeOperation.domNode.type == Node.ELEMENT_NODE) {
        for (var component of nodeOperation.domNode.querySelectorAll('.ihp-ssc')) {
            initalizeSSC(component);
        }
    }
}
```
I'm not completely sure if the Node.ELEMENT_NODE notation works in all browsers; alternatively, we can write this as 1. I also don't know if other types of DOM nodes can have element subnodes; if so, we would have to add more possibilities to the conditional.

**Comment by mpscholten** [comment]
Thanks for reporting this! According to https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType the other node types seem not relevant and your solution should cover the case correctly. It also seems to be supported in all browsers. Maybe you can make a PR?
