### ISSUE TITLE
Deleting column with trigger generates a migration that does not drop the trigger

### ISSUE THREAD

**Issue by stephenbenedict** [digitallyinduced/ihp#1630]
To reproduce, within the IDE add an `updated_at` column to a table, migrate the database, then remove the same column and migrate again. The second migration that is generated does not include `DROP TRIGGER ...` so the trigger remains in the database, throwing an error whenever you try to update a record. At least, I think this is the problem. Manually running a `DROP` query fixes it.

The error you get is like `record "new" has no field "updated_at"` which is confusing since you have removed the `updated_at` field.

**Comment by mpscholten** [comment]
Just debugged this and it turns out that IHP already detected that the trigger needs to be removed, but we have never implemented a `DROP TRIGGER` operation, so the IHP migration system ignored the trigger.
