### ISSUE TITLE
Nix build error for >1.0.0 builds

### ISSUE THREAD

**Issue by stephenbenedict** [digitallyinduced/ihp#1637]
Trying to build IHP when using the latest IHP Pro build results in this error:

```
unknown compression method 'zstd'
cannot build derivation '/nix/store/pdnm3405g0bqaz77sdqib6ni49w9mx65-ghc-9.2.4-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/pdnm3405g0bqaz77sdqib6ni49w9mx65-ghc-9.2.4-with-packages.drv' failed
```

Using build 1.0.0 does not cause this error. It is some build after 1.0.0 that causes this, though perhaps due to something particular to my system.

**Comment by amitaibu** [comment]
Upgrading nix fixed it for me

**Comment by mpscholten** [comment]
Yep, this problem is caused by an outdated nix 👍  After updating to the latest nix version it should be working again. We've reported this problem upstream to cachix/nix in the past and they suggested that updating nix is the best solution as the error only happens with nix versions that haven't been updated more than a year, and it's best to update then anyways.

**Comment by stephenbenedict** [comment]
Thanks for the tips. I just tried building IHP again after updating nix (now on version 2.13.3, was on 2.3.15) but am running into the same error. Will play around with my setup to see what else could be the problem.

**Comment by stephenbenedict** [comment]
Just tried installing a new app with `ihp-new` which worked without a problem (on v1.0.1). Not sure what has changed that fixed the problem.

**Comment by AriFordsham** [comment]
What is defined as an out-of-date Nix version? Older than a year?

**Comment by mpscholten** [comment]
2 years or older, see https://github.com/cachix/cachix/issues/508#issuecomment-1447548559

**Comment by AriFordsham** [comment]
Is there a specific version where this problem goes away, or is it a sliding window?

**Comment by mpscholten** [comment]
Likely a specific version, but I don't know which version exactly (most people that had this issue just updated to the latest version)

**Comment by AriFordsham** [comment]
The relevant version is >=2.4, where zst compression was introduced (via libarchive)
