### ISSUE TITLE
Fix all GHC warnings that happen during compilation of IHP

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1640]
Right now we have several warnings that happen when compiling IHP from scratch:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/2072185/231846724-42b9b7a3-5e74-4cae-b241-40971e1d16b2.png">

Most are not serious issues, but we should still clean this up.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by mpscholten** [comment]
Great, just assigned you :)

**Comment by amitaibu** [comment]
🥳
