### ISSUE TITLE
Creating a table leads to Unable to parse url: "/ShowTableRows?tableName=mytable"

### ISSUE THREAD

**Issue by Vic-M** [digitallyinduced/ihp#1657]
After creating a basic table in the web editor, Application/Schema.sql is updated with:  
```
CREATE TABLE mytable (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL
);
```
but the web editor redirects to http://192.168.56.108:8001/NewTable and displays:

![image](https://user-images.githubusercontent.com/32042587/235336537-7408392b-9fe5-416b-b1fd-5849e7936c2a.png)

The application displays 
```
redirectToPath: Unable to parse url: "/ShowTable?tableName=mytable"
CallStack (from HasCallStack):
  error, called at ./IHP/Prelude.hs:91:17 in ihp-1.0.1-8fPTF7hCSiVED5Uuva42Jl:IHP.Prelude
```
but keeps running. No table is created in the database.

If I delete the Application/Schema.sql modification and create the table manually, I can see it:

![image](https://user-images.githubusercontent.com/32042587/235336636-ac509c81-a612-45c3-8465-6334034bcb1f.png)

so IHP is able to communicate with the database at least.

Any ideas on how to debug?

**Comment by Vic-M** [comment]
Seems the issue is related to having IHP_BASEURL and IHP_IDE_BASEURL inside of a .env file instead of .envrc. Will have to investigate further but moving the variables to .envrc fixes the issue

**Comment by mpscholten** [comment]
Why are you setting `IHP_BASEURL`? Are you running in some kind of non standard environment (e.g. GitPod)?

**Comment by Vic-M** [comment]
IHP is running on a CentOS VM in virtualbox, so localhost is not necessarily reachable from the host machine. If I don't set `IHP_BASEURL` somewhere, the app button in the web IDE points to localhost:8000.

As a side note, I'm quite new to direnv. Where do you recommend putting env variables? IHP wipes .envrc if you re-initialize the installation from scratch and I'd like to avoid putting any project specific settings in .bashrc.

**Comment by mpscholten** [comment]
> IHP is running on a CentOS VM in virtualbox, so localhost is not necessarily reachable from the host machine. If I don't set IHP_BASEURL somewhere, the app button in the web IDE points to localhost:8000.

Makes sense 👍 

> As a side note, I'm quite new to direnv. Where would you recommend putting env variables? IHP wipes .envrc if you re-initialize the installation from scratch and I'd like to avoid putting any project specific settings in .bashrc.

You can put them into the `start` script in the app. There's actually some changes coming in the next IHP version to change how `.envrc` is used in IHP apps, as we're switching over to https://devenv.sh/

**Comment by Vic-M** [comment]
Indeed, I missed the section in `start` where you can define env vars... still not 100% ideal since `start` isn't ignored by .gitignore.

devenv looks promising, I'll test again when you release the next version. Thanks.
