### ISSUE TITLE
Prepopulate Controller from Table name

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1661]
A nice to have feature idea to help reduce repetitive tasks. I have a few tables, and each one needs a controller.

![image](https://github.com/digitallyinduced/ihp/assets/125707/bcf06bcf-edd2-4f75-ab6d-fb09ab437d2e)

So now we have to type the correct controller name for each one manually. It could be nice to have some button on the table called "Create controller" that when clicked would redirect to the codegen with the controller name populated.

![image](https://github.com/digitallyinduced/ihp/assets/125707/d3af9698-c803-4905-9849-4f7fb5a078c6)

**Comment by mpscholten** [comment]
You can right click a table and then there's an option `Generate Controller` (unless the controller already exists, then the option is not there):

<img width="389" alt="image" src="https://github.com/digitallyinduced/ihp/assets/2072185/2908dba7-f5ee-4f2e-9a3b-53e207523100">

**Comment by amitaibu** [comment]
Don't know how I missed that :neutral_face: . Thanks!

**Comment by mpscholten** [comment]
There's a lot of hidden goodies in IHP :D
