### ISSUE TITLE
Support HTML doctype in HSX

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1717]
```haskell
defaultLayout :: Html -> Html
defaultLayout inner = H.docTypeHtml ! A.lang "en" $ [hsx|
```

**Comment by CSchank** [comment]
This is one of the (if not THE) last things where we're reliant on the Blaze API. If this could be lifted up into HSX, we could look at doing more optimizations in the future and break our dependence on Blaze altogether.
