### ISSUE TITLE
Codegenerator check if name exists

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#173]
Running the codegenerator for a second time does not check for name uniqueness. 

What happens is it:
- for files where it appends, it appends more code
- for new files, it overwrites entire file

Preferably, it should warn that this name already exists. If the warning is ignored, I would expect to overwrite in both cases.

**Comment by mpscholten** [comment]
Thanks for reporting :) We're already aware of that (we have an internal Clubhouse Issue at https://app.clubhouse.io/digitallyinduced/story/1610/codegen-improve-handling-when-things-already-exists). Will be fixed soon 🚀

**Comment by themmes** [comment]
@mpscholten thanks for your fast reply! Okay, sorry I was not aware of that. Would it make sense to make such issues visible to the IHP community as well?

Great to hear that you're on this!

**Comment by mpscholten** [comment]
Yes, we're slowly migrating the Clubhouse Issues to GH Issues :) Also all new Issues are created at GH. Sadly we cannot open the Clubhouse Project itself because the CH permission system doesn't allow for this.

**Comment by themmes** [comment]
Makes sense! 👍 

Thanks again!

**Comment by themmes** [comment]
Sorry, did not mean to close.
