### ISSUE TITLE
ihp-hsx: Expose ApplyAttribute class

### ISSUE THREAD

**Issue by Profpatsch** [digitallyinduced/ihp#1731]
I’d like to add an instance of `ApplyAttribute` to one of my types, so I can use it inside the attribute position of my `hsx` parser.

But `class ApplyAttribute` is not exported from the module, sadly.

**Comment by mpscholten** [comment]
👍 make sense. I've alsways considered this class kind of like an implementation detail, so that's why it's not been exported yet.


Can you share a specific code example how you would use it / describe a bit more specific why your data structure needs it's own instance?

**Comment by mpscholten** [comment]
The `ApplyAttribute` class and instances are now exported from `IHP.HSX.Attribute`
