### ISSUE TITLE
Binary caches and release branches

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1740]
I would like to highlight the suggestion from @Eisfunke here https://github.com/digitallyinduced/ihp/pull/1705#issuecomment-1582409810 about release branches and fork it into a separate issue :) 

I think this will be vital for the future of smooth IHP deployments on Shipnix and other platforms

A repeating issue is non-matching binary caches, and that it's difficult to debug when a binary cache is actually working for the current version, and that the server suddenly takes one hour to deploy, if the server is even powerful enough to pull it off.

If we could ensure that the latest version always is covered by the binary cache, I think deployment on all platforms would be really great.

Then if building IHP takes a long time, the solution would probably often be just to run `nix flake update` and try again.

**Nice to haves:**

Could we even could support an individual binary cache for each release branch at least maybe one or two versions down?

And, maybe even better, could even the binary be declared under the hood from the IHP source? I'm guessing it probably isn't as simple as it sounds, but would be great if it was xD

**Comment by Eisfunke** [comment]
> And, maybe even better, could even the binary be declared under the hood from the IHP source? I'm guessing it probably isn't as simple as it sounds, but would be great if it was xD

I'm not sure I understand what you mean, could you elaborate? We can declare a binary cache via the flake, that is then pulled in by the users, so this could be set differently per version:

https://github.com/digitallyinduced/ihp/blob/62376a97376b86b0b3a372a769151c41c598ec51/flake-module.nix#L178

**Comment by kodeFant** [comment]
That is exactly what I meant :+1:

**Comment by kodeFant** [comment]
Am I reading [cachix pins](https://docs.cachix.org/pins) right in that it could actually preserve store paths from the latest each release branch, and by that also not having to ever change binary cache?

**Comment by mpscholten** [comment]
Yes, this would work. But right now it seems not to be what is causing our issues with all the recent missing builds

**Comment by mpscholten** [comment]
Builds should be fixed now (this time likely for real :D)! The problem was that the cachix action doesn't support nix flakes yet, so the nix flakes output wasn't pushed to cachix at all. I've fixed this by manually pushing it there.

**Comment by CSchank** [comment]
So, @mpscholten should I try to update an old project to the Nix Flakes-based IHP and see if caching works?

**Comment by mpscholten** [comment]
Yep, you can give it a try. As the `flake.lock` in `ihp-boilerplate` references commit https://github.com/digitallyinduced/ihp/commit/ed567e800409dab50d7adf57a4075cfeb7a23db4 which still has running github actions, I'd wait a couple minutes before trying it, until all the github actions have finished green 👍

**Comment by CSchank** [comment]
@mpscholten it still seems to want to build IHP for me :(
E.g. `[1/3/9 built] building ihp-v1.0.1 (buildPhase):     Probable fix: add INLINABLE pragma on ‘Text.Megaparsec.Internal.$fMonadParsecesParsecT’`
