### ISSUE TITLE
Please replace the redundant `Data controller` constraint on `parseRoute` with `Typeable controller`

### ISSUE THREAD

**Issue by lierdakil** [digitallyinduced/ihp#1743]
https://github.com/digitallyinduced/ihp/blob/4f215f0fd38573612bd8a16e0ba57f72fd9987f8/IHP/RouterSupport.hs#L871

`Data controller`, as far as I can tell anyway, is redundant, as only `Typeable controller` is required. This is an inconvenience, as I have to write bogus `Data` instances for generic routes (which I represent with existential types).

Let me know if you'd rather see this as a pull request.

**Comment by mpscholten** [comment]
Good catch, thanks for reporting 👍  Fixed via https://github.com/digitallyinduced/ihp/pull/1744

> This is an inconvenience, as I have to write bogus Data instances for generic routes (which I represent with existential types).

Can you share some code examples of what you're doing? As it seems unusual I'm interested in what you're doing :)

**Comment by lierdakil** [comment]
> code examples

Sure. The context is I need to render some (actually quite a few) routes into PDFs. I didn't want to have to add logic for each and every action I need this for. Thus, I have this type:

```haskell
data PdfController where
  PdfAction :: (Typeable c, Eq c, Show c, CanRoute c, HasPath c) => c -> PdfController
```

with corresponding instances:

```haskell
instance Eq PdfController where
  (PdfAction a) == (PdfAction b) = Just a == cast b

deriving stock instance Show PdfController

instance HasPath PdfController where
  pathTo (PdfAction x) = "/Pdf" <> pathTo x

instance All Controller Pdfables => CanRoute PdfController where
  parseRoute' = string "/Pdf" *> choice
    ( tyApMany @Pdfables @ControllerC $
      \(Proxy @_ @x) -> PdfAction <$> parseRoute' @x
    )
```

where `Pdfables` is a type-level list of controllers I need to produce PDFs for, and `tyApMany` and `All` are type-level helpers for working with this list (I can post these, too, if you're interested, but they're somewhat trivial and the code isn't pretty). `ControllerC` is just a synonym type class for `Data a, Controller a, CanRoute a` (here `Data` should've been `Typeable`, but isn't due to this issue)

At the moment, I also require this (unused, bogus) instance:

```haskell
instance Data PdfController where
  gunfold _ _ = error "PdfController.gunfold"
  toConstr = error "PdfController.toConstr"
  dataTypeOf = error "PdfController.dataTypeOf"
```

I also do this in `FrontController`:

```haskell
type Controllers 
  = ... -- controllers that don't need to be "pdfable" go here
  : PdfController
  : Pdfables

instance FrontController WebApplication where
    controllers =
        [ ... -- any non-parseRoute routes go here, atm it's only startPage
        ] <> tyApMany @Controllers @ControllerC (\(Proxy @_ @x) -> parseRoute @x)
```

This all looks a tad overengineered, probably. The main goal was to make PDF generation as plug-and-play as possible, and it is: I just stick the controller I want to add PDFs for into the appropriate list, and I'm done.
