### ISSUE TITLE
Still having issues when upgrading IHP 1.0.1 project to Nix-Flakes

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1745]
It seems like the IHP Nix Flake is fetching ghc 8.10.7? This happens after following the `UPGRADE.md` to upgrade a project (but using the newest `flake.nix` and such from the boilerplate repo, since `UPGRADE.md` seems to be outdated at the moment).

`[0/20 built, 1/42/313 copied (1499.3/3011.0 MiB), 171.6/274.5 MiB DL] fetching ghc-8.10.7 from https://cache.nixos.org`

If indeed it is, why is it fetching an old version? Perhaps this can be removed to help with reducing the image size for GitPod?

Also having issues with IHP building from source (see below).

**Comment by CSchank** [comment]
This doesn't happen when I use `ihp-new` to start a new project, only when I upgrade an old project. Everything downloads in quite little time when I start a new project! And nothing tries to build from source. So that's good, but still can't make this work with upgraded projects.

**Comment by CSchank** [comment]
My comment from #1740: 

It still seems to want to build IHP for me :( (Not this isn't in GitHub Actions, this is just on my macOS computer)

`E.g. it's showing [1/3/9 built] building ihp-v1.0.1 (buildPhase):     Probable fix: add INLINABLE pragma on ‘Text.Megaparsec.Internal.$fMonadParsecesParsecT’`

`flake.nix`, `default.nix`, `flack.lock`, etc are the same as ihp-boilerplate

Edit: Let's move this discussion to https://github.com/digitallyinduced/ihp/issues/1745 as it seems to only happen to me when I'm upgrading an old project to use Flakes.

**Comment by mpscholten** [comment]
I'll take a look at the code (assuming it's `ihp-flakes-second-try`)

**Comment by mpscholten** [comment]
> [0/20 built, 1/42/313 copied (1499.3/3011.0 MiB), 171.6/274.5 MiB DL] fetching ghc-8.10.7 from https://cache.nixos.org

The GHC 8.10.7 seems to come from `elmPackages.elm` (I've commented that one out and then it didn't download GHC 8.10.7 anymore)

**Comment by mpscholten** [comment]
Added the elm package to the IHP build process, so it should be in cachix soon https://github.com/digitallyinduced/ihp/blob/master/.github/patch-flakes.php

**Comment by CSchank** [comment]
> I'll take a look at the code (assuming it's `ihp-flakes-second-try`)

Yes, thank you! Let me know what happens for you.

> > [0/20 built, 1/42/313 copied (1499.3/3011.0 MiB), 171.6/274.5 MiB DL] fetching ghc-8.10.7 from https://cache.nixos.org
> 
> The GHC 8.10.7 seems to come from `elmPackages.elm` (I've commented that one out and then it didn't download GHC 8.10.7 anymore)

And ohhh okay, but we do need Elm in this project. Maybe I can find another way to install it.

**Comment by mpscholten** [comment]
>   noticed you added unordered-containers and Minimorph too. Those didn't seem to be huge deals, but this will be nice as well.

It was building these libs from scratch as well, that's why I added them. There should be no building for dependencies at all IMO

> The big deal was IHP wanting to build from source

That worked for me without any building from source

**Comment by CSchank** [comment]
Okay, I'll try it again, thank you!

**Comment by CSchank** [comment]
Is there an easy way for IHP users to set up Cachix to cache dependencies themselves so you don't have to add them to IHP every time a new one is used?

**Comment by mpscholten** [comment]
Not really at the moment. Especially since we often switch nixpkgs revisions between IHP versions. So better to have everything in the IHP CI directly 👍 

If we pick nixpkgs revisions in a smarter way, we might pick a good nixpkgs revision that has many haskell packages in the native cache.nixos.org

**Comment by CSchank** [comment]
@mpscholten After your help fixing things, IHP v1.1 seems to work for me now on macOS and Codespaces!! 🙌 Thanks so much for your help 🤝 

Unless you can think of a reason not to, I think we can close this issue.

**Comment by mpscholten** [comment]
Thanks for reporting back :) Then let's close this
