### ISSUE TITLE
Upgrade Contribution docs

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1747]
We have outdated docs on developing IHP core

- [ ] Commenting out flags https://github.com/digitallyinduced/ihp/blob/142c32c8351cc6164704f2acbb504575c55f1949/CONTRIBUTING.md#L33-L38
Do we need to delete all of it, or is there an equivalent in the `flake.nix `?
- [ ] How do we [run tests](https://github.com/digitallyinduced/ihp/blob/142c32c8351cc6164704f2acbb504575c55f1949/CONTRIBUTING.md#running-tests) now? `nix develop --impure --command tests` takes longer time to build than we had with ghci's `:r`

**Comment by mpscholten** [comment]
> Do we need to delete all of it, or is there an equivalent in the flake.nix ?

This should still work as previously as the `ihp.nix` file is still used by the `flake.nix`

> How do we run tests now?

This should also work as previously, e.g. 
```
ghci
:l Test/Main.hs
main
```

**Comment by amitaibu** [comment]
> This should also work as previously, e.g.
> ` ghci`

When I execute `ghci` on the root directory of my project, it works. But inside the IHP directory (e.g. `my-project/IHP` I get an error:

<img width="472" alt="image" src="https://github.com/digitallyinduced/ihp/assets/125707/2665eae3-3b66-43df-8234-fda709da3285">

**Comment by mpscholten** [comment]
Can you run `direnv allow` in the `IHP` directory?

**Comment by amitaibu** [comment]
That fixed it. I'll add to the guide.

**Comment by mpscholten** [comment]
Is there anything still to do here?
