### ISSUE TITLE
Compile `migrate` along with `RunDevServer`?

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1760]
Is there a way of compiling the `migrate` script, for example through `nix build` for use inside a NixOS configuration? 

I have tried a bit to reverse-engineer it to work on a test server, but it seems a bit sealed inside of the dev environment, so workarounds I try feel a bit too hacky for it to make sense.

Would for example be great to have it available through `${ihpApp}/bin/migrate` through nix to avoid the need of tapping into the development shell just for running the migrate script on a production server

**Comment by mpscholten** [comment]
It should work with `${ihp}/bin/migrate` actually

**Comment by kodeFant** [comment]
Took it to the test now! Seems like it's not found.

Reproducable step: Made an executable in `configuration.nix` trying both to hook on to the `ihp` library and the `ihpApp` itself coming from the flake.nix.

```nix
  environment.systemPackages = with pkgs; [
    (pkgs.writeShellScriptBin "ihp-migrate" ''
      ${ihp}/bin/migrate
    '')
    (pkgs.writeShellScriptBin "ihp-app-migrate" ''
      ${ihpApp}/bin/migrate
    '')
  ];

```

Here's the result trying to run them:

```sh
[ship@test-server-one:~]$ ihp-app-migrate
/run/current-system/sw/bin/ihp-app-migrate: line 2: /nix/store/m8f52k0i4pqjnkv2xk148fs1kxw07xl8-app/bin/migrate: No such file or directory

[ship@test-server-one:~]$ ihp-migrate
/run/current-system/sw/bin/ihp-migrate: line 2: /nix/store/d46kna0fszi06zhagmmfzg35hw3fg90c-source/bin/migrate: No such file or directory
```

**Comment by Eisfunke** [comment]
I'm a little confused as to why the migrate script package from #1762 works for you while `${ihp}/bin/migrate` doesn't, because the migrate script over there literally just calls `${ghcCompiler.ihp}/bin/migrate`.

Where exactly did you take the `ihp` variable from in your test with `${ihp}/bin/migrate`?

**Comment by kodeFant** [comment]
It comes from the `ihp` of specialArgs that is passed into the `configuration.nix`

```nix
            flake.nixosConfigurations."test-server-one" = nixpkgs.lib.nixosSystem {
                system = "x86_64-linux";
                specialArgs = inputs // {
                    environment = "production";
                    ihp = ihp;
                    migrate = self.packages.x86_64-linux.migrate;
                    ihpApp = self.packages.x86_64-linux.default;
                };
                modules = [
                    ./nixos/configuration.nix
                ];
            };
```
