### ISSUE TITLE
Not possible to run `make` command outside of `direnv`

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#1784]
When I have custom build steps in a `Makefile`, it seems like it's not longer possible to run the `make` commands outside of a direnv environment, for example in a CI environment.

For example like this:

```sh
nix-shell --run 'make static/bundle.js'
```

or like this with the new nix flake API:

```sh
nix develop --impure -c 'make static/bundle.js'
```

This is likely a problem for CI steps where you rely on the makefile commands.

A good enough workaround for me personally could be to have a bin folder in the IHP project an run custom bash scripts,  but this makes it not possible to access the js files that are already bundled in `lib/IHP` depending on the `Makefile.dist`

Not directly related to this issue, but tapping in to the development shell to build stuff in a CLI might not be the optimal approach considering build speed, so maybe flakes offers an opportunity to think about new ways for custom build steps?

**Comment by kodeFant** [comment]
After some research, I found a workaround that works great for me.

Adding a `devShell` script so I can just run `nix develop .#bundle-assets` and it talks nicely to the `Makefile` by setting the `IHP` environment variable. It also has the advantage of not depending on building the app itself :+1: 

```nix
{
  inputs = {
    ihp.url = "github:digitallyinduced/ihp/v1.1";
    nixpkgs.follows = "ihp/nixpkgs";
    flake-parts.follows = "ihp/flake-parts";
    devenv.follows = "ihp/devenv";
    systems.follows = "ihp/systems";
  };

  outputs = inputs@{ ihp, flake-parts, systems, ... }:
    flake-parts.lib.mkFlake { inherit inputs; } {

      systems = import systems;
      imports = [ ihp.flakeModules.default ];

      perSystem = { pkgs, ... }: {
        ihp = {
          enable = true;
          projectPath = ./.;
          packages = with pkgs; [
            # Native dependencies, e.g. imagemagick
            gptcommit
          ];
          haskellPackages = p: with p; [
            # Haskell dependencies go here
            p.ihp
            cabal-install
            base
            wai
            text
            hlint
          ];
        };
        devShells.bundle-assets = pkgs.mkShell {
          buildInputs = [ pkgs.lightningcss pkgs.nodePackages.uglify-js ];
          env = {
            IHP = "${ihp}/lib/IHP";
          };
          shellHook = ''
            echo "Bundling web assets..."
            make static/vendor/bundle.js
            make static/vendor/bundle.css
            echo "Done bundling!"
            exit
          '';
        };
      };
    };
}

```

**Comment by Eisfunke** [comment]
\> When I have custom build steps in a Makefile, it seems like it's not longer possible to run the make commands outside of a direnv environment, for example in a CI environment.

That shouldn't happen. The direnv .envrc should be doing pretty much exactly the same thing as `nix develop --impure` (that's what the `use flake .` command in .envrc should do). What exactly is the problem for you with `nix develop`?

> I looked into "packages" and "apps" as well, but they didn't really support this usecase in a good way, so looks like devShell scripts are the way to go for me

Mhm, did you try putting what you put in `shellHook` into a script inside an app or inside the buildPhase of an package derivation with `export IHP = ${ihp}/lib/IHP` before it to set the IHP env var similarly to what the `env` option does?

**Comment by kodeFant** [comment]
> That shouldn't happen. The direnv .envrc should be doing pretty much exactly the same thing as nix develop --impure (that's what the use flake . command in .envrc should do). What exactly is the problem for you with nix develop?


Here's an example of what happens. This should normally work for any IHP project, and it works within the context of direnv:

```sh
❯ nix develop --impure -c 'make static/prod.css'
/tmp/nix-shell.EW1ehq: line 117: /home/lillo/kode/newproject/make static/prod.css: No such file or directory
```

> Mhm, did you try putting what you put in shellHook into a script inside an app or inside the buildPhase of an package derivation with export IHP = ${ihp}/lib/IHP before it to set the IHP env var similarly to what the env option does?

Apps basically just want to be links to a binary it seems. So it would work if I had a separate bash file I guess, but then I think it's too much of a hassle to manage flake.nix, Makefile AND another binary to get the stuff I want done.

A package is also a bit of a hassle because it's based on creating a symlink result folder from the nix store, and then I would have to move the content into the static folder.

The only thing I don't like about the devShell methdod is that it's named `devShell` and not script really

**Comment by mpscholten** [comment]
try this:

```
nix develop --impure -c bash -c 'make static/prod.css'
```

**Comment by kodeFant** [comment]
Thanks, that works!
