### ISSUE TITLE
disable haddock in case packages build from scratch

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1785]
I've noticed when packages build from source (because, e.g. they're not in the build pipeline to be cached by Cachix), Haddock is a HUGE time and memory hog. Can we maybe disable it to help with this? Maybe https://github.com/input-output-hk/haskell.nix/issues/273 is relevant.

**Comment by mpscholten** [comment]
We've discussed this yesterday and it seems the best solution here is to fix the binary cache. So closing this for now (feel free to reopen if you think otherwise 👍 )
