### ISSUE TITLE
Memory limits?

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1788]
Hi, I'm wondering about heap memory limits for IHP servers. I've been told the conventional wisdom is to never run a Haskell program without a heap limit - what are the default options?

We've been having an issue where our optimized prod IHP server quickly uses 41%+ of our server's RAM (8gb) and then sometimes it crashes if there isn't enough left (e.g. when we start compiling the server, or just randomly sometimes!). What are the default settings for IHP apps in terms of heap usage? Can we limit this to avoid this happening? It clearly doesn't NEED that much, since when we first launch the server it only uses about 3% and only expands to 40%+ as the site is used more (and then it stays high). Clearly it's just garbage that's not being collected. Where can we limit heap size? Is there a config file for this?

**Comment by mpscholten** [comment]
Check out https://ihp.digitallyinduced.com/Guide/deployment.html#ghcrts By adjusting the RTS flags you can lower the amount the IHP app allocates, e.g.:

```
export GHCRTS="-A16M -N"
```

**Comment by CSchank** [comment]
Thank you, I missed that!

**Comment by CSchank** [comment]
This has reduced our memory usage by 10x! From about 44% to 4.5% %MEM in `top`. Thanks!
