### ISSUE TITLE
IHP v1.1.0 `dontCheckPackages` no longer working as intended?

### ISSUE THREAD

**Issue by larrytheliquid** [digitallyinduced/ihp#1798]
For example, say I add `servant-js` to `haskellPackages` in `flake.nix`.
On IHP v1.1.0, when running `nix-shell` this fails with:
```
> Using Parsec parser
> Configuring servant-foreign-0.15.4...
> CallStack (from HasCallStack):
>   withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:370:14 in Cabal-3.8.1.0:Distribution.Simple.Utils
> Error: Setup: Encountered missing or private dependencies:
> hspec >=2.6.0 && <2.10
```

Note that `hspec` is only a test dependency.
If I add `dontCheckPackages = [ "servant-foreign" ];`, then the same error results.

However, if I use `cabal2nix --no-check cabal://servant-foreign-0.15.4` as a custom `haskell-packages/servant-foreign.nix`, which sets `doCheck = false;`, then `nix-shell` succeeds.

**Comment by mpscholten** [comment]
Can you try to jailbreak the package by adding `doJailbreakPackages = [ "servant-foreign" ];`?

**Comment by larrytheliquid** [comment]
Yep, same result unfortunately.

**Comment by mpscholten** [comment]
It seems like we've fixed this on master already. Can you upgrade to IHP master and give the `doJailbreakPackages = [ "servant-foreign" ];` or `dontCheckPackages = [ "servant-foreign" ];` a try again?

For that change the `flake.nix` to use `ihp.url = "github:digitallyinduced/ihp";` at the top and then run `nix flake update`. 

The commit that has fixed this is likely https://github.com/digitallyinduced/ihp/commit/6dff6c5be701aaabfae5db319a0aff260f4b47b9

**Comment by mpscholten** [comment]
This can be done using a `rev` query parameter:

```
ihp.url = "github:digitallyinduced/ihp?rev=0be186bfa416a8a86620f38f25df94565d419039";
```
