### ISSUE TITLE
Hackage releases for 1.1.0?

### ISSUE THREAD

**Issue by Profpatsch** [digitallyinduced/ihp#1806]
1.1.0 fixed a lot of IHP regarding GHC 9.4 (e.g. `ihp-hsx`), but hasn’t been pushed to hackage yet. This makes it hard for nixpkgs to vendor these outside of the official distribution.

GHC 9.4 is the current stackage LTS version, so compatibility with it on hackage is very useful.

Personally I use `ihp-hsx` as a standalone library, and I had to manually override it from the 1.1.0 github release because it wasn’t on hackage yet.

**Comment by mpscholten** [comment]
Fixed via https://hackage.haskell.org/package/ihp-hsx-1.1.0
