### ISSUE TITLE
Remaining mentions of `default.nix` in the guide

### ISSUE THREAD

**Issue by sir4ur0n** [digitallyinduced/ihp#1808]
While reading the guide, in particular ["Your first project"](https://ihp.digitallyinduced.com/Guide/your-first-project.html), I see that it still mentions `default.nix`, while in reality, Flakes are used now.
The syntax of the Nix file mentioned in "Adding a Markdown Library", in particular, is quite different from the syntax of `flake.nix`.

**Comment by amitaibu** [comment]
@sir4ur0n may I encourage you to create a PR to fix it? 😄
