### ISSUE TITLE
Re-add debounce to fsnotify

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1809]
The latest version of fsnotify has removed debouncing from the library, so we likely need to implement this ourselves.

Related to https://github.com/digitallyinduced/ihp/pull/1771

**Comment by amitaibu** [comment]
I suspect this is also causing a longer time waiting for the server to start, as it's re-compiling the same code over and over again - like after `git pull`

**Comment by mpscholten** [comment]
Yes 👍

**Comment by amitaibu** [comment]
I think this library has implemented the debounce that was removed, and it built on top of fsnotify

https://hackage.haskell.org/package/steeloverseer-2.1.0.1/docs/System-FSNotify-Streaming.html
