### ISSUE TITLE
Inconsistent behaviour for selectField when using enum vs references

### ISSUE THREAD

**Issue by mariano-dagostino** [digitallyinduced/ihp#1820]
:wave: I'm pretty new to IHP, forgive me if I'm not correct enough describing this problem.

I've seen that using `selectField` in combination with enums leads to inconsistent rendering of `<select>` inputs.

Below there is an example of 2 fields, one populated with enums. and the other one with references from a table. This code was generated using some boilerplate code generated by the IHP IDE. And following the [documentation](https://ihp.digitallyinduced.com/Guide/form.html#select-inputs-with-custom-enums).

https://github.com/digitallyinduced/ihp/assets/5313631/36efb6f8-c904-4d5b-9570-2234714eb8ce

As you can observe. When using enums. The option `Please select` is disabled. But when populating the same field with the ids of an external table, it works.

This is the generated HTML for the form:

![Screenshot_2023-09-13_23-23-06](https://github.com/digitallyinduced/ihp/assets/5313631/7eb00bd1-67dd-4248-9347-fd7746b098d9)

Both columns for the Music Album table are set to `NOT Nullable` so attempting to save the form as is will trigger a SQL error because `00000000-0000-0000-0000-000000000000` is not a valid value for the `genre_id`. The enums field does not allow selecting that option, which seems more robust, but at the same time, does not allow you to let users choose, it always select the first option. Which can lead other problems from a UX point of view.

![Screenshot_2023-09-13_23-33-59](https://github.com/digitallyinduced/ihp/assets/5313631/7d2a6753-a768-4e5f-8170-e9ed2f6d1da6)

I don't have the answer to how to fix this. In my opinion the correct behavior should be the presented by the second dropdown. With some extra validation.

**Comment by mpscholten** [comment]
Thanks for reporting this 👍 

The select field is always displaying the value it gets from the music album passed to the `formFor`. The issue is introduced basically by the `newRecord @MusicAlbum`. The `newRecord @MusicAlbum` call in the controller creates an empty record setting all fields to a default empty value. The default empty value for UUIDs is the `00000000-0000-0000-0000-000000000000` and the default empty value for enums is the first enum value.

> The enums field does not allow selecting that option, which seems more robust, but at the same time, does not allow you to let users choose,

👍  this would atleast make it consistent

> Both columns for the Music Album table are set to NOT Nullable so attempting to save the form as is will trigger a SQL error because 00000000-0000-0000-0000-000000000000 is not a valid value for the genre_i

This issue has come up in the past and the solution we've found is to use the `nonEmpty` validation on the ID:

```
|> fill @'["genreId"]
|> validateField #genreId nonEmpty
```

**Comment by amitaibu** [comment]
I think we can keep the field required but not have it selected by setting the `fieldValue = ""`

`{(selectField #contentType allContentTypes) {required = True, fieldValue = "" } }`

<img width="488" alt="image" src="https://github.com/digitallyinduced/ihp/assets/125707/88e564a5-4bc6-48b3-9a5f-46f8f3665fd0">

**Comment by mariano-dagostino** [comment]
> {(selectField #contentType allContentTypes) {required = True, fieldValue = "" } }

@amitaibu Thanks. I also tried this, but the problem is it overrides the default value once the form is submitted.

**Comment by amitaibu** [comment]
You can make it conditional

```haskell
renderForm :: Post -> Html
renderForm post = formFor post [hsx|
        {(textField #title)}
        {(selectField #enumTests allEnumTests) { required = True, fieldValue = value } }

        {submitButton}}
|]
    where
        allEnumTests = allEnumValues @EnumTest
        value = if isNew post
                    then ""
                    else show post.enumTests
```

**Comment by mariano-dagostino** [comment]
@amitaibu good point. I think is worth then to check this logic, in the `selectField` function. Maybe it is possible to have this out of the box. Also it would make `required` more useful.

Would this work?

```diff
diff --git a/IHP/View/Form.hs b/IHP/View/Form.hs
index 2b518f14..81585875 100644
--- a/IHP/View/Form.hs
+++ b/IHP/View/Form.hs
@@ -738,7 +738,9 @@ selectField field items = FormField
                  SelectInput (map itemToTuple items)
         , fieldName = cs fieldName
         , fieldLabel = removeIdSuffix $ fieldNameToFieldLabel (cs fieldName)
-        , fieldValue = inputValue ((getField @fieldName model :: SelectValue item))
+        , fieldValue = if isNew model
+            then ""
+            else inputValue ((getField @fieldName model :: SelectValue item))
         , fieldInputId = cs (lcfirst (getModelName @model) <> "_" <> cs fieldName)
         , validatorResult = getValidationViolation field model
         , fieldClass = ""
```

```

**Comment by amitaibu** [comment]
Yeah, I think it's a good idea.

**Comment by amitaibu** [comment]
I've created https://github.com/digitallyinduced/ihp/pull/1821
