### ISSUE TITLE
"Could not deduce" Error When Sorting Many-To-One Collection Queries

### ISSUE THREAD

**Issue by billksun** [digitallyinduced/ihp#1822]
I wanted to sort the results of a many-to-one relationship query. However, following the example for [one-to-many relationships](https://ihp.digitallyinduced.com/Guide/relationships.html#order-with-multiple-records) and modifying it for many-to-one, results in a "Could not deduce" error.

Here's an example code:
```Haskell
query @Comment |> fetch
  >>= pure . map (modify #postId (orderByAsc #createdAt))
  >>= collectionFetchRelated #postId
```

This results in this error:
```
Could not deduce (HasQueryBuilder Id' joinRegister0)
arising from a use of 'orderByAsc' from the context: (?context :: ControllerContext, ?modelContext :: ModelContext, ?theAction :: CommentsController)
bound by the type signature for ...

**Comment by mpscholten** [comment]
The code you've shared is basically saying "fetch all comments, with all their related posts ordered by created at". The problem is that each comment only belongs to a single post, so you cannot order the related posts by created at.

**Comment by billksun** [comment]
Ah, that makes much more sense than "Could not deduce...".

But how would I sort the results by a relation's field in a many-to-one relationship?

**Comment by mpscholten** [comment]
This query cannot be done with the IHP query builder directly. You could either write your own sql query using the `sqlQuery` function or reorder the results manually using a haskell sort function

**Comment by billksun** [comment]
Ah, thanks for confirming my suspicions. I think I will use a sortable JavaScript-based table instead.
