### ISSUE TITLE
allow `validateField` to work on Maybe values

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1878]
https://github.com/digitallyinduced/ihp/blob/d0658832f6d51160678f3a03d0920f3621b844e2/IHP/ValidationSupport/ValidateField.hs#L62-L69

Right now `validateField` assumes we have required fields. So if we have a `Maybe Text` for the body it won't work. 
So this won't work as is:

```haskell
buildPost post = post
    |> fill @'["title", "sourceUrl"]
    |> validateField #name nonEmpty
    |> validateField #sourceUrl isUrl
```

@mpscholten we could add `validateMaybeField`, but I think `validateField` "just" working would be nicer. Do you agree?

**Comment by amitaibu** [comment]
Maybe a simpler option is to add this 

```haskell
-- | Validate a Maybe field.
validateMaybe :: (val -> ValidatorResult) -> Maybe val -> ValidatorResult
validateMaybe _ Nothing = Success
validateMaybe validator (Just value) = validator value
```

So then we can have this working:

```haskell
buildPost post = post
    |> fill @'["title", "sourceUrl"]
    |> validateField #name nonEmpty
    |> validateField #sourceUrl (validateMaybe isUrl)
```

**Comment by mpscholten** [comment]
The `validateMaybe` function looks great. Making `validateField` work automatically with Maybe fields will add a lot of complexity, so I prefer how you solved it 👍
