### ISSUE TITLE
Remove cachix install step from `ihp-new`

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#1883]
With the new flake based dev env we don't need to install cachix anymore to add the digitallyinduced binary cache. So the step here can be removed https://github.com/digitallyinduced/ihp/blob/master/ProjectGenerator/bin/ihp-new#L219

**Comment by rvarun11** [comment]
Apart from removing cachix install step, do we need: https://github.com/digitallyinduced/ihp/blob/33df9f448cd2bda19f43b7fa60b9a2407b4dff3c/ProjectGenerator/bin/ihp-new#L237

Or can this be removed as well?

**Comment by mpscholten** [comment]
Yes very likely
