### ISSUE TITLE
Series of things that leads to a GET/POST error - ideas for fixing it

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#1893]
When you submit a form and the validation fails, the usual thing you do to handle this:

```haskell
                    Left something -> do
                        ...
                        render NewView { .. }
```
which makes sense because this persists the values of the form.

The problem is that the URL is now replaced with `.../CreateSomething`. So if a user tries to refresh the page, you get:

<img width="825" alt="image" src="https://github.com/digitallyinduced/ihp/assets/12722104/ec31af4b-2020-46c4-8c65-f7301d2e8f1c">

I tried to avoid this by adding something like this at the beginning of the `Create` action:

```haskell
        when (requestMethod theRequest == "GET") $ do
            redirectTo NewDataExportAction
```
but the error still happens, since this appears hardcoded for all `Create` actions.

So some possible ways of fixing this would be:
1) Make sure IHP replaces the URL properly instead of leaving it `Create*` (though this might change how `render` works, which we might not want).
2) Make it so you automatically redirect to to the corresponding `New` page.
3) Give some sort of API allowing a fallback for requests that are `GET` when that URL should be `POST`.
4) Something else?

**Comment by amitaibu** [comment]
:wave: @CSchank 
We had that in the past. Are you using the latest version?

Here are the two I remember:

1. https://github.com/digitallyinduced/ihp/issues/1385
2. https://github.com/digitallyinduced/ihp/commit/f1ffc9557df5f7bb79f0e5c65c1551556b8b8ed0
