### ISSUE TITLE
"Enabling flakes" in the installation guide is empty

### ISSUE THREAD

**Issue by salomvary** [digitallyinduced/ihp#1897]
This:
https://ihp.digitallyinduced.com/Guide/installation.html#enabling-flakes

Looks like this for me:
<img width="821" alt="Screen Shot 2024-01-21 at 10 15 17" src="https://github.com/digitallyinduced/ihp/assets/193923/12c5ef5c-5cb0-4c89-a664-e268865b4010">

**Comment by amitaibu** [comment]
Sam here, although code seems fine

https://github.com/digitallyinduced/ihp/blob/2802a71eb3b32dc2b74a1219e618e098c6007639/Guide/installation.markdown?plain=1#L117-L127


I suspect it's related to the above collpasibles. Not sure how those are craeted.

**Comment by mpscholten** [comment]
The collapse element is created via JS here https://github.com/digitallyinduced/ihp/blob/master/Guide/spoilify.js Very likely the issue comes from that JS

**Comment by amitaibu** [comment]
@salomvary care to try and fix? :smile: 

https://github.com/digitallyinduced/ihp/blob/master/CONTRIBUTING.md#working-on-the-documentation

**Comment by liammcdermott** [comment]
I just wrote a patch for this, but only just now noticed the _Enabling flakes_ content is being inserted at the bottom of the instructions for _Windows_. :open_mouth: 

That's probably quite confusing for Windows users!

**Comment by liammcdermott** [comment]
@mpscholten  thanks for merging my PR for this!!
