### ISSUE TITLE
HIE Integration

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#190]
Would be cool to have zero-setup support for Haskell Ide Engine out of the box

**Comment by Sir4ur0n** [comment]
Does this issue imply/also include [Haskell Language Server](https://github.com/haskell/haskell-language-server)? HLS is the converging point in terms of IDE experience, I think it would be best, what do you think?

**Comment by mpscholten** [comment]
Yes :) the issues is a bit misnamed. The referenced PR is actually using HLS. We first tried HIE, but then changed the PR to work with HLS instead.

**Comment by Sir4ur0n** [comment]
Awesome, thank you @mpscholten !

**Comment by Montmorency** [comment]
Was working on integrating [hls](https://github.com/haskell/haskell-language-server) with vim for IHP projects today. I think this issue [614](https://github.com/digital-asset/ghcide/issues/614) might be a fix for the template haskell issue raised here. I tried building hls with the [`fix-more-th`](https://github.com/digital-asset/ghcide/commit/985268dec97783b44d0339bf32d0cf084b903410) branch of ghcide but kept ran in to a bit of trouble compiling. However as soon as that patch makes it into the master branch of ghcide I think that will resolve this issue with HLS/IHP. So maybe one to watch?

**Comment by mpscholten** [comment]
Thanks for pointing out. Just subscribed to that PR :) Once it's merged we can continue the integration

**Comment by mpscholten** [comment]
It looks like the fix for this just got merged via https://github.com/haskell/ghcide/pull/741 :) This means we can continue the work on this now 👍

**Comment by maralorn** [comment]
Please be aware, that https://github.com/digital-asset/ghcide/issues/614 is still open. Because there still are issues with TH sometimes. I am not aware of what issue exactly you are having, so I don‘t know if the merged fix helps you or not.

**Comment by mpscholten** [comment]
Thanks for letting us know 👍  I think our issue is mostly related to `symbols need to be exported because they occur in a TH splice.`. Will try out to build the fixed version tomorrow, maybe we're lucky and everything is working already :)
