### ISSUE TITLE
Add to docs/ core the way to encode JSON via hsx

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1900]
```
import qualified Text.Blaze.Html.Renderer.Text as Renderer
import Text.Blaze.Html (Html)
import qualified Data.Text.Lazy as TL

instance ToJSON Html where
    toJSON html = String (TL.toStrict $ Renderer.renderHtml html)
    
    
<div data-my-encoded-json={encode someJsonValue}></div>
```

**Comment by amitaibu** [comment]
I've started an example. Surprisingly it seems I didn't need to declare the `instance ToJSON Html where` to make it work

https://github.com/amitaibu/ihp-landing-page/pull/37

**Comment by mpscholten** [comment]
Likely because the `encode`returns a `Bytestring` which cannot be directly rendered into the HTML. Can you try something like `<div data-my-encoded-json={(cs (encode someJsonValue)) :: Text}></div>`?

**Comment by mpscholten** [comment]
With an instance `ApplyAttribute Aeson.Value` like:

```
-- IHP.HSX.Attribute
instance ApplyAttribute Aeson.Value where
    applyAttribute attr attr' value h = applyAttribute attr attr' value' h
        where value' = Html.textValue (encode someJsonValue)
```

we could also allow for this:

```
<div data-my-encoded-json={toJSON someJsonValue}></div>
```

This way we hide the technical implementation of the `encode` and the `cs`

**Comment by amitaibu** [comment]
The surprising part is that it's working as is:

`<div data-my-encoded-json={encode someJsonValue}></div>`

:shrug: 

So I'll just go ahead and document it
