### ISSUE TITLE
`deploy-to-nixos` deletes active sessions

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1920]
I've noticed that after every `deploy-to-nixos`, users need to re-login. Is it possible to prevent this?

**Comment by amitaibu** [comment]
Known issue and already documented - https://ihp.digitallyinduced.com/Guide/deployment.html#ihpsessionsecret

**Comment by mpscholten** [comment]
Maybe we can add this to the ihp boilerplate as well with a comment on how to generate a new ihp session secret string (we should propably add a new CLI command to IHP `generate-session-secret`)

**Comment by amitaibu** [comment]
github.com/digitallyinduced/ihp-boilerplate/pull/33
