### ISSUE TITLE
Proper support for non "id" primary keys.

### ISSUE THREAD

**Issue by MonaMayrhofer** [digitallyinduced/ihp#1924]
Currently multiple parts of the `SchemaCompiler` assume that a) the primary key is always called `id` and that b) it is not a composite key.

Some examples for this are:
https://github.com/digitallyinduced/ihp/blob/6971e39134aa10ba1a015cf5e51fd52d7e8c8995/IHP/SchemaCompiler.hs#L585-L590

https://github.com/digitallyinduced/ihp/blob/6971e39134aa10ba1a015cf5e51fd52d7e8c8995/IHP/SchemaCompiler.hs#L617-L623

And possibly others, that are found when investigating further...

Currently using a non-"id" primary key either results in non-compiling code or runtime errors when trying to update (IHP thinks that you forgot a database migration, because "the id column is missing")

After digging in a bit, implementing single-column, non-"id" primary keys seems to be a pretty quick thing, however composite PKs seem to pose a little bit more of a headache, especially for supporting the `genericFetchIds` in `Fetch.hs`, which would probably entail creating a `filterWhereIdIn` in the `FilterPrimaryKey` class in the QueryBuilder (because simply chaining two `QueryBuilder.filterWhereIn` together would yield false positives).
That one should result in generating `WHERE (id_a, id_b) = (?, ?)` predicates in the final sql query... 
That could be done by simply falling back to `sqlQuery`, however as `filterWhereId` is implemented in terms of `QueryBuilder.filterWhere...`, it would probably be better to make `QueryBuilder.filterWhereIn` be able to handle tuples, like
`filterWhereIn (#userId, #thingId) [(1, 2), (3,2)]` or introducing a cousin `QueryBuilder.filterWhereTupleIn` that can do something like that...

I will probably do something along the lines of this anyways in order to incorporate an existing database that i really don't wanna change, the question is whether supporting non-"id" PKs is a goal of ihp, and if a (possibly sizeable) pull request that does that is wanted.

If it is i'd be happy to draft up something proper and collect some more feedback in the form of a PR!

**Comment by mpscholten** [comment]
Happy to have IHP supporting non-id PKs 👍  Ideally we can support that without introducing much new complexity
