### ISSUE TITLE
IHP codegen does not enforce capitalised View names

### ISSUE THREAD

**Issue by liammcdermott** [digitallyinduced/ihp#1950]
The steps I took, as an IHP beginner, just working with the web console:

1. Created a table named `users`, using CodeGen
2. Clicked CodeGen in the console, then _Controller_
3. Entered `users` in the _Controller name_ text box (notice the console corrects `users` → `Users` so it's capitalised)
4. This all seemed to work, so I went to _CodeGen_ again, and selected _Users_ from the drop-down. I was unsure what it meant _precisely_ to create a View in this context, so in the _View name_ text box I entered `test`.
5. Clicked _Preview_ then _Generate_

The CodeGen failed to generate valid Haskell code (since type and module names cannot be lowercase). The attached screenshot shows the _Preview_ step, including the invalid code.

![image](https://github.com/digitallyinduced/ihp/assets/5082004/df3b23d1-744b-4319-a1b7-35f9054d391c)

**Comment by liammcdermott** [comment]
What I would expect to happen: IHP console should auto-capitalise the contents of _View name_, like it does when creating a Controller.

Also, I successfully reproduced this bug on `master` (love the new console gui when you run `./start`. So slick!)

**Comment by mpscholten** [comment]
Thanks, good catch 👍 

Looks like the error is here: https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/CodeGen/ViewGenerator.hs#L83C24-L83C38

The `{$nameWithSuffix}` will always produce something like `data X = {X}` which is always invalid haskell. I guess it's just a typo and should be `${nameWithSuffix}`
