### ISSUE TITLE
IHP IDE: 'DEPLOY' link leads to site with an invalid certificate

### ISSUE THREAD

**Issue by liammcdermott** [digitallyinduced/ihp#1954]
The _DEPLOY_ link in the sidebar of the IHP IDE opens https://ihpcloud.com, which has an invalid SSL certificate.

IIRC, Digitally Induced don't plan to provide cloud hosting again soon, right? In that case, we could just remove the _DEPLOY_ link until there's something meaningful to replace it.

**Comment by mpscholten** [comment]
Yes that's correct, good catch. Maybe we can link the deploy button to the deploy section in the guide? Alternatively we could also remove it

**Comment by liammcdermott** [comment]
I can see why linking to the guide is a tempting idea, but every other button in the sidebar lets the user automate the thing in the label, _CODEGEN_ generates code, _SCHEMA_ builds your db schema and runs migrations, and so on. That sets an expectation for the user that _DEPLOY_ will deploy their app.

So, when the user finds it's just a link to the documentation, it's an unpleasant surprise for  them. And - using the Principle of Least Astonishment - temporarily removing the button seems the best option.

**Comment by mpscholten** [comment]
Agree, then let’s remove it 👍
