### ISSUE TITLE
Save only the relative path of the filename in `storeFileWithOptions`

### ISSUE THREAD

**Issue by amitaibu** [digitallyinduced/ihp#1989]
Right now, on  `StaticDirStorage ` we save the filename with the full file path `https://example.com/static/image/foo.jpg`

https://github.com/digitallyinduced/ihp/blob/4526f58b29741f351b66b070f165111d83a0efc1/IHP/FileStorage/ControllerFunctions.hs#L106-L115

I think it's better to save it as `/image/foo.jpg`; it takes less space and is more flexible if the base path is changed.

**Comment by mpscholten** [comment]
Agree. I think it was done to be consistent with the S3 storage method (as that also generates a full absolute url). But I see the point in changing that, so in case it's not breaking anything let's do this 👍
