### ISSUE TITLE
Checking data sync application journalctl I am seeing a number of 

### ISSUE THREAD

**Issue by Montmorency** [digitallyinduced/ihp#2011]
Error in pg_notify handler: IHP/DataSync/ChangeNotifications.hs:(157,5)-(163,42): Non-exhaustive patterns in function parseJSON

Looks like some patterns aren't matched in the type class? Should there be a catchall?

**Comment by mpscholten** [comment]
if the app was deployed before https://github.com/digitallyinduced/ihp/commit/e31d7b8fdbb5ff88e9e7711dfb5e92848b9c860b it's likely that your database triggers are outdated. You can verify that by manually checking that the database triggers have the diff in that commit applied.

**Comment by Montmorency** [comment]
Great quite likely. Looks to be gone after redeploy which updated triggers.
