### ISSUE TITLE
`collectionFetchRelated` not working per the guide instructions

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#207]
Following the instructions in the [guide](https://ihp.digitallyinduced.com/Guide/relationships.html#multiple-records), `posts :: [Include "comments" Post] <- query @Post |> fetch >>= collectionFetchRelated #comments` fails to compile: `Couldn't match type ‘Id' "comments"’ with ‘QueryBuilder Comment’`

Is the [filter](https://ihp.digitallyinduced.com/api-docs/src/IHP.FetchRelated.html#local-6989586621680126202) on the related models incorrectly using the related model's #id instead of the foreign key field?

This was my workaround:
`posts <- mapM (fetchRelated #comments) =<< query @Post |> findManyBy #id postId`

**Comment by nkpart** [comment]
I think the problem is the `targetForeignKey` line. That requires that the parent model (second argument to collectionFetchRelated) being targeted is a `Post' (Id' "comments")`, while the result of the first fetch is `Post' (QueryBuilder Comment)`.
