### ISSUE TITLE
Snake-caps Tables with Foreign Key Constraints Break Generated Types

### ISSUE THREAD

**Issue by ruhatch** [digitallyinduced/ihp#211]
If we follow the tutorial example with a `posts` table, but replace `comments` with `user_comments`, we see two issues in `build/Generated/Types.hs`.

First, `type instance Include "userComments" (Posts' user_comments) = Posts' user_comments` instead of `Posts' [UserComment]`. This breaks `fetchRelated`.

Second, the field in `Posts'` type is called `user_comments`, rather than `userComments` as is the naming convention. This then propagates to instances in the file such as `UpdateField "user_comments"...` and also breaks `fetchRelated`.

This will happen with any second table with a name that has multiple words in snake caps and a foreign key constraint.

**Comment by mpscholten** [comment]
Good catch 👍
