### ISSUE TITLE
Implement getInput

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#213]
It seems like the `getInput` function referenced in the [guide](https://ihp.digitallyinduced.com/Guide/routing.html#autoroute-beautiful-urls) would be a helpful utility function to include in IHP.RouterSupport.

**Comment by mpscholten** [comment]
Hey, thanks for opening the issue :-) The `getInput` function in the guide is from attoparsec (see here: https://hackage.haskell.org/package/attoparsec-0.7.2/docs/Data-Attoparsec-Char8.html#v:getInput) I guess we should add the function to the RouterPrelude, so that it's available by default :)

**Comment by nghamilton** [comment]
Brilliant, thanks! Perhaps the same needs to be done for the missing `parseText` function?

**Comment by mpscholten** [comment]
Good point. I guess the function got lost during the last refactoring before open sourcing IHP :-) Just added it again in the above PR.
