### ISSUE TITLE
Using parseId results in ambiguous type errors

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#215]
When using `parseId` type errors are thrown (at least within `parseRoute'`: I haven't attempted elsewhere):
```
      i <- Just <$> parseId
```
fails to compile with:
```
    • Couldn't match type ‘GetTableName record0’ with ‘"posts"’
      Expected type: Maybe (Id Post)
        Actual type: Maybe (Id' (GetTableName record0))
      The type variable ‘record0’ is ambiguous
```
However, this compiles:
```
i <- Just . IHP.ModelSupport.Id <$> parseUUID
```

**Comment by mpscholten** [comment]
Most likely fixed via https://github.com/digitallyinduced/ihp/commit/a5c9923e52c46f9df0f08ee09b6d98b6788b7d79 :)
