### ISSUE TITLE
HSX input tag

### ISSUE THREAD

**Issue by nezbite** [digitallyinduced/ihp#223]
When using an `<input>` tag without closing (as seen on Bootstrap Documentation) HSX gives an error, searching for the wrong closing tag. 
In my case, using the navbar template from Bootstrap, the issue was fixed with closing input like so `<input type=""/>` but the error was:
```
   |
34 |     </form>
   |      ^
unexpected '/'
expecting "</div>", "</form>", "</input>", "</nav>", identifier, or text
```

**Comment by ruhatch** [comment]
This also includes other self-closing tags, such as `hr`, `br`, and `img`
