### ISSUE TITLE
Empty optional fields fail to parse

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#227]
Chrome (and possibly all other browsers?) submits empty form fields with just a field name and no content (e.g. /Users?page=). In this situation, IHP parses the field value as "", and queryOrBodyParam will return `Just ""`

As empty strings could be considered as acceptable parameters, and therefore the `queryOrBodyParam` function is probably is working as expected.

This poses a problem for the optional ParamReader's, in particular the non-stringy ones; they will likely fail when attempting to parse `""` (e.g. `ParamReader (Maybe Int)` will fail with `ParamReader Int: not enough input`).

The most appropriate solution seems to be to consider an empty string as a successful parse with a result of `Nothing` for optional all fields, but only after first attempting to read the parameter.

PR: #226

**Comment by mpscholten** [comment]
Merged ✅
