### ISSUE TITLE
dateTimeField renders obsolete HTML

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#228]
The `dateTimeField` function produces an HTML field `<input type="datetime">` and the `datetime` input type is obsolete: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime#Browser_compatibility.

**Comment by mpscholten** [comment]
Good catch :) I guess we can just switch to `datetime-local`, right? Then we'd also need to update some css selectors in the js helpers: https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/static/helpers.js#L271

**Comment by nghamilton** [comment]
I had a look at datetime-local, but it seems it is not widely supported?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#Browser_compatibility

I am thinking perhaps a text field with a specific 'date-time-input' class:
the text field's value would be set based on user locale date-time. Helper
JS functions to go to/from locale/UTC and a submit event handler to convert
the value in the field back to ISO 8601. Would that make sense?

**Comment by nghamilton** [comment]
Looking more closely at your Flatpickr, it would seem you have done a lot of the work there already, so my comment about conversion probably is less relevant.

**Comment by mpscholten** [comment]
I think this was fixed via https://github.com/digitallyinduced/ihp/pull/267, right? :)
