### ISSUE TITLE
Layout.hs has missing JS/source files

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#229]
The generated `Web/View/Layout.hs` file does not included all the required JS/CSS vendor files:

* flatpickr.js
* flatpickr.min.css
* select2.min.css and select2.js ?
* prod.js is not used (all vendor JS files are included individually)

**Comment by mpscholten** [comment]
Just for background: The `prod.js` can be created using [`make static/prod.js`](https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/Makefile.dist#L131). This will simply bundle all js files into a single bundle. The js files which are bundled have to be specified in the `Makefile` of the project (like `JS_FILES += ${IHP}/static/vendor/turbolinksMorphdom.js`).
