### ISSUE TITLE
Unique Together is interpreted as a syntax error

### ISSUE THREAD

**Issue by kigsmtua** [digitallyinduced/ihp#232]
While editing the raw SQL  on the schema designer, a table defined as follows, fails with a syntax error

```sql
CREATE TABLE user_followers (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    user_id UUID NOT NULL,
    follower_id UUID NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    UNIQUE(user_id, follower_id)
);

```
Seemingly we cannot add the UNIQUE constraints for two fields as it fails with the below error

```haskell

Application/Schema.sql:18:11:
   |
18 |     UNIQUE(user_id, follower_id)
   |           ^^^^^^^^^^^^^^^^^^
unexpected "(user_id, follower"
expecting "BIGINT", "BINARY", "BOOL", "BOOLEAN", "CHAR(", "CHARACTER VARYING(", "CHARACTER(", "DATE", "DOUBLE PRECISION", "FLOAT4", "FLOAT8", "INT", "INT4", "INT8", "INTEGER", "NUMERIC", "NUMERIC(", "REAL", "TEXT", "TIME", "TIMESTAMP", "TIMESTAMPZ", "UUID", "VARCHAR(", Custom type, identifier, or white space


```

I am not entirely sure if I am missing something.

**Comment by mpscholten** [comment]
Hey, defining a unique constraint this way is not supported at the moment. We can fix this by updating the [SchemaParser](https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/SchemaDesigner/Parser.hs) :)

**Comment by kigsmtua** [comment]
Aaah I see.. am guessing a P.R for this would be welcome ?

**Comment by mpscholten** [comment]
Yes, would be happy to merge this :)

**Comment by mpscholten** [comment]
@kigsmtua the issue should be fixed with the next IHP release (next release is coming this friday) ✅
