### ISSUE TITLE
Guide: Add section on deployment

### ISSUE THREAD

**Issue by glademiller** [digitallyinduced/ihp#240]
The guide is great but as someone evaluating a framework for the first time I would love to have a section on packaging and deployment. 

The kinds of things I would like to know quickly are:
1) How can I package this app into a Docker container
2) How can I create a package that can be easily put on to a Linux machine and started quickly
3) What about static assets should those go on a CDN etc...

I think this would do a lot to help power adoption.

**Comment by mpscholten** [comment]
Just linking the internal clubhouse task: https://app.clubhouse.io/digitallyinduced/story/1507/doku-deployment

**Comment by mpscholten** [comment]
Just adding more notes: We should have a section on how the IHP build process works in dev and production

**Comment by Laobiz** [comment]
Here is a short sketch of the deployment process:

- Install nix on your server
- Copy your project folder to your server.
- Run `nix-shell` inside of your project folder
- Run `make -B build/Generated/Types.hs` and after that `make -B build/bin/RunUnoptimizedProdServer` inside of the nix-shell
- You need to run `/build/bin/RunProdServer` with $DATABASE_URL and $PORT set, where $DATABASE_URL is your postgresql connection [url](https://jdbc.postgresql.org/documentation/head/connect.html).

**Comment by ruhatch** [comment]
> Here is a short sketch of the deployment process:
> 
>     * Install nix on your server
> 
>     * Copy your project folder to your server.
> 
>     * Run `nix-shell` inside of your project folder
> 
>     * Run `make -B build/Generated/Types.hs` and after that `make -B build/bin/RunUnoptimizedProdServer` inside of the nix-shell
> 
>     * You need to run `/build/bin/RunProdServer` with $DATABASE_URL and $PORT set, where $DATABASE_URL is your postgresql connection [url](https://jdbc.postgresql.org/documentation/head/connect.html) and $PORT the port where the server will be run.

Seems like you could get a nice `nixops` deployment template for this that wraps the database information into the binary, does all the steps you've outlined, and launches the `RunProdServer` as a `systemd` service!

**Comment by Montmorency** [comment]
Just posting a link to some [notes](http://harlambert.co.uk/ihp_notes/) on serving an IHP application with nginx. I just followed Laobiz's sketch from above. This is a pretty basic set up but might be helpful for someone looking to get up and running quickly. The only other thing I'd mention is that the default IHP postgresql database name is "app".

**Comment by mpscholten** [comment]
I've added a few more notes on deploying with https://github.com/digitallyinduced/ihp/pull/396

**Comment by radek3911** [comment]
Hi I am having a problem I have set my database URL to .envrc and even used `export DATABASE_URL=postgresql://ihp:ihp@localhost:5432/ihp`, but for some reason I cannot `make db`. It seems like it's trying to use database `app` even through I am trying to use database IHP.

**Comment by Montmorency** [comment]
Have you started the postgres server? Something like 
```
postgres -D build/db/state -k $PWD/build/db -c "listen_addresses="&
```
make db I think just generates the schema and fixtures and then connects via psql but the postgres server needs to be started manually.

**Comment by mpscholten** [comment]
Yes, `make db` expects to have a db running. It's best to have a terminal with `./start` running to do this.

In case you want to run `make db` against your staging or prod db, this will not work. You can manually run the commands that `make db` is running:

```bash
	psql "$DATABASE_URL" < build/ihp-lib/IHPSchema.sql
	psql "$DATABASE_URL" < Application/Schema.sql
	psql "$DATABASE_URL" < Application/Fixtures.sql
```

(take from https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/Makefile.dist#L105)

**Comment by radek3911** [comment]
> 
> 
> Yes, `make db` expects to have a db running. It's best to have a terminal with `./start` running to do this.
> 
> In case you want to run `make db` against your staging or prod db, this will not work. You can manually run the commands that `make db` is running:
> 
> ```shell
> 	psql "$DATABASE_URL" < build/ihp-lib/IHPSchema.sql
> 	psql "$DATABASE_URL" < Application/Schema.sql
> 	psql "$DATABASE_URL" < Application/Fixtures.sql
> ```
> 
> (take from https://github.com/digitallyinduced/ihp/blob/master/lib/IHP/Makefile.dist#L105)

This works. Thank you :)

**Comment by mpscholten** [comment]
Closing this as the documentation for this is available now at https://ihp.digitallyinduced.com/Guide/deployment.html :) In case something is still missing let me know :)
