### ISSUE TITLE
Roadmap Question: Realtime UI updates?

### ISSUE THREAD

**Issue by camstuart** [digitallyinduced/ihp#243]
Hi, 
This is a very interesting looking framework! I'm currently trying out Phoenix (Elixir) because I recently "discovered" functional programming, but I prefer strong types. So Haskell seems like a good option.

Can you please tell me if you have plans to add any kind of real-time UI update feature such as web sockets. For example Phoenix LiveView?

**Comment by mpscholten** [comment]
Hey, yes this is planed to be released in Q3 2020 :)

**Comment by camstuart** [comment]
Ok, that's great news @mpscholten then I'm very interested. I'll watch your YouTube videos and have a go over the weekend!

**Comment by mpscholten** [comment]
FYI: This is in progress now at https://github.com/digitallyinduced/ihp/pull/419 :)

**Comment by camstuart** [comment]
Awesome! I saw you are starting to get into youtube tutorial videos as well. nice!

**Comment by mpscholten** [comment]
This has been shipped with the latest released https://github.com/digitallyinduced/ihp/releases/tag/v20201002 :)

Here's a live demo: https://twitter.com/digitallyinduce/status/1312017800223956992
And here's the documentation: https://ihp.digitallyinduced.com/Guide/auto-refresh.html
