### ISSUE TITLE
Code Duplication in View Generators

### ISSUE THREAD

**Issue by ruhatch** [digitallyinduced/ihp#251]
Right now we have the same view generation code duplicated in `IHP.IDE.CodeGen.ViewGenerator` and `IHP.IDE.CodeGen.ControllerGenerator`. This led to a change in the views generated by the `ViewGenerator` not propagating to the `ControllerGenerator`. It would be nice to reduce this duplication and probably have the `ControllerGenerator` call the `ViewGenerator` to generate its views.

**Comment by Laobiz** [comment]
We had the same thought and fixed it in here https://github.com/digitallyinduced/ihp/pull/236 :)
