### ISSUE TITLE
Makefile:7: /../lib/IHP/Makefile.dist: No such file or directory

### ISSUE THREAD

**Issue by mdgart** [digitallyinduced/ihp#256]
I'm trying to run psql from like the documentation says: "When inside the project directory you can also use make psql to open a postgres REPL connected to the development database. " but I get this error:

make psql 
usage: dirname path
Makefile:7: /../lib/IHP/Makefile.dist: No such file or directory
make: *** No rule to make target `/../lib/IHP/Makefile.dist'.  Stop.

Am I doing something wrong?

**Comment by mpscholten** [comment]
Hey, thanks for reporting! :)

Could you try to run the following:
```
nix-shell --run 'make build/ihp-lib'
```

**Comment by mdgart** [comment]
If I run this when the app is running I get:

`error: file '/Users/mdgiorgi/Documents/Exercises/haskell/blog/build/db/.s.PGSQL.5432' has an unsupported type`

So I run it when the app stopped and I got:

```
mkdir -p build
rm -f build/ihp-lib
ln -s /nix/store/vj0k79cygj4sr72mf46gd1m91608bms3-ghc-8.8.3-with-packages/bin/../lib/IHP build/ihp-lib
```

Then I tried again with make psql and I got the same error:

```
make psql                                           
usage: dirname path
Makefile:7: /../lib/IHP/Makefile.dist: No such file or directory
make: *** No rule to make target `/../lib/IHP/Makefile.dist'.  Stop.
```

**Comment by mpscholten** [comment]
Can you run:

```bash
which RunDevServer
```
?

I guess `direnv` might not be set up as expected. Can you run `direnv status` and paste the output?

**Comment by mdgart** [comment]
`which RunDevServer`
RunDevServer not found

`direnv status`
```
direnv exec path /usr/local/bin/direnv
DIRENV_CONFIG /Users/mdgiorgi/.config/direnv
bash_path /bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
No .envrc loaded
Found RC path /Users/mdgiorgi/Documents/Exercises/haskell/blog/.envrc
Found watch: ".envrc" - 2020-07-23T08:24:47-06:00
Found watch: "../../../../.local/share/direnv/allow/d00b974b602be2e077a28ddf254d76bc04f6b878e4fa7917fb33894ff5adbb8f" - 2020-07-23T08:24:47-06:00
Found RC allowed true
Found RC allowPath /Users/mdgiorgi/.local/share/direnv/allow/d00b974b602be2e077a28ddf254d76bc04f6b878e4fa7917fb33894ff5adbb8f
```

**Comment by mpscholten** [comment]
`No .envrc loaded` <- Something is off here.

Did you add

```bash
eval "$(direnv hook zsh)"
```

to your `~/.zprofile` when installing direnv?

**Comment by mdgart** [comment]
that was it, works now, thanks!! Is this in the documentation? because if it is I missed it...

**Comment by mpscholten** [comment]
We've recently removed this step from the documentation as [this is now part of the setup process when running `ihp-new`](https://github.com/digitallyinduced/ihp/blob/master/ProjectGenerator/bin/ihp-new#L32).

Do you remember whether this step succeeded while running `ihp-new`? Maybe we somehow need to improve the `ihp-new` command to automatically do this or atleast to check that `direnv` is working as expected.

**Comment by mdgart** [comment]
I don't remember any error or warning when I run `ihp-new`, I think checking that direnv is working would improve this step for sure.

**Comment by victorcwai** [comment]
I got this message when I run `ihp-new`:
```
Direnv needs to be hooked into your shell. Please follow the steps below:
Bash: Add \e[4meval "$(direnv hook bash)"\e[0m to ~/.bashrc
ZSH: Add \e[4meval "$(direnv hook zsh)"\e[0m to ~/.zshrc
```
Solved the same issue by adding 
`eval "$(direnv hook bash)"` 
to my `~/.bashrc`.

**Comment by mpscholten** [comment]
The error `error: file '/Users/mdgiorgi/Documents/Exercises/haskell/blog/build/db/.s.PGSQL.5432' has an unsupported type` has been fixed, the situation around the `build/ihp-lib` symlink has also improved recently (the symlink is now checked whenever the dev server is started). Closing this now as the situation around this error has improved so that it won't happen anymore in the latest IHP version.
