### ISSUE TITLE
ihp-new runs out of memory on small hosts (eg EC2 micro instances)

### ISSUE THREAD

**Issue by chrislf** [digitallyinduced/ihp#265]
`ihp-new` calls `nix-env -i $package`, which does a large evaluation of nix expressions, which can run out of memory on resource-constrained hosts.

Using `nix-env -iA nixpkgs.$package` is faster and uses much less memory.

**Comment by chrislf** [comment]
I have added a PR which should address this.

I only changed the invocations in ihp-new; there are instances in the github actions config which might benefit as well. I can add these if that is considered a good idea.

**Comment by mpscholten** [comment]
> I only changed the invocations in ihp-new; there are instances in the github actions config which might benefit as well. I can add these if that is considered a good idea.

Would be happy to merge this 👍

**Comment by mpscholten** [comment]
This is fixed via https://github.com/digitallyinduced/ihp/pull/266
