### ISSUE TITLE
Check if Unix-domain socket path exceeds li

### ISSUE THREAD

**Issue by andreasrueb** [digitallyinduced/ihp#272]
IHP should check on startup if the path is to long to use as a socket and suggest solutions to the user.

`psql: Unix-domain socket path "/long-path-to-app/build/db/.s.PGSQL.5432" is too long (maximum 103 bytes) psql: Unix-domain socket path "/long-path-to-app/build/db/.s.PGSQL.5432" is too long (maximum 103 bytes)`

**Comment by mpscholten** [comment]
This is handled by devenv.sh now so can be closed 👍
