### ISSUE TITLE
Adding a second foreign key to the same table breaks type generation

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#275]
• Conflicting definitions for ‘tariffdetails’
      Bound at: build/Generated/Types.hs:124:44-56
                build/Generated/Types.hs:124:58-70
    • In an equation for ‘updateField’
    |
124 |     updateField newValue (Tariffversion id tariffdetails tariffdetails meta) = Tariffversion id newValue newValue (meta { touchedFields = "tariffdetails" : touchedFields meta })
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

build/Generated/Types.hs:127:44: error:
    • Conflicting definitions for ‘tariffdetails’
      Bound at: build/Generated/Types.hs:127:44-56
                build/Generated/Types.hs:127:58-70
    • In an equation for ‘updateField’
    |
127 |     updateField newValue (Tariffversion id tariffdetails tariffdetails meta) = Tariffversion id newValue newValue (meta { touchedFields = "tariffdetails" : touchedFields meta })
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

build/Generated/Types.hs:130:44: error:
Failed, two modules loaded.
    • Conflicting definitions for ‘tariffdetails’
      Bound at: build/Generated/Types.hs:130:44-56
                build/Generated/Types.hs:130:58-70
    • In an equation for ‘updateField’
    |
130 |     updateField newValue (Tariffversion id tariffdetails tariffdetails meta) = Tariffversion id tariffdetails tariffdetails newValue
    |                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

[Schema.zip](https://github.com/digitallyinduced/ihp/files/4992679/Schema.zip)

**Comment by mpscholten** [comment]
Thanks for reporting! Will look into this asap

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/commit/520e87d15ea45b6121d0afbbae7cd08850fdc196 🎉

**Comment by Kaeptenblaubaer** [comment]
Thanks, sorry for not reading correctly :-)Am 06.09.2020 12:25 schrieb Marc Scholten <notifications@github.com>:

Fixed via 520e87d 🎉
