### ISSUE TITLE
Composite primary keys break generation

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#291]

**Comment by ruhatch** [comment]
So it seems there are multiple parts to this one:
1. Add support to Schema UI for composite primary keys, including SQL generation
2. Build off #312 to add support for composite keys in the IHP code
3. Make sure type generators create the correct `PrimaryKey` instances and those work generally

I'm gonna give this a go!

**Comment by mpscholten** [comment]
Great 👍

**Comment by ruhatch** [comment]
@mpscholten a quick design question:

With composite keys it doesn't really make sense to have an `id` column directly in the schema.

My thought is that for composite keys we can instead create a `HasField "id" Model (Id' "models))` instance that returns a tuple of the primary key columns. This preserves all code which needs `HasField "id"` constraints.

We would then additionally have to disallow creating an `id` column when using composite pks in the IHP UI, and throw an error if the user puts an `id` column in the `CREATE TABLE` statement manually. Does this seem like a reasonable approach? Any adjustments you'd want to make?

**Comment by ruhatch** [comment]
@mpscholten I noticed that the `CanUpdate` instances don't allow updates of the `id` field. Would you expect the same from a `CanUpdate` with a composite key, i.e. you wouldn't be able to change any of the primary key fields?

**Comment by ruhatch** [comment]
@mpscholten so the `FromRow` instance looks like this (I've formatted for readability):
```
instance FromRow Post where 
  fromRow = do
    id <- field
    Post 
      <$> pure id 
      <*> field 
      <*> field 
      <*> field 
      <*> pure (QueryBuilder.filterWhere (Data.Proxy.Proxy @"postId", id) (QueryBuilder.query @Comment)) 
      <*> pure def
```
This seems to rely on `id` always being the first field in the data type, but I don't see that being enforced anywhere else. Am I missing something?

**Comment by Kaeptenblaubaer** [comment]
That's reasonable, I guessAm 10.08.2020 20:52 schrieb Ru Horlick <notifications@github.com>:
@mpscholten I noticed that the CanUpdate instances don't allow updates of the id field. Would you expect the same from a CanUpdate with a composite key, i.e. you wouldn't be able to change any of the primary key fields?

**Comment by mpscholten** [comment]
> My thought is that for composite keys we can instead create a HasField "id" Model (Id' "models)) instance that returns a tuple of the primary key columns. This preserves all code which needs HasField "id" constraints.

I think this will work, but feels a bit hacky :) Let's try it out and see. If we find any edge cases, we could also introduce a `getPrimaryKey :: record -> PrimaryKey record` that will return the PK value.

> This seems to rely on id always being the first field in the data type, but I don't see that being enforced anywhere else. Am I missing something?

You're correct. This is not enforced and works only by convention. I think we need to rewrite this part of the code generation process to be able to deal with composite PKs.

**Comment by ruhatch** [comment]
> That's reasonable, I guessAm 10.08.2020 20:52 schrieb Ru Horlick <notifications@github.com>: @mpscholten I noticed that the CanUpdate instances don't allow updates of the id field. Would you expect the same from a CanUpdate with a composite key, i.e. you wouldn't be able to change any of the primary key fields? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ruhatch** [comment]
> You're correct. This is not enforced and works only by convention. I think we need to rewrite this part of the code generation process to be able to deal with composite PKs.

Okay, cool, I'm rewriting `compileFromRowInstance` to be more general now

**Comment by ruhatch** [comment]
@mpscholten things are going relatively well on this, but the UI code seems very tied into `id` as the first field!

`ShowTableRowsView` is an example of a place where it's a bit thorny. I'm happy to keep trying to generalise to composite ids, but just want to check that it seems worth it. What do you think?

I can post a draft PR with the current changes to give you an idea of where it is so far?

**Comment by mpscholten** [comment]
Happy to take a look :)

IMO when it's too much work we can also just display a `composite primary keys are not supported in the data tools` message in `ShowTableRowsView`. It's still an improvement compared to the current state (where it's not supported at all).

**Comment by ruhatch** [comment]
> Happy to take a look :)
> 
> IMO when it's too much work we can also just display a `composite primary keys are not supported in the data tools` message in `ShowTableRowsView`. It's still an improvement compared to the current state (where it's not supported at all).

That sounds like a reasonable step. So right now it would support changing the schema through the UI or manually, but once composite keys are used for a table the data tool would stop working.
