### ISSUE TITLE
composite UNIQUE constraint breaks generation

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#292]

**Comment by mpscholten** [comment]
Thanks for reporting! :) Is this the same error as in https://github.com/digitallyinduced/ihp/issues/232 ? Because then it's fixed once we have merged https://github.com/digitallyinduced/ihp/pull/290

**Comment by mpscholten** [comment]
the PR for the above issue has just been merged and will be available with the next IHP release coming this friday ✅

**Comment by mpscholten** [comment]
The fix for this has just been released :)
