### ISSUE TITLE
Mismatch Haskell UTCTime vs Postgres Timestamp: infinity 

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#306]
IHP Output

Details
The exception was raised while running the action: CreateTariffversionAction

ConversionFailed {errSQLType = "timestamptz", errSQLTableOid = Just (Oid 24716), errSQLField = "invalidatedat", errHaskellType = "UTCTime", errMessage = "Failed reading: takeWhile1"}

PSQL OUTPUT
  | invalidatedat | validfrom  | validthru 
--------------------------------------+--------------------------------------+-------------------------------+---------------+------------+-----------
 217d3525-fe69-4976-accb-d52c9b85152b | d9ff5359-271d-4740-96a4-b876e134bbd8 | 2020-08-06 15:39:30.523124+02 | infinity      | 1858-11-17 | infinity
 190829e1-a019-49bf-b777-6b2446084fcc | be8f03ab-191e-4be4-8202-5580305453b6 | 2020-08-06 19:02:45.184935+02 | infinity      | 1858-11-17 | infinity
 d7f0e771-c96f-469e-bab2-e9c97e73811c | b4f18d3d-02e5-480a-a1ec-d1c318ccc6b0 | 2020-08-06 19:17:10.103004+02 | infinity      | 1858-11-17 | infinity
(3 rows)

**Comment by mpscholten** [comment]
I think `UTCTime` is not able to represent the sql value `infinity`. This is something we cannot fix easily as this has to be changed in the underlying data type used by `postgresql-simple` (the lower level library used by IHP's database functions). A good workaround might be to make the column nullable (`null` representing `infinity`). Does that fix the issue?

**Comment by Kaeptenblaubaer** [comment]
That's the usual approach, but I prefer a real timestamp value, so it became New Year's Eve 2099 23:59:59 instead.  :-) This gives me intervals. Thank You for looking into it.Am 24.08.2020 20:06 schrieb Marc Scholten <notifications@github.com>:
I think UTCTime is not able to represent the sql value infinity. This is something we cannot fix easily as this has to be changed in the underlying data type used by postgresql-simple (the lower level library used by IHP's database functions). A good workaround might be to make the column nullable (null representing infinity). Does that fix the issue?

**Comment by mpscholten** [comment]
Ok this makes sense. I'm sure we'll somehow fix this until 2099 haha :D For now I'm going to close this as we'd basically have to fix this in postgresql-simple and this is more of an edge case.
