### ISSUE TITLE
No form field generated when default value selected for Text

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#308]
Hi, its me again trying to push forward a model containing floats ;-)!

## Steps to reproduce

1. ihp-new test
2. cd test and ./start
3. create new table in schema designer, add column `title`, select datatype Text and default value
4. update and push to db
5. create new codegen/Controller

## Expected

Form to have a form field to edit the title when creating new record for that table

## Bug

No textfield/formfield is rendered

**Comment by mpscholten** [comment]
Thanks for reporting :) Just pushed a fix to https://github.com/digitallyinduced/ihp/pull/322 This actually was the expected behavior (to avoid columns like `created_at` being part of the form). But found a better solution now to handle these kind of columns 👍
