### ISSUE TITLE
Code generation for BIGSERIAL still generates initializer and validator 

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#313]
![BIGINT-UUID](https://user-images.githubusercontent.com/12422482/89791380-8c282180-db23-11ea-9349-cde0ab23a1b9.PNG)

![BIGINT-UUID-PG](https://user-images.githubusercontent.com/12422482/89791716-f214a900-db23-11ea-8e54-eb65dddf2676.PNG)

**Comment by mpscholten** [comment]
What version of IHP are you running (you can find the IHP version in `default.nix` line 4)? [The latest release](https://github.com/digitallyinduced/ihp/releases/tag/v07082020) does not include the fix for the BIGSERIAL, so you should be on the latest master.

**Comment by Kaeptenblaubaer** [comment]
Yes master it is.Am 10.08.2020 17:05 schrieb Marc Scholten <notifications@github.com>:
What version of IHP are you running (you can find the IHP version in default.nix line 4)? The latest release does not include the fix for the BIGSERIAL, so you should be on the latest master.

**Comment by mpscholten** [comment]
I cannot reproduce currently. Can you share the schema.sql for this table?

Have you executed `make -B .envrc` after updating to the new version? Otherwise it might still run the old IHP version.

Maybe it also might be that the generated code has not been regenerated. Can you post the logs of the dev server when you start it? In case IHP fails to compile the schema.sql, the error will be shown there.

**Comment by Kaeptenblaubaer** [comment]
I misunderstood. Now I'm on master "b56ff1845805ca2e72b77de392a3ac49a259f513";
The problem remains.
trivial schema is 
[Schema.sql.txt](https://github.com/digitallyinduced/ihp/files/5058344/Schema.sql.txt)

**Comment by mpscholten** [comment]
Hm, this can really only happen when IHP is still using the old version. Here's how it looks for me:

![image](https://user-images.githubusercontent.com/2072185/89984171-3796ba80-dc79-11ea-959e-dcc35eacf166.png)

Can you run the following command and post the output of it:

```bash
nix-shell --run 'make -B .envrc; ./start'
```

**Comment by Kaeptenblaubaer** [comment]
Thank You for Your patience, I had ihp-new'ed and forgotten to redirct default.nix to master. :-)

**Comment by mpscholten** [comment]
So this is working now? :)

**Comment by Kaeptenblaubaer** [comment]
Yessss!

**Comment by mpscholten** [comment]
🎉 perfect 👍
