### ISSUE TITLE
Faunadb integration, easy to use

### ISSUE THREAD

**Issue by janat08** [digitallyinduced/ihp#317]
Faunadb asks that you provide it a graphql schema, to use, it sets up queries and indexes itself from what I remember.

**Comment by mpscholten** [comment]
Thanks for your suggestion! :-)

Faunadb looks very cool, but I think for IHP to be working well we have to stay focussed on a single database platform. We only have very limited resources, so we need to consider carefully which tools we want to add to the IHP stack. For now we'll stick with postgres as the only supported database platform.

Thanks again 👍

**Comment by janat08** [comment]
Can't you leave this under low priority or help needed?

**Comment by mpscholten** [comment]
Unless someone is actively trying to tackle this I‘d rather close this as it’s not something I can see becoming part of IHP soon

**Comment by janat08** [comment]
Could you write a recipe for using alternative db and tradeoffs that entails?

**Comment by janat08** [comment]
There's also hasura, and some other variant of instant api from looking at schema either in the sql or graphql. Besides fauna which is tied to non-sql db, there're 2 other ORMs that generate the api from schemas. You're probably in no small part trying to replicate their efforts, while you yourself may not be considering that to be your core product.
