### ISSUE TITLE
Live coding session: Unable to change email address (around min 88)

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#330]

**Comment by mpscholten** [comment]
Thanks for opening! :) This is caused by https://github.com/digitallyinduced/ihp-forum/blob/master/Web/Controller/Users.hs#L35 missing the `email` attribute. So this is not really a bug I guess :)

**Comment by themmes** [comment]
Ah yes, makes sense. In that case I’ll close this ticket!
