### ISSUE TITLE
Failed parsing UUID in Show and Edit operations where key column type is Bigserial

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#332]
**GET /ShowTariffversion
  Params: [("tariffversionId","1")]
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  Status: 500 Internal Server Error 0.0005188s
AutoRoute: Failed parsing UUID
CallStack (from HasCallStack):
  error, called at ./IHP/RouterSupport.hs:224:19 in ihp-0.1.0.0-BkpffE8tq5UEYAWij1jGE2-IHPFramework:IHP.RouterSupport**

rev = "df79e551951b807dfb8866c593477c42e1069f62";

Plain generated Controllers, nothing hand coded here.

[Schema.sql.txt](https://github.com/digitallyinduced/ihp/files/5078880/Schema.sql.txt)

[Fixtures.sql.txt](https://github.com/digitallyinduced/ihp/files/5078881/Fixtures.sql.txt)

**Comment by Kaeptenblaubaer** [comment]
Oh, wait! I sthis an instance of the override parseArgument case?

**Comment by Kaeptenblaubaer** [comment]
Yess it was

**Comment by mpscholten** [comment]
Thanks for reporting :) I've opened https://github.com/digitallyinduced/ihp/pull/334 to improve this error message 👍
