### ISSUE TITLE
uuid-ossp missing - Update DB fails

### ISSUE THREAD

**Issue by 2mol** [digitallyinduced/ihp#333]
[The documentation](https://ihp.digitallyinduced.com/Guide/your-first-project.html) mentions the line

```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

in `Application/Schema.sql `

This was not there by default when I first clicked "Update DB", which resulted in an error along the lines of

```
ERROR: function uuid_generate_v4() does not exist HINT: No function matches the given name and argument types
```

I'm using the latest IHP version. Adding it manually fixed the problem.

**Comment by mpscholten** [comment]
Hey, I cannot reproduce this issue with the latest IHP version. To avoid this kind of issue happening again we've moved this DB init step into the framework code (it's a technical implementation detail anyway, doesn't really belong to the app code). Therefore we can be safe that this setup code is not lost while making changes to the file :)
