### ISSUE TITLE
<script src="" defer></script> breaks HSX parsing

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#342]
https://www.w3schools.com/tags/att_script_defer.asp
e.g.  `<script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js" defer></script>`

this raises the following error when trying to add it to `Layout.hs`

```
ConnectionClosedunexpected '>'
expecting '=' or white space

```

**Comment by mpscholten** [comment]
Good catch, current workaround is to set `<script defer="defer">`, but we should still fix this
