### ISSUE TITLE
js-delete breaks when html anchor is not the leaf element

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#361]
I just stumbled upon this problem when creating a delete <button>

```
<a href="DeleteTodoAction (get #id todo)">
  <button>
    Delete
  </button>
</a>
```

In this case actually the `event.target` is not the `anchor`, but the `button`. I verified this by removing the HTMLAnchor check (here: ) and adding a `js-delete` to the button.

I was going to write a PR to remove the HTMLAnchor check, but that does not work. It uses the href from that specific element which does not exist on the button. 

Alternatively, we could recursively check parents for the `js-delete` class, however maybe you guys know of a better way to solve this?

**Comment by themmes** [comment]
I think I wrote a fix using `event.target.closest()`, however I am not sure how to apply this change to my project. Is there some documentation on how to contribute on the javascript code(and haskell, documentation for that matter)?

**Comment by mpscholten** [comment]
Good catch :) I think there's [`event.currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) which always refers to the element the event listener was registered to (in our case the `a`).

To make changes to the JS, follow the steps in https://github.com/digitallyinduced/ihp/blob/master/CONTRIBUTING.md#running-an-application-against-a-local-copy-of-the-framework

In short it should be like this:

```bash
cd $YOUR_PROJECT
git clone git@github.com:digitallyinduced/ihp.git IHP
make -B .envrc
make -B build/ihp-lib

# Now it should be ready to pick up the local IHP source instead of the release version
./start
```

Then you can make changes to `$YOUR_PROJECT/IHP/lib/IHP/static/helpers.js` :)

**Comment by themmes** [comment]
Hmm.. I might be mixing up stuff here. When I run `./start` after following your instructions I get a compilation error 

```
build/Generated/Types.hs:51:14
    • The constructor ‘ModelContext’ should have 2 arguments, but has been given 1
    • In the pattern: ModelContext conn
      In a pattern binding: (ModelContext conn) = ?modelContext
```

Is this an error because I'm now running the latest master or because I am mixing up versions?

**Comment by themmes** [comment]
Have not been able to finish this, after my holidays (2 weeks) I'll pick this up!

**Comment by mpscholten** [comment]
> Hmm.. I might be mixing up stuff here. When I run `./start` after following your instructions I get a compilation error
> 
> ```
> build/Generated/Types.hs:51:14
>     • The constructor ‘ModelContext’ should have 2 arguments, but has been given 1
>     • In the pattern: ModelContext conn
>       In a pattern binding: (ModelContext conn) = ?modelContext
> ```
> 
> Is this an error because I'm now running the latest master or because I am mixing up versions?

This is caused by the latest master. Try to run `nix-shell --run "make -B build/Generated/Types.hs"` or a `make clean` might also do the job.

This is caused by a change to the signature of ModelContext. So the generated types need to be regenerated to fit the new interface :)

**Comment by s0kil** [comment]
@mpscholten Can be closed.
