### ISSUE TITLE
Improve Session Functions

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#371]
Currently the IHP Sessions Functions only really work well with `Text` values. When you want to store other values like `Float` or `ByteString` or `Id Project` you always have to first convert them to a text and then later manually convert them back.

For a few cases we manually added functions such as `getSessionInt` or `getSessionUUID`. We should try to generalize this by introducing a type class `SessionValue`:

```haskell
class SessionValue value where
    toSessionValue :: value -> Text
    fromSessionValue :: Text -> value
```

Then we could use this type class for the `getSession` and `setSession` functions:

```haskell
action MyAction = do
    projectId <- getSession @(Id Project) "projectId"
    counter <- getSession @Int "counter"

    setSession "counter" (0 :: Int)
    setSession "userId" (get #id user)
```

Here is some IHP code that could be improved by this API change:

[Current:](https://github.com/digitallyinduced/ihp/blob/master/IHP/LoginSupport/Middleware.hs#L32)
```haskell
    user <- getSessionUUID (sessionKey @user)
            >>= pure . fmap (Newtype.pack @(Id user))
            >>= fetchOneOrNothing
```

After Update:
```haskell
    user <- getSession @(Id user) (sessionKey @user)
            >>= fetchOneOrNothing
```

All changes need to be made in [`IHP.Controller.Session`](https://github.com/digitallyinduced/ihp/blob/master/IHP/Controller/Session.hs).

**Comment by eddyjlhaigh** [comment]
Hey @mpscholten, is this still a good first issue? I'd be happy to give it a shot :)

**Comment by mpscholten** [comment]
Hey, yes 👍  feel free to tackle this

**Comment by Lipranu** [comment]
I suggest adding a type to display error types for an unsuccessful attempt to get a value from the session store.
```
data SessionError
    = VaultError      -- missing (sessionLookup, sessionInsert) pair
    | EmptyError      -- for cases when the key is absent, or the value is empty
    | ParseError Text
```
For cases where the type of error does not matter, you can use the getSession function. 
```
getSession :: forall value . (?context :: ControllerContext, SessionValue value)
           => Text -> IO (Maybe value)
```
If different types of errors need to be handled differently, you can use getEitherSession.
```
getEitherSession :: forall value . (?context :: ControllerContext, SessionValue value)
                 => Text -> IO (Either SessionError value)
```

**Comment by mpscholten** [comment]
Like the idea 👍 let’s do it that way

**Comment by s0kil** [comment]
This seems to be done.
