### ISSUE TITLE
Split nix derivations for library and executables

### ISSUE THREAD

**Issue by ruhatch** [digitallyinduced/ihp#384]
While hacking on the IHP library, small changes to e.g. DevServer require rebuilding the entire IHPFramework library. It would be good to try and split these into smaller nix derivations to make them easier to work with.

**Comment by mpscholten** [comment]
I'm always loading the dev server into my ghci. IMO this way you have the best feedback loop.

**Comment by ruhatch** [comment]
> I'm always loading the dev server into my ghci. IMO this way you have the best feedback loop.

Yeah, I've been doing that as well, but sometimes you need to keep building the executable! It's not a huge deal though, so feel free to close this one :shrug:

**Comment by mpscholten** [comment]
Ok, just wanted to make sure :) happy to keep it open 👍
