### ISSUE TITLE
static/helpers.js dateTime producing incorrect output for locales with 12-hour time

### ISSUE THREAD

**Issue by dansvo** [digitallyinduced/ihp#390]
I'm in a locale where `.toLocaleTimeString()` produces output like `9:20:50 PM`.

Currently at the tip of master, dateTime produces a time stamp without seconds by cutting down to 5 characters
https://github.com/digitallyinduced/ihp/blob/e6f0bcd037e8c3cbe8a74c4bf8db663d2def14ef/lib/IHP/static/helpers.js#L33-L35

This produces the output `9:20:` for this locale. It should instead read something like `9:20 PM`.

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/pull/391
