### ISSUE TITLE
Enhancement: a vscode extension that can deal with inline hsx

### ISSUE THREAD

**Issue by HugoPeters1024** [digitallyinduced/ihp#406]
It would be nice for vscode users to get html syntax highlighting and auto complete suggestions while working on hsx sections.

**Comment by mpscholten** [comment]
We could take a look at https://github.com/mjbvz/vscode-lit-html This basically embeds html into JS. We're dealing with a similiar problem (html in haskell). It seems like the extension [basically registers a syntax JSON file](https://github.com/mjbvz/vscode-lit-html/blob/master/syntaxes/lit-html.json). If we change this a little bit it should work with HSX.

Then we could try to get this merged into the `Haskell` extension or create a new `IHP` or `HSX` extension :)

**Comment by jbpotonnier** [comment]
I think the documentation can help https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages

The scope for quasiquote  has just been added to language-haskell 
https://github.com/JustusAdam/language-haskell/issues/23#issuecomment-710374439

**Comment by mpscholten** [comment]
Very cool, thanks for sharing 👍

**Comment by s0kil** [comment]
The extension should also include Emmet support.

**Comment by s0kil** [comment]
I've created an extension that provides syntax highlighting for HSX, https://github.com/s0kil/vscode-hsx
Also, checkout the README which shows how to enable Emmet support.

**Comment by mpscholten** [comment]
Good job! :) We should add this extension to https://ihp.digitallyinduced.com/Guide/editors.html#using-ihp-with-visual-studio-code-vscode :)

**Comment by fegu** [comment]
Looking forward to trying this, have missed syntax highlighting in hsx!

**Comment by s0kil** [comment]
Autocompletion will be tracked here: https://github.com/s0kil/vscode-hsx/issues/1
Otherwise, let's consider this closed.

**Comment by s0kil** [comment]
Autocompletion has been implemented in https://github.com/s0kil/vscode-hsx/pull/2
Will be available in version 0.2.0.
