### ISSUE TITLE
The AuthSupport module should be updated to include salts for password hashes

### ISSUE THREAD

**Issue by HugoPeters1024** [digitallyinduced/ihp#408]
Not salting passwords is a major security concern that should never be advocated. Although developers should know better the reality is that many people will deploy their app after just reading the guide.

Password verification logic can be found in: `IHP/AuthSupport/Authentication.hs`

**Comment by HugoPeters1024** [comment]
Frustratingly, the crypto library https://hackage.haskell.org/package/pwstore-fast-2.4.4/docs/Crypto-PasswordStore.html#t:Salt perfectly supports generating a password with a salt but it doesn't seem to implement any verifyPassword version that takes a salt.

**Comment by mpscholten** [comment]
IHPs [`hashPassword`](https://ihp.digitallyinduced.com/api-docs/src/IHP.AuthSupport.Authentication.html#hashPassword) is using `Crypto.PasswordStore.makePassword`. In the docu it says  `Hash a password with a given strength (17 is a good default). The output of this function can be written directly to a password file or database. Generates a salt using high-quality randomness from /dev/urandom or (if that is not available, for example on Windows) Random, which is included in the hashed output.` So I think the Pws are already salted :)

**Comment by HugoPeters1024** [comment]
Ah the ol' 'should have read the docs better'. Of course the salts are stored as part of the hash, the fact that there was no explicit salt argument put me off. Well great to hear, closing.
