### ISSUE TITLE
broken build: FrameworkConfig context not bound in FrontController

### ISSUE THREAD

**Issue by HugoPeters1024** [digitallyinduced/ihp#416]
Since https://github.com/digitallyinduced/ihp/commit/10c6ca5a6163dcee76841181c107f65c47434a66 a newly generated project does not support developing (`:l Main`) because of a compilation error:

```
Web/FrontController.hs:12:11: error:
    * Could not deduce IHP.FrameworkConfig.FrameworkConfig
        arising from a use of `startPage'
      from the context: (?applicationContext::IHP.ApplicationContext.ApplicationContext,
                         ?application::WebApplication, ?requestContext::RequestContext)
        bound by the type signature for:
                   controllers :: (?applicationContext::IHP.ApplicationContext.ApplicationContext,
                                   ?application::WebApplication, ?requestContext::RequestContext) =>
                                  [Parser (IO Network.Wai.Internal.ResponseReceived)]
        at Web/FrontController.hs:11:5-15
    * In the expression: startPage WelcomeAction
      In the expression: [startPage WelcomeAction]
      In an equation for `controllers':
          controllers = [startPage WelcomeAction]
   |
12 |         [ startPage WelcomeAction
   | 
```

Perhaps the routine described in CONTRIBUTING.md could be added as a CI stage to prevent this in the future

**Comment by mpscholten** [comment]
Thanks for reporting. Yes, we should add this to the test suite IMO 👍

**Comment by mpscholten** [comment]
The problem seems to be that the instance of `FrameworkConfig` defined in `Config/Config.hs` is not loaded. Usually the `Config.hs is` loaded by the `Main`, but because the `Web.FrontController` is also imported by `Main` the Config instance is not available yet. I think a good solution is to add the constraint to the `FrontController` class as well.

**Comment by mpscholten** [comment]
Pushed a fix :) Can you try again?

Also opened https://github.com/digitallyinduced/ihp/issues/418

**Comment by HugoPeters1024** [comment]
Everything is working now! :+1:
