### ISSUE TITLE
Shouldn't hardcode localhost?

### ISSUE THREAD

**Issue by warpr** [digitallyinduced/ihp#422]
Hello!

I followed the instructions at https://ihp.digitallyinduced.com/Guide/installation.html to install IHP.  I had some trouble with nix on MacOS, so installed it on a linux host instead.

The linux host is using 10.237.0.238 on the LAN, and I can connect to IHP by going to http://10.237.0.238:8001.  However, the app seems to have localhost hardcoded in various places, which prevents it from working correctly.

For example, following the guide to create a table the table gets created correctly, but the dialog never closes:

![Screen Shot 2020-09-24 at 07 47 20](https://user-images.githubusercontent.com/85700/94147422-deef3b80-fe3a-11ea-945f-ba6de493cafc.png)

It seems IHP should use whatever hostname or IP address I used to connect to it instead of "localhost".  In the meantime, is there a way to configure IHP to use a different hostname/ip address?

**Comment by mpscholten** [comment]
Thanks for reporting. Agree that we should always use the current host.

Inside your app `Config/Config.hs` you can define a custom hostname as a workaround like:
```
instance FrameworkConfig where
    environment = Development
    appHostname = "10.237.0.238"
```

This setting will only affect the app itself. The dev tooling still expects a lot of stuff to be running on localhost.

**Comment by mpscholten** [comment]
This has been fixed now with the recent Gitpod integration :) Check the documentation here to learn what env var's to set: https://ihp.digitallyinduced.com/Guide/editors.html#running-the-ihp-dev-server-on-a-host-different-from-localhost
