### ISSUE TITLE
how do i install the: Integrated Haskell Platform, and all of it's tools on my own local nixos machine ?

### ISSUE THREAD

**Issue by zeta-00** [digitallyinduced/ihp#424]
hello there, i just tried out the Integrated Haskell Platform today, and it's amazing, but i'd prefer to install all the tools on my own local nixos machine, in a shell.nix file, instead doing the things on a web-browser, so is there some good documentation out there on how to do this ? i'm guessing that i need to clone this repo and import all the nix files into a shell.nix file in order to install all the tools, but i'm not sure ?

if you could please clarify this for me, thanks, this Integrated Haskell Platform is a great tool, it's good to see a lot of good haskell-web-frameworks out there !

note, my setup is: (lorri+direnv+emacs-direnv), which I use to code in isolated nix environments.

**Comment by mpscholten** [comment]
hey :) thanks for opening the issue.

IHP is actually already providing a `shell.nix` for you. It's just a bit hidden.

Usually to get started with IHP you install the `ihp-new` tool. This tool checks that `direnv`, `cachix`, `git` and `make` are available and then does a `git clone` of the boilerplate repository.

Usually this is installed globally:
```
nix-env -f https://ihp.digitallyinduced.com/ihp-new.tar.gz -i ihp-new
```

If you don't want to install this globally for now, you can just copy + paste the code from here https://github.com/digitallyinduced/ihp/blob/master/ProjectGenerator/bin/ihp-new into a shell file on your system. Or you could also just run the commands manually in your terminal.

The `ihp-new` script will do a `git clone https://github.com/digitallyinduced/ihp-boilerplate.git`. In that `ihp-boilerplate` we have a `shell.nix` that is used for actually managing your project's dependencies. The `ihp-new` script will basically just start a `nix-shell` in your project, which triggers a download of all the project dependencies. So ihp is never installed globally.

Btw: similiar to lorri, IHP is caching the result of `nix-shell` into the `.envrc`. We'll repace our custom approach with lorri in the future.

**Comment by zeta-00** [comment]
@mpscholten , great, thanks for the help, i'll try setup IHP in an isolated environment with your solution! note: I also switched from lorri to nix-direnv( https://github.com/nix-community/nix-direnv ), so my current nix dev setup is: (direnv+nix-direnv+emacs-direnv), so hopefully with this setup I can get IHP to install locally on my nixos machine.
Thanks again! I can't wait to try out IHP some more!
