### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by teu5us** [digitallyinduced/ihp#429]
Tried to set up a new project on NixOS following the guide. After executing `./start` I see the Schema page. Clicking on App takes me to localhost:8000 and the page says it "Is compiling", I never see the actual page.

`DEBUG=1 ./start` produces the following:

```
 ===> AppState {postgresState = NotStarted, appGHCIState = NotStarted, statusServerState = NotStarted, liveReloadNotificationServerState = NotStarted, fileWatcherState = NotStarted, toolServerState = NotStarted}
UpdateToolServerState Started
 ===> AppState {postgresState = NotStarted, appGHCIState = NotStarted, statusServerState = NotStarted, liveReloadNotificationServerState = NotStarted, fileWatcherState = NotStarted, toolServerState = Started}
UpdateStatusServerState Started
 ===> AppState {postgresState = NotStarted, appGHCIState = NotStarted, statusServerState = Started, liveReloadNotificationServerState = NotStarted, fileWatcherState = NotStarted, toolServerState = Started}
UpdateLiveReloadNotificationServerState Started
 ===> AppState {postgresState = NotStarted, appGHCIState = NotStarted, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = NotStarted, toolServerState = Started}
GHCI: :script build/ihp-lib//applicationGhciConfig
GHCI: import qualified ClassyPrelude
GHCI: :l Main.hs
UpdatePostgresState Started
 ===> AppState {postgresState = Started, appGHCIState = NotStarted, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = NotStarted, toolServerState = Started}
UpdateFileWatcherState Started
 ===> AppState {postgresState = Started, appGHCIState = NotStarted, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
UpdateAppGHCIState Loading
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
ReceiveAppOutput {line = StandardOutput "GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help"}
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
ReceiveAppOutput {line = StandardOutput "package flags have changed, resetting and loading new packages..."}
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
ReceiveAppOutput {line = StandardOutput "package flags have changed, resetting and loading new packages..."}
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
ReceiveAppOutput {line = StandardOutput "Loaded GHCi configuration from /home/paul/Documents/code/ihp/blog/.ghci"}
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
ReceiveAppOutput {line = StandardOutput "Loaded GHCi configuration from /nix/store/lgv6kkh2h1sfjf11vx48pvykfk701ymh-hm_ghci"}
 ===> AppState {postgresState = Started, appGHCIState = Loading, statusServerState = Started, liveReloadNotificationServerState = Started, fileWatcherState = Started, toolServerState = Started}
Opening in existing browser session.
GET /
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  Status: 200 OK 0.001244703s
```

**Comment by mpscholten** [comment]
Thanks for reporting :) What happens when you run `ghci` inside the project directory? What happens when you type `:l Main` inside that `ghci`?

**Comment by teu5us** [comment]
@mpscholten it loads correctly. At least it seems so, no errors from ghci

**Comment by mpscholten** [comment]
Ok very strange. What nixos version and nixpkgs version are you on?

**Comment by teu5us** [comment]
20.03 for both

**Comment by teu5us** [comment]
An update. Now I'm getting segfault after launching `ghci` in the project environment

**Comment by mpscholten** [comment]
Can you run this script https://github.com/digitallyinduced/ihp/blob/9aa771c7eeef18179562bc390b2b8724488b4221/Troubleshoot/ihp-troubleshoot and paste the output? :) Maybe it gives us some more information to work with.

**Comment by teu5us** [comment]
ihp-troubleshoot:

```
Checking that the current directory is an IHP project:
+ Found Main.hs
+ Found start
Checking nix:
+ Nix installed
Checking direnv:
+ Found .envrc
+ direnv loads .envrc
+ ghci is loaded from nix store
Checking .ghci:
+ Found .ghci
+ .ghci permissions are ok
Checking IHP:
+ Symlink build/ihp-lib exists
- Symlink build/ihp-lib target directory does not exist. Try 'nix-shell --run -- make -B build/ihp-lib' to fix this
+ IHP used from nix
Checking Cachix:
+ Cachix config exists
+ digitallyinduced.cachix.org configured
+ No legacy cachix key found
Debugging Details:
GHCI Output:
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
package flags have changed, resetting and loading new packages...
build/ihp-lib Target:
/nix/store/651v681jd0wr45mhnh2rsnmfihp6psf7-ghc-8.8.3-with-packages/bin/../lib/IHP
Direnv Output:
direnv exec path /nix/store/kn11223r7pi8fh9pvwj2y7kbc2wncc3h-direnv-2.21.2-bin/bin/direnv
DIRENV_CONFIG /home/paul/.config/direnv
bash_path /nix/store/4xb9z8vvk3fk2ciwqh53hzp72d0hx1da-bash-interactive-4.4-p23/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /home/paul/Documents/code/ihp/blog/.envrc
Loaded watch: ".envrc" - 2020-10-14T11:56:58+06:00
Loaded watch: "../../../../.local/share/direnv/allow/88a2b71aadb5c28ef797f12bda8e3092b8a931b75ac29535ac316499434a2a0f" - 2020-10-14T12:00:29+06:00
Loaded RC allowed false
Loaded RC allowPath 
Found RC path /home/paul/Documents/code/ihp/blog/.envrc
Found watch: ".envrc" - 2020-10-14T11:56:58+06:00
Found watch: "../../../../.local/share/direnv/allow/88a2b71aadb5c28ef797f12bda8e3092b8a931b75ac29535ac316499434a2a0f" - 2020-10-14T12:00:29+06:00
Found RC allowed true
Found RC allowPath /home/paul/.local/share/direnv/allow/88a2b71aadb5c28ef797f12bda8e3092b8a931b75ac29535ac316499434a2a0f
which direnv Output:
/nix/store/651v681jd0wr45mhnh2rsnmfihp6psf7-ghc-8.8.3-with-packages/bin/ghci
default.nix:
let
    ihp = builtins.fetchGit {
        url = "https://github.com/digitallyinduced/ihp.git";
        rev = "c4d2815f064c055cd957389a4df5eab25294dba3";
    };
OS:
Linux
```

Then `nix-shell --run -- make -B build/ihp-lib`:

```
error: unrecognised flag '-B'
Try 'nix-shell --help' for more information.
```

**Comment by teu5us** [comment]
After running `make -B build/ihp-lib` in nix-shell still getting the same output from `ihp-troubleshoot`

**Comment by mpscholten** [comment]
It complains because it think that the symlink at `build/ihp-lib` points to a directory that does not exist anymore (e.g. happens when you used nix GC). Can you check that `/nix/store/651v681jd0wr45mhnh2rsnmfihp6psf7-ghc-8.8.3-with-packages/bin/../lib/IHP` exists on your system?

**Comment by teu5us** [comment]
Yes, it is in the store

**Comment by mpscholten** [comment]
Ok then `Symlink build/ihp-lib target directory does not exist.` is just a bug in the script

**Comment by mpscholten** [comment]
Testing it right now in a VM

**Comment by mpscholten** [comment]
Works fine in my VM.

Looking at the segfault log above it seems to crashing at the linking phase for the unix module. Do you have any special stuff on your nixos that could affect linking? How much memory do you have?

**Comment by teu5us** [comment]
Not sure about something that could interfere. I have 12 GB RAM and 30 GB free storage

**Comment by teu5us** [comment]
It seems that `ghci` only launches with `-ignore-dot-ghci` even outside the project

**Comment by teu5us** [comment]
Ghci segfaults on `:set -package ihp` for some reason

**Comment by teu5us** [comment]
`ghci` launches in tty, but not under Xorg. However, I can run `ghci` in project in `nix-shell --pure` and the project compiles

**Comment by teu5us** [comment]
Not sure what the problem is, but:

1. I can run `ghci` in tty and execute `:set -package unix`;
2. I cannot do n.1 under Xorg;
3. I can do n.1 under `nix-shell --pure` in Xorg.

I was able to finally launch the project like so:

1. `ihp-new blog`;
2. `cd blog && ./start`;
3. Interrupt the process with <kbd>C-c</kbd>;
4. `nix-shell --pure`, then `./start`.

**Comment by mpscholten** [comment]
I'm still a bit confused about how Xorg can affect the `:set -package unix` call. Does that also happen when you load any other haskell package?


> Interrupt the process with C-c;

I could imagine the dev server being stuck at opening the browser window. It calls [`xdg-open http://localhost:8000`](https://github.com/digitallyinduced/ihp/blob/97a9a379bab7c7d6dd131baf59e70acb57a30b91/IHP/IDE/ToolServer.hs#L98).  We have had issues with that in the past. Can you try to override the open function by using this:

```bash
export IHP_BROWSER=echo
./start
```

(from https://ihp.digitallyinduced.com/Guide/recipes.html#dont-autoopen-the-app-in-the-browser)

What happens then?

**Comment by teu5us** [comment]
Didn't have such issues with haskell packages before, but pretty sure that's something in my nix-profile.

My browser opens automatically, but ghci is not running, so no working app. Seems to work in pure nix-shell though

**Comment by teu5us** [comment]
Emacs seems to be my problem. I am running gccEmacs with EXWM as my window manager. Just tried with dwm and `:set -package unix` worked as it should as well as the IHP `start` script

**Comment by mpscholten** [comment]
Do you have any ideas how we can identify what part of emacs or EXWM is causing the problem? Maybe we can add a note [to the docs](https://ihp.digitallyinduced.com/Guide/editors.html#using-ihp-with-emacs) that EXWM causes trouble together with IHP.

**Comment by teu5us** [comment]
I will try without native-comp in a moment. The problem might be caused by the gccEmacs wrapper, I think

**Comment by teu5us** [comment]
Indeed the problem is gone when I don't use the [wrapped](https://gist.github.com/mjlbach/179cf58e1b6f5afcb9a99d4aaf54f549/revisions?short_path=d47f9d5#diff-d47f9d5d47230f86121998a90ed5bd8787847847e6855b5b9c80685dca224658) gccEmacs. That gist has been updated since I copied the overlay configuration, so need to try that too

**Comment by teu5us** [comment]
No problems with this instead of wrapper:

```
programs = {
    emacs = {
      enable = true;
      package = unstable.emacsGcc.override
        { imagemagick = unstable.imagemagick; };
      extraPackages = (epkgs: with epkgs; [
        pdf-tools
        elpy
        haskell-mode
        hamlet-mode
        lispy
        evil-lispy
        exwm
        jupyter
      ] ++ (with unstable; [
        libvterm gcc cmake gnumake
      ]));
};
```
