### ISSUE TITLE
Add row error for blank site

### ISSUE THREAD

**Issue by kandelvijaya** [digitallyinduced/ihp#446]
I followed the steps in the getting started guide. 

I got and added schema `Post` and wanted to add a entry; which i failing with this error:

```sh
SqlError {sqlState = "22P02", sqlExecStatus = FatalError, sqlErrorMsg = "invalid input syntax for type uuid: \"uuid_generate_v4()\"", sqlErrorDetail = "", sqlErrorHint = ""}
An exception was raised while running the action CreateRowAction
```

Seems like the issue is on uuuid. I tried replacing with plain text but that doesnot help either.

**Comment by mpscholten** [comment]
Thanks for reporting 👍  This is a know issue, will be fixed with the next release :)
