### ISSUE TITLE
Error creating enum attribute via schema designer

### ISSUE THREAD

**Issue by TDiazT** [digitallyinduced/ihp#448]
Hi, 

I encountered an error while trying to setup an attribute with an enum type (it's fixed in my case, but figured it was better to report it). 
Basically what I did was:
1. Created a table `X`
2. Created enum type `Y` 
3. Created new attribute `Z` in table `X` with type `Y`

When trying to update the db you get the following error:
![image](https://user-images.githubusercontent.com/7966908/95007774-d1c80e80-05e9-11eb-860b-cdd7e485dddc.png)

I checked the `Schema.sql` and noticed that the enum type is defined after the table (bc indeed, I created the enum type after the table). The problem is that when updating the db, the enum type is not found when creating the table, so it crashes (I imagine that's the error). 
Solution: Simply moved the creation of the enum type before the tables :shrug:. 

```sql
e.g. 
CREATE TYPE foo AS ENUM ('1');
CREATE TABLE bar (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    baz foo NOT NULL
);
```

**Comment by mpscholten** [comment]
Thanks for reporting! :) I think the solution is to change the behavior so that enums are always placed before all tables. Will take a look soon.
