### ISSUE TITLE
Console Output is not thread safe

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#450]
> the logging on the dev server is not thread safe. Two windows open will give you stuff like: ("S(E"LSEECLTE CtTo oplrso.je cFtRsO.M tFoRoOlMs p r"o,j[e]c)t
s ORDER BY tprojectno ",[])

**Comment by xterolax** [comment]
It is thread safe, but this is probably just normal putStr/putStrLn behaviour as they output characters one by one.

**Comment by tjlaxs** [comment]
This is thread safe, but also probably just normal putStr/putStrLn behavior as it outputs strings characters one by one.

**Comment by mpscholten** [comment]
This was fixed recently via https://github.com/digitallyinduced/ihp/commit/c1aacc1d49d73fdd6c57ece012e461b70164be47 :)
