### ISSUE TITLE
Any button in renderForm will act as submit?

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#455]
**Context**

In this MR https://github.com/digitallyinduced/ihp-forum/pull/13 I created an additional button in the form that simply takes you back to the thread. 

**Bug**

However this button shows `type=submit` behaviour, while I did not assign this...

**Steps to reproduce**

1. Create basic project with one model and a New View
2. Add an extra button to `renderForm`

**Comment by hendi** [comment]
I don't think that's a bug in IHP. Every `<button>` in a `<form>` has by browser's default `type="submit"`, if you don't want that you have to manually set `type="button"`.

@mpscholten Maybe add a custom `{button}` that defaults to `type="button"` to make this behaviour of browsers obvious?
