### ISSUE TITLE
PG connection permanently drops

### ISSUE THREAD

**Issue by fegu** [digitallyinduced/ihp#463]
Every morning so far in production, probably due to periods of inactivity (during the night), IHP is permanently down until a restart of the server process. The error message is one of two, either:

libpq: failed (no connection to the server )
An exception was raised while running the action MainAction while calling initContext

or an error related to SSL connection giving no reply.

I am running postgres on a separate server and with enforced SSL-connections. I am guessing some timeout causes the connection to go down, and then IHP does not seem to reconnect. Should always try to reconnect, if a query gives connection exception.

**Comment by mpscholten** [comment]
We've been thinking about using a connection pool for having multiple db connections open from a single IHP server process. With the pool we could just pick a different connection once a connection is dead (and remove the dead one from the pool of course). We'll add some more prio to the pooling topic so this issue will be fixed soon (cc @andreasrueb).
