### ISSUE TITLE
Haskell Language Server:  `GLIBC_2.32' not found

### ISSUE THREAD

**Issue by paparga** [digitallyinduced/ihp#476]
OS: Windows 10 WSL 2 with Ubuntu 20.04.1 LTS
Editor: VS Code with Remote WSL extension 
Error mesage:
```
Unexpected usage error
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /nix/store/bdf8iipzya03h2amgfncqpclf6bmy3a1-glibc-2.32/lib/librt.so)

```

**Comment by paparga** [comment]
It's seems I didn't read de docs well:
`
You need to install the following extensions:
nix-env-selector, this loads the project default.nix file, so all the right haskell packages are available to VSCode
`

**Comment by mpscholten** [comment]
Thanks for reporting back on this :) Good to see this resolved.

In case someone finds this issue via Google at some point in the future and is stuck with the same problem: Check out this YT video: https://www.youtube.com/watch?v=_8_8XYO6rgY
