### ISSUE TITLE
Include Welcome Page in ihp-boilerplate

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#481]
> I'm not sure if this is something you've talked about before but it would be nice if the files for the "welcome" page were included in the scaffolding and not inside of the IHP package. that way new learners (i.e. me) can modify it and see changes made quickly

**Comment by dixonary** [comment]
On a related point, the Welcome page should also follow the MVC discipline. Currently the view is embedded inside of the controller file.

**Comment by Montmorency** [comment]
This would be a useful way to include a Static view directory and controller in the ihp-boilerplate template. At the moment it is a recipe, but when spinning out a new project it would be easy to just extend/modify an existing `/Welcome` page with new static pages e.g. `/About`, `/Terms` etc.

**Comment by Montmorency** [comment]
Hey I have a sketch here of an implementation: https://github.com/Montmorency/ihp/tree/welcome-page this would modify `FrontController` and add a `StaticController.hs` and `applicationName/Views/Static` directory to boilerplate. The only issue is the current svg icon which (now that I think about it) could jsut be moved to static in the boilerplate. Let me know if this seems sensible and I can open a PR (after testing;).

**Comment by mpscholten** [comment]
Looks good to me 👍

**Comment by Montmorency** [comment]
Sound pull request issued however I'm not sure how to build the ihp-new binary against this updated IHP version IHP so requires more testing.

**Comment by mpscholten** [comment]
`ihp-new` always pulls the latest master of `ihp-boilerplate`. So there's no direct way to test it with `ihp-new`. But the script behind `ihp-new` is rather simple. You can just copy paste the commands and run them manually.

[The important part start at line 108 in ihp-new.](https://github.com/digitallyinduced/ihp/blob/master/ProjectGenerator/bin/ihp-new#L108) Before that it's just checking that all the tools that it needs are there. Replace `BOILERPLATE_GIT_URL` with your fork of ihp-boilerplate and `PROJECT_NAME` is just the first argument passed to `ihp-new` :)

```
git clone --quiet --depth=1 "$BOILERPLATE_GIT_URL" -- "$PROJECT_NAME"
cd "$PROJECT_NAME"
rm -rf ".git"

nix-shell -j auto --cores 0 --quiet --run 'make -s all; new-application Web'
echo "🚀 Project created, happy coding :)"
echo "You can start the server by running:"
echo "  cd $PROJECT_NAME"
echo "  ./start"
```

**Comment by mpscholten** [comment]
This has been shipped with the latest release :)
