### ISSUE TITLE
Overloading of `Html`

### ISSUE THREAD

**Issue by dixonary** [digitallyinduced/ihp#482]
The type Layout is an alias for `Html -> Html` where `Html` is the standard `Text.Blaze.Html` definition.

In the default scaffold module `Web.View.Layout`, `Html` is redefined to be `HtmlWithContext ViewContext`, which adds an implicit parameter `viewContext :: context`.

This is confusing, as one would naturally expect `defaultLayout` to be of type `Layout` but in fact it is the same type with an implicit parameter. So you cannot simply replace arbitrary `Layout` functions for `defaultLayout`.

My suggested fix would be to rename the `Html` alias in `Web.View.Layout` with `ViewHtml` or similar to emphasise that they are different.

Alternatively, create a type alias `type ViewLayout = HtmlWithContext ViewContext -> HtmlWithContext ViewContext`

**Comment by mpscholten** [comment]
The ViewContext has been removed with the last IHP version, so this should be fixed now :)
