### ISSUE TITLE
imagemagick cannot be installed with current IHP version

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#484]

**Comment by Montmorency** [comment]
There were two quick patches that fixed up the lcms2 (little color management system) and cairo dependencies on darwin:
add these to the `./Config/nix/nixpkgs-config.nix`
```
  config = {
    allowBroken = true;
    packageOverrides = pkgs: rec {
                           ...
      lcms2 = pkgs.lcms2.overrideAttrs (oldAttrs: rec {
                        LDFLAGS = ''-Wl,-w'';
                        });
      cairo = pkgs.cairo.overrideAttrs (oldAttrs: {
             preConfigure=''sed -i.bu 's/if test "x$cairo_cc_stderr" != "x"; then/if false; then/' configure'';
                        });
    };
  };
```

However the build was still failing with the final issue which is some strange linking bug with rustc-1.46.0 on darwin which is far beyond my powers of understanding. Not sure where rustc came in as a dependency. This is holding up nixpkgs-unstable going green on nix hydra atm.

**Comment by Montmorency** [comment]
Looks like a potential fix for [rustc](https://github.com/NixOS/nixpkgs/pull/101136) pushed to nixpkgs master. It is a top level fix in `pkgs/top-level/all-packages.nix/

```
rust_1_46 = callPackage ../development/compilers/rust/1_46.nix {
    inherit (darwin.apple_sdk.frameworks) CoreFoundation Security;
    llvmPackages = if stdenv.cc.isClang then llvmPackages_5 else llvmPackages_10;
  };
  rust = rust_1_46;
```

Not sure this what the best way of including this I can't see how to fit this into override: 
I tried adding this to nixpkgs-config.nix

```
      rust = pkgs.rust.override {
                    inherit (pkgs.darwin.apple_sdk.frameworks) CoreFoundation Security;
                    stdenv = pkgs.llvmPackages_5.stdenv;
                    llvmPackages = pkgs.llvmPackages_5.stdenv;
                    };
```

but the link error persisted.

Should all be fixed automatically in the next nixpkgs bump in IHP though ;)
