### ISSUE TITLE
database type binary

### ISSUE THREAD

**Issue by StefanYohansson** [digitallyinduced/ihp#502]
trying to create a table photo with type binary and try to update DB it fails with message Binary type doesn't exist. It works if I edit SQL directly on the "code editor" toggle and put `bytea` as column.

please let me know if you guys need more info (any debug info or something like that) about it.

**Comment by mpscholten** [comment]
Thanks for reporting 👍 This issue has been fixed on master two days ago, see https://github.com/digitallyinduced/ihp/commit/b8b172017d6afc4b0de46b51463aacb3bcc1049c 

Will be released with the next IHP release on friday. If you don't want to wait for friday, [follow this guide to update your project to the latest master version](https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-the-latest-git-commit) :)

**Comment by StefanYohansson** [comment]
Thank you, I am just trying/learning about IHP, so I can wait :+1: 

I am closing this one.
