### ISSUE TITLE
File uploads should have cloud storage option

### ISSUE THREAD

**Issue by fegu** [digitallyinduced/ihp#516]
File uploads automagically appear in /static/uploads/action/id. Using the local filesystem is a bit dated, we should offer configurable cloud storage options where people could choose provider (e.g. Azure or AWS) and enter their own access key to their own blob storage account.

(also, uploads currently keep the original file as picture.upload wasting space. Keeping this file should at least be configurable)

**Comment by mpscholten** [comment]
This has been shipped already https://ihp.digitallyinduced.com/Guide/file-storage.html :)
