### ISSUE TITLE
Issue with auto-generating routes

### ISSUE THREAD

**Issue by YannickLeRoux** [digitallyinduced/ihp#521]
First, well 2nd time that I am trying to play with IHP.
I ran into this error at the very beginning. I just created a very simple schema with 3 text fields:

```
CREATE TABLE loom_videos (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT NULL,
    link TEXT NOT NULL UNIQUE
);
```

Then `UpdateDB` and `Generate Controller` for this model.
I got:

```
Web/Routes.hs:7:20: error:
    Not in scope: type constructor or class ‘StaticControllerinstance’
  |
7 | instance AutoRoute StaticControllerinstance AutoRoute LoomVideosController
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^
Failed, six modules loaded.
pg_dump -a --inserts --column-inserts --disable-triggers -h $PWD/build/db app | sed -e '/^--/d' > Application/Fixtures.sql

```
Looks like turn this into that works now: 
`instance AutoRoute LoomVideosController`

So it looks like the generator didn't work as intended (I am working with the latest version)

**Comment by mpscholten** [comment]
Looks like we broke something in the last release. I'll check this right now. Also saw some discussion about this problem in the IHP forum: https://forum.ihpapp.com/ShowThread?threadId=13100a22-a9eb-4c0b-9587-e4e0ae587ff1

**Comment by mpscholten** [comment]
Just tagged a new release: https://github.com/digitallyinduced/ihp/releases/tag/v20201101

That will fix the issue. If you don't want to update for now, you can also just add a manual new line character in `Web/Routes.hs`.

Current Code:
```haskell
instance AutoRoute StaticControllerinstance AutoRoute LoomVideosController
```

Change this to:
```haskell
instance AutoRoute StaticController
instance AutoRoute LoomVideosController
```

**Comment by YannickLeRoux** [comment]
Great, thanks!

**Comment by mpscholten** [comment]
I guess this can be closed now. Feel free to comment if you think there's still something to do :) Thanks again for opening the issue :)
