### ISSUE TITLE
Problems with psql connection, "user reader_1 does not exist"

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#525]
```
macOS Catalina 10.15.4
nix (Nix) 2.3.6
rev = "e21f5d743104ba8b1bed185ee85fb20e064e0bef";
```

Since the new release I am having problems with the connection to psql. Even in a fresh project trying to create a table and press "Update DB" leads to 

```
psql: FATAL: role "reader_1" does not exist psql: FATAL: role "reader_1" does not exist psql: FATAL: role "reader_1" does not exist psql: FATAL: role "reader_1" does not exist make: *** [/nix/store/84587ajkrkghy7cpamvxy2hs1rhhvks4-ghc-8.8.3-with-packages/bin/../lib/IHP/Makefile.dist:112: db] Error 2 echo "drop schema public cascade; create schema public;" | psql -h $PWD/build/db -d app psql -h $PWD/build/db -d app < "/nix/store/84587ajkrkghy7cpamvxy2hs1rhhvks4-ghc-8.8.3-with-packages/bin/../lib/IHP/IHPSchema.sql" psql -h $PWD/build/db -d app < Application/Schema.sql psql -h $PWD/build/db -d app < Application/Fixtures.sql
```

**Comment by themmes** [comment]
Sorry, this was probably due to some rogue environment variables.

**Comment by damienxy** [comment]
@themmes, how did you fix it? I have the same issue (`createdb: could not connect to database template1: FATAL:  role "postgres" does not exist`)

**Comment by mpscholten** [comment]
Try removing the `build/db` directory (`rm -rf build/db`). After that run `./start`, does it work now?

**Comment by themmes** [comment]
@damienxy In my case it was a set of environment variables (the `reader_1` user is not something IHP uses) that made IHP look for user/db combination that did not exists. However, every postgres database should have a `postgres` user, so @mpscholten suggestion of recreating the database would be your best shot to fix this!

**Comment by damienxy** [comment]
Thanks both of you for the fast anwers! 
I deleted `build/db` and also got rid of some postgres-related env variables I had lying around. 
I had to retry a bunch of times, so I don't know if the latter was needed, but in any case it works now 🎉
