### ISSUE TITLE
mime-mail-ses version is outdated

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#532]
The `mime-mail-ses` in the pinned nixpkgs is 0.4.1, which does not authenticate with AWS correctly under some circumstances, giving a `InvalidClientTokenId` error (possibly only when there is a '+' character in the AWS_SECRET_ACCESS_KEY?)

I realise this is issue is unrelated to IHP, but it could perhaps be helpful to have a note in the documentation on how to upgrade if it poses a problem for other users.

Running this to get the latest version worked for me:

`cabal2nix cabal://mime-mail-ses-0.4.3 > Config/nix/haskell-packages/mime-mail-ses.nix`

**Comment by mpscholten** [comment]
Thanks for opening the issue on this :) Updated the mime-mail-ses version in https://github.com/digitallyinduced/ihp/pull/533 Will be part of the next IHP release 👍
