### ISSUE TITLE
Cocoa framework not found on macOS Big Sur 11.0.1

### ISSUE THREAD

**Issue by sycured** [digitallyinduced/ihp#543]
I tried to start a fresh IHP project to test it and I've an error at the first `./start`.

# To reproduce
- `ihp-new test_ihp`
- `cd test_ihp`
- `./start`

# Output
```
Success. You can now start the database server using:

    pg_ctl -D build/db/state -l logfile start

can't load framework: Cocoa (not found)
Loaded GHCi configuration from /Volumes/Macintosh HD - Case Sensitive/test_ihp/.ghci
IHP> package flags have changed, resetting and loading new packages...
can't load framework: Cocoa (not found)
IHP> [ 1 of 14] Compiling Application.Helper.Controller ( Application/Helper/Controller.hs, interpreted )
[ 2 of 14] Compiling Application.Helper.View ( Application/Helper/View.hs, interpreted )
[ 3 of 14] Compiling Config           ( Config/Config.hs, interpreted )
[ 4 of 14] Compiling Generated.Types  ( build/Generated/Types.hs, interpreted )
[ 5 of 14] Compiling Web.Types        ( Web/Types.hs, interpreted )
[ 6 of 14] Compiling Web.Routes       ( Web/Routes.hs, interpreted )
[ 7 of 14] Compiling Web.Controller.Prelude ( Web/Controller/Prelude.hs, interpreted )
[ 8 of 14] Compiling Web.View.Layout  ( Web/View/Layout.hs, interpreted )

<no location info>: error:
    <command line>: can't load framework: Cocoa (not found)
Failed, 7 modules loaded.
```

# System
![Screen Shot 2020-11-10 at 23 14 33](https://user-images.githubusercontent.com/60801403/98765214-9c160280-23ab-11eb-939e-f03810d8528d.png)

**Comment by tomadimitrie** [comment]
Same issue here. Did you find a fix?

**Comment by mpscholten** [comment]
There's currently no known fix. Will take a look this week.

**Comment by mpscholten** [comment]
Cocoa has been removed now (was not required anymore), https://github.com/digitallyinduced/ihp/pull/552

There's propably some other error coming up. I think we need to follow the steps I found in this tweet: https://twitter.com/angerman_io/status/1328901955893088257?s=21

**Comment by sycured** [comment]
A long time ago (June 28th), I opened an issue on nixpkgs and at this time, it can be more up-to-date: https://github.com/NixOS/nixpkgs/issues/91748
It can be better to use staging-next than master: https://github.com/NixOS/nixpkgs/issues/91748#issuecomment-727641022

The bad part is about the missing cache so a lot of things to build/rebuild at this time due to the lack of cache.

**Comment by tomadimitrie** [comment]
> Cocoa has been removed now (was not required anymore), #552
> 
> There's propably some other error coming up after that. I think we need to follow the steps I found in this tweet: https://twitter.com/angerman_io/status/1328901955893088257?s=21

It still gives the same error even after I reinstalled `ihp-new` on nix and recreated the project. Do I need to update something else as well?

**Comment by mpscholten** [comment]
Just got it to work with a workaround 👍 
![IMG_5503](https://user-images.githubusercontent.com/2072185/99563555-a9457980-29c9-11eb-965e-ecf73e39674a.jpg)



To avoid the `can't load framework: Cocoa (not found)` you need to run this inside your project directory:
```bash
git clone https://github.com/digitallyinduced/ihp.git IHP
```

This will clone the IHP source code into `IHP` (it's important that it's named uppercase). After that `./start` will work. It will still output a warning `Cocoa not found`, but it will then continue to compile.

**Comment by tomadimitrie** [comment]
> Just got it to work with a workaround 👍
> ![IMG_5503](https://user-images.githubusercontent.com/2072185/99563555-a9457980-29c9-11eb-965e-ecf73e39674a.jpg)
> 
> To avoid the `can't load framework: Cocoa (not found)` you need to run this inside your project directory:
> 
> ```shell
> git clone https://github.com/digitallyinduced/ihp.git IHP
> ```
> 
> This will clone the IHP source code into `IHP` (it's important that it's named uppercase). After that `./start` will work. It will still output a warning `Cocoa not found`, but it will then continue to compile.

wow, that worked, thanks! so basically if it finds a folder named IHP it will use the framework from there instead of the default installation directory?

**Comment by mpscholten** [comment]
Yes exactly. You are basically running IHP from source instead of using the normal binary version.

The interesting thing is that once we build the exact same master version to a binary, the Cocoa error comes back. I think this is related to the linker changes on macOS. Hopefully this will be fixed in nix soon.

**Comment by francisdb** [comment]
Any chance this will be released soon?

The workaround doesn't work here
```
IHP/IHP/Mail.hs:22:1: error:
    Could not find module ‘Network.Mail.SMTP’
    Perhaps you meant Network.Mail.Mime (from mime-mail-0.5.0)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

**Comment by mpscholten** [comment]
Will be released on friday. Until then you can just update to the latest master commit:
- Change commit in line 4 of `default.nix` to `943431d4dfeda5236961073e5895670b0fce2da6` (latest master commit)
- Replace your `Config/nix/nixpkgs-config.nix` with this https://github.com/digitallyinduced/ihp-boilerplate/blob/6a3f63d0628fb1ab06706776799f47b693918767/Config/nix/nixpkgs-config.nix
- Run `make clean`
- Run `nix-shell` and then `make -B .envrc`
- After that run `./start` and you should be on the latest version

**Comment by francisdb** [comment]
I think I will just wait for Friday:

```
> make clean
usage: dirname path
Makefile:22: /../lib/IHP/Makefile.dist: No such file or directory
make: *** No rule to make target `/../lib/IHP/Makefile.dist'.  Stop.
```

**Comment by mpscholten** [comment]
Ok 👍 

You can also just do `rm -rf build` instead of `make clean` :)
