### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#557]
I'd like to add some anonymous telemetry to the DevServer in IHP. This would allow us to answer questions such as:

- How many people are running at which IHP version?
- What is the primary OS people are using IHP on?
- How many active users are working with IHP?

To answers these questions I'd like to add a function that sends a simple `POST` request with a few information bits to a IHP telemetry server. The request would look like this:

```json
{
    "ihpVersion":"GIT COMMIT HASH OF IHP",
    "os": "darwin|windows|linux",
    "arch": "x86_64",
    "projectId":"SHA512($CURRENT_PROJECT_PATH)"
}
```

We would send this request as soon as the `./start` DevServer starts up.

To opt-out of this we'd offer to set a `IHP_DISABLE_TELEMETRY=1` env variable.

I got the idea for this on the [nextjs website](https://nextjs.org/telemetry). It looks like homebrew is also doing something similiar. Would love to get some input on this topic.

**Comment by mpscholten** [comment]
✅

**Comment by geofflangenderfer** [comment]
this is not good for folks working on work laptops

https://stackoverflow.com/questions/74626178/how-do-i-turn-off-ihp-telemetry

**Comment by stianlagstad** [comment]
I don't mind the default setting here at all. It's easy for me to configure my work laptop to have the proper environment variable set to turn this off (should I need to).

**Comment by mpscholten** [comment]
I've just commented a fix on your stackoverflow question https://stackoverflow.com/a/74626670/14144232

**Comment by kodeFant** [comment]
To avoid future confution: The actual variable name is `IHP_TELEMETRY_DISABLED`   and not `IHP_DISABLE_TELEMETRY`
