### ISSUE TITLE
Markdown-issue with superscript in "Your first project"?

### ISSUE THREAD

**Issue by stianlagstad** [digitallyinduced/ihp#575]
I'm going through <https://ihp.digitallyinduced.com/Guide/your-first-project.html> again and noticed this:
![Screenshot_20201129_150414](https://user-images.githubusercontent.com/4340859/100544174-356e6100-3254-11eb-9bd0-2f071cb36899.png)

Notice the "sup" and "/sup" around the sentence saying "Note that the word ‘Post’ here still refers to a post on our blog and is unrelated to the HTTP-POST request method.".

The same is not visible when looking at <https://github.com/digitallyinduced/ihp/blob/2cf0681082b2f6ad49e1f40641e15370342bda88/Guide/your-first-project.markdown>:
![Screenshot_20201129_150543](https://user-images.githubusercontent.com/4340859/100544199-62bb0f00-3254-11eb-8664-b35792ffa9d3.png)

**Comment by mpscholten** [comment]
Looks like the `<sup>` is not supported by our markdown parser. So I removed it.
