### ISSUE TITLE
List of Bad GHC Error Messages

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#587]
From our [Error Message Design Goals](https://ihp.digitallyinduced.com/Guide/design-goals.html):

> IHP error messages should be clear, actionable, and practical. A great error message tells the user what went wrong and what the user needs to do to fix the problem. It should direct the user to the solution most likely needed.

Let's keep track of all GHC Haskell Error Messages that are not helpful and write down a better alternative. In the future we maybe can help make the GHC errors a little bit better :)

**Comment by mpscholten** [comment]
Let's start with the first.

Given this code:

```haskell
action CreateUserAction = do
        let user = newRecord @User
        let password = param @Text "password"
        user
            |> set #passwordHash password
            |> fill @["email"]
            |> validateField #email isEmail
            |> validateField #passwordHash nonEmpty
            |> debug
            |> ifValid \case
            Left user ->
                render NewView {..}
            Right user -> do
                hashed <- hashPassword (get #passwordHash user)
                user
                    |> set #passwordHash hashed
                    |> createRecord

                setSuccessMessage "You have successfully registered"
```

GHC errors with:

```haskell
Web/Controller/Users.hs:16:23
    * Expected a type, but `"email"' has kind `Symbol'
    * In the type `["email"]'
      In the second argument of `(|>)', namely `fill @["email"]'
      In the first argument of `(|>)', namely
        `user |> set #passwordHash password |> fill @["email"]'
   |
16 |             |> fill @["email"]
   |                       ^^^^^^^
```

A better error message would be:

```haskell
Web/Controller/Users.hs:16:23
    * Type level lists with only a single element need a ' in front of the list. Prepend a ' like `'["email]' to get it working.
    * In the type `["email"]'
      In the second argument of `(|>)', namely `fill @["email"]'
      In the first argument of `(|>)', namely
        `user |> set #passwordHash password |> fill @["email"]'
   |
16 |             |> fill @["email"]
   |                       ^^^^^^^
```

**Comment by mpscholten** [comment]
Given this code:

```haskell
    action NewEventAction = do
        now <- getCurrentTime
        let event = newRecord @Event
            |> set #createdAt now -- THIS LINE NEEDS MORE INDENTATION
        render NewView { .. }
```

GHC errors with:

```haskell
Admin/Controller/Events.hs:26:9: error:
    The last statement in a 'do' block must be an expression
      let event = newRecord @Event
   |
26 |         let event = newRecord @Event
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

A better error message would be:

```haskell
Admin/Controller/Events.hs:26:9: error:
    The let-expression is only indented 4 spaces from the do-statement, but it needs to be indented 8 spaces
      '|> set #createdAt now'
   |
26 |         let event = newRecord @Event
27 |             |> set #createdAt now
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by mpscholten** [comment]
Given this code:
```haskell
fetchCategories :: (?modelContext :: ModelContext) => IO ()
fetchCategories = do
  categories :: [Category] <- query @Category |> fetch
  putContext categories
```

GHC errors with:
```haskell
Web/FrontController.hs:18:3: error:
    * Could not deduce: ?context::ControllerContext
        arising from a use of `putContext'
      from the context: ?modelContext::ModelContext
        bound by the type signature for:
                   fetchCategories :: (?modelContext::ModelContext) => IO ()
        at Web/FrontController.hs:15:1-59
    * In a stmt of a 'do' block: putContext categories
      In the expression:
        do categories :: [Category] <- query @Category |> fetch
           putContext categories
      In an equation for `fetchCategories':
          fetchCategories
            = do categories :: [Category] <- query @Category |> fetch
                 putContext categories
   |
18 |   putContext categories
```

A better error message would be:

```haskell
Web/FrontController.hs:18:3: error:
    * The call to `putContext` requires an implicit parameter `?context::ControllerContext` to be available. Change the type signature to this: fetchCategories :: (?modelContext::ModelContext, ?context :: ControllerContext) => IO ()
        at Web/FrontController.hs:15:1-59
    * In a stmt of a 'do' block: putContext categories
      In the expression:
        do categories :: [Category] <- query @Category |> fetch
           putContext categories
      In an equation for `fetchCategories':
          fetchCategories
            = do categories :: [Category] <- query @Category |> fetch
                 putContext categories
   |
18 |   putContext categories
```

**Comment by tomjaguarpaw** [comment]
Great initiative! This is the kind of thing I'm trying to keep track of in my project [tilapia](https://github.com/tomjaguarpaw/tilapia). If you want to use the [tilapia issue tracker](https://github.com/tomjaguarpaw/tilapia/issues/new) as a central place to store and discuss these issues the please feel free.

**Comment by ShalokShalom** [comment]
Why is this closed? Is there no bad error message in GHC anymore?

**Comment by goldfirere** [comment]
For what it's worth, I'm very much in favor of a `ux` repo or other place specifically to track UX improvements. I know I've been a little negative on GHC's GitLab instance toward @mpscholten, because some of these suggestions will be hard to implement. I hope this isn't discouraging! We need these concrete examples. Hopefully, some will be easy, and perhaps collecting many examples will reveal patterns that we can take advantage of to amortize the implementation costs.

I'm hoping that once @haskellfoundation has found its feet (that is, has a permanent board and an executive director), it will be in a good position to push this all forward, with all of our help. This should happen by the end of January or so. If I lose sight of this in the meantime, please feel free to ping me then about setting up an "official" repo to collect UX complaints.

**Comment by ShalokShalom** [comment]
You can also look to Eta. They have already implemented quite a couple of new error messages, although their project is currently unmaintained. 

https://mobile.twitter.com/jyothsnasrin/status/1037703436043603968

**Comment by mpscholten** [comment]
> Why is this closed? Is there no bad error message in GHC anymore?

Closed this as all the current issues have been reported to the GHC issue tracker. My opinion until now have been that all future issues should be directly be reported to GHC GitLab. That way we can get direct input from the people working on GHC itself. I did add a few sentences on that process to our documentation via https://github.com/digitallyinduced/ihp/pull/614/files :)


> For what it's worth, I'm very much in favor of a ux repo or other place specifically to track UX improvements. I know I've been a little negative on GHC's GitLab instance toward @mpscholten, because some of these suggestions will be hard to implement. I hope this isn't discouraging! We need these concrete examples. Hopefully, some will be easy, and perhaps collecting many examples will reveal patterns that we can take advantage of to amortize the implementation costs.

I think it's actually quite easy to add issues directly to the GHC issue tracker, but I guess many people are not aware of this (I wasn't aware myself until it was suggested on reddit). So maybe we can have this central UX repo here on GitHub, this way people can contribute with their existing github account :)

Happy to help move this forward. I could create a repo at `digitallyinduced/haskell-ux`. We could later move that to the haskellfoundation if there's interest, just want to get things going.

I could also help push this in the haskellfoundation. Is there a process on how to contribute to the foundation or how decisions like making a haskell-ux repo are made?

**Comment by mpscholten** [comment]
There's https://github.com/digitallyinduced/haskell-ux now :)

**Comment by goldfirere** [comment]
> I could also help push this in the haskellfoundation. Is there a process on how to contribute to the foundation or how decisions like making a haskell-ux repo are made?

The official communications medium of the Haskell Foundation is the Haskell Foundation category at https://discourse.haskell.org/. This space is open for all to contribute to. But, I should say that the current status of the HF is a bit in limbo: there is an interim board whose sole job is to appoint a permanent board and a first executive director (ED). That permanent board (well, people will rotate on and off, so don't read "permanent" too seriously) will work with the ED to move things forward. This should start happening at the end of January/beginning of February.

There is not currently an "RFC" process, by which you could propose the UX repo. I hope there will be, and will personally push to make it so once we get out of the interim period. The best you can do right now is post on that Discourse, but please be patient if not much happens very quickly.

Somewhat separately, I do think there are good reasons to have a UX repo separate from the main bug tracker. (There are also reasons against, to be sure.) A UX repo could be more explicitly welcoming to newcomers, and it would allow for a space for UX experimentation and brainstorming. Once a UX decision is made there (or, at least, a solid direction to pursue), then a proposal and/or ticket can be made in the main GHC repo. I think that concentrating the UX conversation may produce results that would be harder to achieve in the main bug tracker. On the other hand, a separate repo means more "stuff" and could introduce a failure mode of converging on something that is impossible to implement. It's not obvious to me what's best here, but my inclination is that a separate repo would work better.

**Comment by ShalokShalom** [comment]
You could also look into [Eta](eta-lang.org) to see how they [improve compiler messages](https://mobile.twitter.com/jyothsnasrin/status/1037703436043603968) in Haskell.

**Comment by unhammer** [comment]
https://discourse.haskell.org/t/proposal-an-issue-tracker-for-better-error-messages/2498

**Comment by mpscholten** [comment]
@unhammer thx for sharing! :) This is fantastic.

Also thanks @goldfirere for pushing this topic 💯
