### ISSUE TITLE
Codegen error on JSONB

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#594]
Create a table with a JSONB type field and generate its controller

-- Your database schema. Use the Schema Designer at http://localhost:8001/ to add some tables.
CREATE TABLE jsontests (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    jsonfield JSONB NOT NULL
);

[ 9 of 18] Compiling Web.View.Prelude ( Web/View/Prelude.hs, interpreted ) [Web.Routes changed]
[10 of 18] Compiling Web.View.Jsontests.Show ( Web/View/Jsontests/Show.hs, interpreted )
[11 of 18] Compiling Web.View.Jsontests.New ( Web/View/Jsontests/New.hs, interpreted )

Web/View/Jsontests/New.hs:19:45: error:
    • Could not deduce (InputValue
                          aeson-1.5.2.0:Data.Aeson.Types.Internal.Value)
        arising from a use of ‘textField’
      from the context: ?context::ControllerContext
        bound by the type signature for:
                   renderForm :: Jsontest -> Html
        at Web/View/Jsontests/New.hs:(19,1)-(22,2)
      or from: (?context::ControllerContext,
                ?formContext::FormContext Jsontest)
        bound by a type expected by the context:
                   (?context::ControllerContext,
                    ?formContext::FormContext Jsontest) =>
                   Text.Blaze.Html.Html
        at Web/View/Jsontests/New.hs:(19,40)-(22,2)
    • In the first argument of ‘toHtml’, namely
        ‘(textField (fromLabel @"jsonfield"))’
      In the expression: toHtml (textField (fromLabel @"jsonfield"))
      In the third argument of ‘Data.MonoTraversable.Unprefixed.foldl'’, namely
        ‘[toHtml (textField (fromLabel @"jsonfield")),
          toHtml submitButton]’
   |
19 | renderForm jsontest = formFor jsontest [hsx|
   |                                             ^...
[12 of 18] Compiling Web.View.Jsontests.Index ( Web/View/Jsontests/Index.hs, interpreted )
[13 of 18] Compiling Web.View.Jsontests.Edit ( Web/View/Jsontests/Edit.hs, interpreted )

**Comment by mpscholten** [comment]
Fixed this via https://github.com/digitallyinduced/ihp/pull/602 will be part of the upcoming release :)

**Comment by Kaeptenblaubaer** [comment]
Next error is:
```
[16 of 18] Compiling Web.Controller.Jsontests ( Web/Controller/Jsontests.hs, interpreted )

Web/Controller/Jsontests.hs:29:16: error:
    • Could not deduce (ParamReader Value)
        arising from a use of ‘buildJsontest’
      from the context: (?context::ControllerContext,
                         ?modelContext::ModelContext, ?theAction::JsontestsController)
        bound by the type signature for:
                   action :: (?context::ControllerContext,
                              ?modelContext::ModelContext, ?theAction::JsontestsController) =>
                             JsontestsController -> IO ()
        at Web/Controller/Jsontests.hs:10:5-10
    • In the second argument of ‘(|>)’, namely ‘buildJsontest’
      In the first argument of ‘(|>)’, namely ‘jsontest |> buildJsontest’
      In a stmt of a 'do' block:
        jsontest |> buildJsontest
          |>
            ifValid
              \case
                Left jsontest -> render EditView {..}
                Right jsontest
                  -> do jsontest <- jsontest |> updateRecord
                        setSuccessMessage "Jsontest updated"
                        ....
   |
29 |             |> buildJsontest
   |                ^^^^^^^^^^^^^
Failed, 15 modules loaded.
```
