### ISSUE TITLE
Update Nixpkgs Version

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#606]
- Update Haskell Language Server from v0.4 to v0.6. v0.6 has hlint support which is nice :) 
- Fixes an issue with imagemagick
- Fixes https://github.com/digitallyinduced/ihp/issues/543 when we upgrade to GHC 8.10.3

**Comment by s0kil** [comment]
@mpscholten Does this also update GHC version?

**Comment by mpscholten** [comment]
Not by default, but we could do that

**Comment by mpscholten** [comment]
Currently there seems to be no nix package available on latest nixpkgs for GHC8.10.3 which we need to fix macOS support. I've found [this patch](https://cardanoupdates.com/commits/ef78c386431f601b567aae772f24d57e5cab31ce) by IOHK which adds ghc8103 to their custom haskell.nix infrastructure. Maybe we can use that to add GHC8.10.3 to nixpkgs upstream.
