### ISSUE TITLE
Support Custom Services in the Dev Server

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#613]
We should add a way to start custom scripts when the dev server starts. Additionally it would be cool to also run a script automatically when a certain file changes.

Currently we have multiple use cases:
- When using IHP with tailwind you want to run `./start` and `make tailwind-dev`.
- When using e.g. stripe locally you want to run `./start` and `stripe listen --forward-to localhost:8000/StripeWebhook`
- When using IHP with Elm you want to run `nix-shell --run './Application/Script/GenerateElmTypes.hs'` when `Application/Schema.sql` changes

Possible solution: Have a directory `Config/CustomDevTools`. There we could place e.g. a dhall file like this:

`Config/CustomDevTools/tailwind.dhall`:
```dhall
{
    onStart: "make tailwind-dev"
}
```

We could also allow file watchers like this:

`Config/CustomDevTools/tailwind.dhall`:
```dhall
{
    onFileChange: {
        pattern: "tailwind/*.css"
        run: "make tailwind-dev"
    }
}
```

For elm:

`Config/CustomDevTools/elm.dhall`:
```dhall
{
    onStart: "./Application/Script/GenerateElmTypes.hs"
    onFileChange: {
        pattern: "build/Generated/Types.hs"
        run: "./Application/Script/GenerateElmTypes.hs"
    }
}
```

For stripe:

`Config/CustomDevTools/stripe.dhall`:
```dhall
{
    onStart: "stripe listen --forward-to localhost:8000/StripeWebhook"
}
```

**Comment by jeyj0** [comment]
Elm preset should also be changed to use this then, right now the `start` script is customized to start parcel alongside the normal server, but this would allow a better way of doing this.

**Comment by jeyj0** [comment]
This should also be available to plugins, as that would get us one step closer to refactoring the presets into plugins

**Comment by mpscholten** [comment]
This can be done via devenv.sh processes now 👍
