### ISSUE TITLE
Add pagination to ShowTableRows

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#624]
After loading ~30k records into one of my tables, I went to explore things in the IHP IDE and was greeted by quite a long loading time! It would be great if the database view would paginate, preferably in a configurable way (i.e. show 50, 100, all), to eliminate the heavy loading times for large tables.

Would be happy to take a shot at this myself once I can get development on Big Sur working!

**Comment by mpscholten** [comment]
Good suggestion 👍  cc @nezbite

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/pull/714
