### ISSUE TITLE
Calling createMany with an empty list results in a SQL error

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#627]
By calling `createMany ([] :: [<insert model type>])`, the following exception is thrown:

```
*** Exception: SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"RETURNING\"", sqlErrorDetail = "", sqlErrorHint = ""}
```

It makes sense that `createMany []` should fail, but perhaps this should be checked by the function so it can fail with a better error message.

**Comment by fegu** [comment]
createMany [] should return ok. No work to do -> no work done, no problem. I have added a commit in my PR #625  to fix this.
