### ISSUE TITLE
Syntax error when creating an object with text field containing quotes

### ISSUE THREAD

**Issue by k-bx** [digitallyinduced/ihp#642]
I'm trying to add a record putting this text into a field's value:

```
In 1973, a young filmmaker named George Lucas scribbled some notes for a far-fetched space-fantasy epic. Some forty years and 37 billion later, Star Wars -- related products outnumber human beings, a growing stormtrooper army spans the globe, and "Jediism" has become a religion in its own right. Lucas's creation has grown into far more than a cinematic classic; it is, quite simply, one of the most lucrative, influential, and interactive franchises of all time. Yet incredibly, until now the complete history of Star Wars -- its influences and impact, the controversies it has spawned, its financial growth and long-term prospects -- has never been told.
```

Getting an error:

```
SqlError {sqlState = "42601", sqlExecStatus = FatalError, sqlErrorMsg = "syntax error at or near \"s\"", sqlErrorDetail = "", sqlErrorHint = ""}
```

Looks like some kind of escaping problem. Would be great if IHP would print the full SQL upon error if possible.

**Comment by mpscholten** [comment]
Thanks for reporting! :) Do you do this via the Database Editor in the dev tools?

**Comment by k-bx** [comment]
Ok, this might be a different one (I'll try to reproduce the one with `near \"s\"` later). The error happens when you have a schema with nullable UUID field, and you try to edit a row, IHP will by default show you a text field input with an empty string as the value.

What should happen (ideally): you shouldn't be allowed to input an empty string in that field, asked to provide a valid UUID value.

Alternatively: IHP should put NULL into that field if it's nullable.

What happens now: `SqlError {sqlState = "22P02", sqlExecStatus = FatalError, sqlErrorMsg = "invalid input syntax for type uuid: \"\"", sqlErrorDetail = "", sqlErrorHint = ""}`

**Comment by k-bx** [comment]
Yeah, seems like there's a potential for an SQL injection. When you're using single-quotes in your text field, it'd make a query like this (printed via `Prelude.print`):

```
"INSERT INTO books VALUES (uuid_generate_v4(),'ouhouh','',NULL,NULL,'In 1973, a young filmmaker named George Lucas scribbled some notes for a far-fetched space-fantasy epic. Some forty years and 37 billion later, Star Wars -- related products outnumber human beings, a growing stormtrooper army spans the globe, and \"Jediism\" has become a religion in its own right. Lucas's creation has grown into far more than a cinematic classic; it is, quite simply, one of the most lucrative, influential, and interactive franchises of all time. Yet incredibly, until now the complete history of Star Wars -- its influences and impact, the controversies it has spawned, its financial growth and long-term prospects -- has never been told.',NULL,false,'now()','now()')"
```

Obviously, `'` should be escaped. I'll see if I can fix this one (more trivial than the previous one for me atm).
