### ISSUE TITLE
REPL button does nothing

### ISSUE THREAD

**Issue by francisdb** [digitallyinduced/ihp#676]
Nothing happens when I click the REPL button in the web editor

`("ihpVersion","0.8.0"),("os","darwin"),("arch","x86_64")`

**Comment by s0kil** [comment]
Right now the [REPL](https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/ToolServer/Layout.hs#L75) and [LINT](https://github.com/digitallyinduced/ihp/blob/master/IHP/IDE/ToolServer/Layout.hs#L78) buttons are placeholders reserved for the future

**Comment by francisdb** [comment]
I would expect these buttons to be greyed out or to get some kind of page showing a message or notification that those are placeholders.

**Comment by s0kil** [comment]
We could add a "feature coming soon" page.
