### ISSUE TITLE
ihp-new not in path on OSX during "Getting Started"

### ISSUE THREAD

**Issue by ijcd** [digitallyinduced/ihp#685]
Hi,

New to ihp -- trying out the "Getting Started" steps on OSX. I'm not sure yet if this is a documentation shortfall or if my setup when awry but `ihp-new` is not in path yet. This was a "from nothing" install on OSX.

1. Installed Nix using the `sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
` method
2. Ran the `nix-env -f https://ihp.digitallyinduced.com/ihp-new.tar.gz -i ihp-new
` command
3. Opened a new terminal.

This is probably just nix noob stuff but maybe there is a path setup missing.

I get this:

```
... [elided] ...
copying path '/nix/store/q6la7x65vy350bawxkxmnhcvi0vhqmyh-clang-wrapper-7.1.0' from 'https://cache.nixos.org'...
copying path '/nix/store/wh1phjwpgmc5cv0prrgprxhrgw6v09c6-stdenv-darwin' from 'https://cache.nixos.org'...
building '/nix/store/nzmdrrnalirl5q91hd5kfsw79b3fgaq4-ihp-new.drv'...
unpacking sources
unpacking source archive /nix/store/asza31p01pdhg33ngp8as38bkgxjqwmr-3bvm2r688i9i6wa610q6l3lw1i2zxdc6-ihp-new.tar.gz
source root is 3bvm2r688i9i6wa610q6l3lw1i2zxdc6-ihp-new.tar.gz
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
strip is /nix/store/ynbk6s6nqmrvv17snwydkfn64h81r4yv-cctools-binutils-darwin-949.0.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/j7wqsjyfdcmy0qsaripr82hr5ji4jyvn-ihp-new/bin
strip: can't process non-object and non-archive file: /nix/store/j7wqsjyfdcmy0qsaripr82hr5ji4jyvn-ihp-new/bin/ihp-new
patching script interpreter paths in /nix/store/j7wqsjyfdcmy0qsaripr82hr5ji4jyvn-ihp-new
/nix/store/j7wqsjyfdcmy0qsaripr82hr5ji4jyvn-ihp-new/ihp-new: interpreter directive changed from "/bin/bash -e" to "/nix/store/qjxzxvxf0fgsw1i50wsa6ymbj7n37591-bash-4.4-p23/bin/bash -e"
building '/nix/store/a8qw6vyw21my55vjb64fzjmxjizq8y24-user-environment.drv'...
created 23 symlinks in user environment
nix-env -f https://ihp.digitallyinduced.com/ihp-new.tar.gz -i ihp-new  17.53s user 4.63s system 57% cpu 38.498 total


% lhp-new blog
zsh: command not found: lhp-new

% which lhp-new
lhp-new not found
```

**Comment by s0kil** [comment]
@ijcd Add `. $HOME/.nix-profile/etc/profile.d/nix.sh` to your `.zshrc` file.
Looks related to https://github.com/NixOS/nix/issues/1577

**Comment by ijcd** [comment]
Thanks, that appears to be it.

Here is a proposed update to the docs.

https://github.com/digitallyinduced/ihp/pull/686

**Comment by s0kil** [comment]
Aslo related to https://github.com/digitallyinduced/ihp/issues/260

**Comment by ijcd** [comment]
Something I ran fixed my shell but I'm not sure what. This is now in `zshenv`:

```
if [ -e /Users/ijcd/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/ijcd/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
```

Nothing asked to update my dotfiles (and they are quite custom) so not happy this found its way in there without a prompt of some sort -- it does appear to have happened today.

**Comment by s0kil** [comment]
@ijcd Maybe it was simply that you restarted your terminal and then `~/.nix-profile/etc/profile.d/nix.sh` loaded?
