### ISSUE TITLE
Auto troubleshoot script should verify files

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#689]
The IHP autotroubleshoot script should check what files are different from their versions in https://github.com/digitallyinduced/ihp-boilerplate

**Comment by s0kil** [comment]
MD5 checksum seem the way to go. Maybe something like, the troubleshooting script will itself clone `ihp-boilerplate` into /tmp and generate checksum for every file, then compare the those checksums to the files in the current project.

**Comment by s0kil** [comment]
Maybe this is a better way:
GitHub API already has git hashes calculated in their api: `https://api.github.com/repos/digitallyinduced/ihp-boilerplate/contents/`
Now we can run `git hash-object file_name` and compare the hash.
