### ISSUE TITLE
Using a pure shell, default.nix does not contain all necessary dependencies to run IHP

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#690]
I'm working on deploying IHP on a NixOS server. I created a systemd service with the following configuration:

```nix
systemd.services.attics = {
    description = "Attics IHP Web Server";
    enable = true;
    after = [ "network.target" "postgresql.service" ];
    wantedBy = [ "multi-user.target" ];
    environment = {
      DATABASE_URL = "***";
      NIX_PATH = "/root/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels";
    };
    path = [ pkgs.nix pkgs.which ];
    serviceConfig = {
      Type = "simple";
      Restart = "always";
      User = "root";
      WorkingDirectory = /root/Attics/web;
      ExecStart = ''
        ${pkgs.nix}/bin/nix-shell \
          --run "/root/Attics/web/build/bin/RunProdServer" \
          /root/Attics/web/default.nix
      '';
    };
  };
```

There's a couple of hacks here I needed to get this to work due to systemd running in a pure nix-shell.
I would be happy to work on these suggestions, but since I am new to nix it would be great to get some feedback on these ideas first!

## Remove dependency on NIX_PATH

I needed to manually specify the `NIX_PATH` environment variable or else I get the error

```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

It appears the IHP nix build requires a set `NIX_PKGS` due to [this line here](https://github.com/digitallyinduced/ihp/blob/master/NixSupport/make-nixpkgs-from-options.nix#L73).

Instead of importing nixpkgs inline as is currently done, we could include pkgs as an optional argument to the function and allow users to pass through `pkgs` in their `default.nix` to allow for pinning nixpkgs, which is described as best practice [in this article](https://nix.dev/tutorials/towards-reproducibility-pinning-nixpkgs.html#pinning-nixpkgs).

## Implicit dependency on `which`

Without including ` pkgs.which` in the service path, `RunProdServer` fails with the error
```
/bin/sh: which: command not found
dirname: missing operand
Try 'dirname --help' for more information.
RunProdServer: readCreateProcess: dirname $(which RunDevServer) (exit 1): failed
```

This dependency should be explicitly included in IHP's nix configuration.

**Comment by zacwood9** [comment]
Update regarding the dependency on `which`: by running `nix-shell --run 'make build/ihp-lib` followed by `nix-shell --run 'make build/bin/RunUnoptimizedProdServer` I was able to fix this without manually specifying `which`.

**Comment by zacwood9** [comment]
Another strange error: after making unrelated changes to my NixOS config and rebuilding my profile, my service started failing with
```
nix-shell[26119]: error: executing 'git': No such file or directory
```
After trying to add the git package to the nix-shell command, now it fails with
```
/nix/store/0pc86gb8hmppj29k454sy75xkggpi4v1-default.nix: line 1: let: expression expected
```

The contents of the file are the same as the default IHP config
```nix
let
    ihp = builtins.fetchGit {
        url = "https://github.com/digitallyinduced/haskellframework.git";
        ref = "refs/tags/v0.8.0";
    };
    haskellEnv = import "${ihp}/NixSupport/default.nix" {
        ihp = ihp;
        haskellDeps = p: with p; [
            cabal-install
            base
            wai
            text
            hlint
            p.ihp
        ];
        otherDeps = p: with p; [
            # Native dependencies, e.g. imagemagick
        ];
        projectPath = ./.;
    };
in
    haskellEnv
```

Trying to figure out what the root cause of all of this is. The worrisome part is how it just started failing after editing my nginx config: definitely want to get that sorted out before I deploy to production.

**Comment by mpscholten** [comment]
This issue is mostly outdated so closing this :) Docs for deploying with nix can be found here https://ihp.digitallyinduced.com/Guide/deployment.html#building-with-nix
