### ISSUE TITLE
Buggy space stripping in HSX

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#699]
HSX:
```html
   <td>{get #question card} → {get #answer card}</td>
```

Output:
```
foo→ bar
```

**Comment by Profpatsch** [comment]
Another example which is probably related:

hsx:
```
a<span> foo bar </span>b
```

result:

```
afoo barb
```

outer spaces inside the span are stripped

**Comment by mpscholten** [comment]
> outer spaces inside the span are stripped

This behavior might not be fixed easily (might require reworking the whole space handling). So I'd consider this a known limitation for now :)
