### ISSUE TITLE
Proposal: IHP.Log, a unified logging solution for IHP apps

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#716]
# Introduction

This proposal introduces the `IHP.Log` module, a set of logging functions built on top of [fast-logger](https://hackage.haskell.org/package/fast-logger). Ideally, this would be the only way the framework logs information during its execution, allowing the user complete control over the format of logs, logging levels, and log destination.

## Logging in IHP today

Currently, IHP logs information about its execution through a variety of means.
- Database queries are logged in development mode only through the [`logQuery` function](https://github.com/digitallyinduced/ihp/blob/master/IHP/ModelSupport.hs#L355). This logs the query and its parameters through `putStrLn` to standard out.
- Requests are logged through `wai-extra` middleware, with defaults defined in [IHP configuration](https://github.com/digitallyinduced/ihp/blob/master/IHP/FrameworkConfig.hs#L94). By default this is logged to standard out but can also be directed to a file.
-  Exceptions during  the request cycle are [logged to standard error](https://github.com/digitallyinduced/ihp/blob/master/IHP/ErrorController.hs#L103).
- Logs in user application can be done through any means: `putStrLn`, or a custom logging framework.

## What's missing?

In order to collect and analyze logs in production applications, a common flow in other frameworks is to log into files that are collected and uploaded to external services. With current IHP logging, users would have to redirect stdin/stdout to a file to store logs. This solution makes rotating log files much harder and error prone.

Also, current IHP logging has no concept of log levels, a common idea in logging libraries. With log levels, users can specify what level of logs they would like output (i.e. in development all logs, in production just warnings and errors). This allows for logging flexibility -- for example, if a user would like to log query execution time in production to debug bad query performance, this would not be possible the built in IHP logging.

## Proposal: IHP.Log

I propose adding a module to the framework, `IHP.Log`, that provides functions to configure the application logger as well as functions to log at different log levels. By building on top of a battle-tested library such as `fast-logger`, we can inherit a lot of great features such as:
- automatic log rotating
- great performance, especially in multi-threaded environments
- extensive configuration options
- log formatting

I imagine the logging configuration be stored in `FrameworkConfig` and be configured in `Config.hs`.

```haskell
config :: ConfigBuilder
config = 
  ...
  option Production
  option $ LogFileTimedRotate "Log/production.log" rotateDaily
  option $ LogDateFormat "some time format string"
  option $ LogLevel Warning -- log warnings and greater
  -- or maybe condense into one LogConfiguration record
```

This could then be used anywhere in an IHP application, such as in a controller action

```haskell
 action CreatePostAction = do
        let post = newRecord @Post
        Log.debug "creating new post"
        post
            |> buildPost
            |> ifValid \case
                Left post -> do
                    Log.error "failed to build post"
                    render NewView { .. }
                Right post -> do
                    post <- post |> createRecord
                    Log.info "created new post"
                    setSuccessMessage "Post created"
                    redirectTo PostsAction
```

These logging functions would also be added in place of the uses of `putStrLn` in places such as query, request, and exception logging. This way, there will be one centralized way to customize logging behavior of the framework and applications.

## Conclusion

Logging is an essential part of maintaining any production system, and even with applications built with other web frameworks, it's easy to get wrong. In the spirit of IHP, the design of IHP logging should make things easy to get right. Along with the benefits of Haskell that IHP brings, a built-in logging solution will help make both developing and running IHP apps in production a great, reliable experience worth sharing.

# Feedback

Please give any feedback on what you think of the proposal and problems or other suggestions you have with it! I'd love to work on something like this as it would be a great help for my own production application. Since it's such a substantial addition though it deserves serious design consideration and discussion. Looking forward to the discussion :)

**Comment by mpscholten** [comment]
Great proposal  👍  Thanks!

We're always using systemd which automatically deals with the log management for this kind of stuff. Any reasons you're not 
 using a similiar solution like systemd for this?

Should the default logging behavior be standard/error output or file output?

**Comment by zacwood9** [comment]
To be honest, I was not aware of how many features are built into systemd logging! that should work for most of my humble use cases :)

However, I still think the idea of an IHP logging module is worth considering. Log levels are useful for filtering message based on environment, for example providing options for logging simplified database queries with performance metrics. This would have to be done manually now since all query logging is turned off in production.

Default should be stdout/stderr. I'd imagine the default output would look similar to today, except with more options available to the user to be able to extend, format, and specify logs they'd like to see.

**Comment by mpscholten** [comment]
👍 merged
