### ISSUE TITLE
RunDevServer not starting postgres server

### ISSUE THREAD

**Issue by NiekPas** [digitallyinduced/ihp#719]
I'm following the IHP Guide.

After successfully starting the dev server by running `./start`, everything seems to be working. However, when I attempt to commit a new table to postgres by clicking the `update DB` button, I get the following error:

```
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/.s.PGSQL.5432"?
make: *** [/nix/store/map2i1pdw1c30xlqh7y429kqa3rcbk2h-ghc-8.10.3-with-packages/bin/../lib/IHP/Makefile.dist:112: db] Error 2
echo "drop schema public cascade; create schema public;" | psql -h $PWD/build/db -d app
psql -h $PWD/build/db -d app < "/nix/store/map2i1pdw1c30xlqh7y429kqa3rcbk2h-ghc-8.10.3-with-packages/bin/../lib/IHP/IHPSchema.sql"
psql -h $PWD/build/db -d app < Application/Schema.sql
psql -h $PWD/build/db -d app < Application/Fixtures.sql
```

Some inspection confirms that there is no unix socket file at `/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/.s.PGSQL.5432`, so my guess is that the postgres server does not get started successfully. There is nothing about this in the stdout of `start`, however.

I am on macOS 11.1 Big Sur, if that helps.

Contents of `Application/Schema.sql`:

```
-- Your database schema. Use the Schema Designer at http://localhost:8001/ to add some tables.
CREATE TABLE posts (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL
);
```

**Comment by s0kil** [comment]
@NiekPas Could you please paste the output of running `curl --silent https://raw.githubusercontent.com/digitallyinduced/ihp/master/Troubleshoot/ihp-troubleshoot | python3` inside the project directory?

**Comment by NiekPas** [comment]
Here is the output:

```
Checking that the current directory is an IHP project:
+ Found Main.hs
+ Found start script
+ Nix installed
Checking direnv:
+ Found .envrc
+ direnv loads .envrc
+ direnv allows .envrc
+ ghci is loaded from nix store
Checking .ghci:
+ Found .ghci
+ .ghci permissions are ok
Checking IHP:
+ Symlink build/ihp-lib exists
+ Symlink build/ihp-lib target exists
+ IHP used from nix
Checking Cachix:
+ Cachix exists
+ digitallyinduced.cachix.org configured
+ No legacy cachix key found
Checking IHP files:
Debugging Details:
GHCI Output:
GHCi, version 8.10.3: https://www.haskell.org/ghc/  :? for help
package flags have changed, resetting and loading new packages...
Loaded GHCi configuration from /Users/niekvandepas/Documents/code/haskell-practice/blog/.ghci
IHP> ok
IHP> Leaving GHCi.

build/ihp-lib Target:
/nix/store/map2i1pdw1c30xlqh7y429kqa3rcbk2h-ghc-8.10.3-with-packages/bin/../lib/IHP
Direnv Output:
direnv exec path /Users/niekvandepas/.nix-profile/bin/direnv
DIRENV_CONFIG /Users/niekvandepas/.config/direnv
bash_path /nix/store/fb2pkc446jgwxn98hgabhsjkj7scb57y-bash-4.4-p23/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /Users/niekvandepas/Documents/code/haskell-practice/blog/.envrc
Loaded watch: ".envrc" - 2021-01-26T22:22:39+01:00
Loaded watch: "../../../../.local/share/direnv/allow/f8e67865bbc417964d24ac945cd5668824d3a548a5d3e02b7955cbf3d2532519" - 2021-01-27T20:00:12+01:00
Loaded RC allowed false
Loaded RC allowPath
Found RC path /Users/niekvandepas/Documents/code/haskell-practice/blog/.envrc
Found watch: ".envrc" - 2021-01-26T22:22:39+01:00
Found watch: "../../../../.local/share/direnv/allow/f8e67865bbc417964d24ac945cd5668824d3a548a5d3e02b7955cbf3d2532519" - 2021-01-27T20:00:12+01:00
Found RC allowed true
Found RC allowPath /Users/niekvandepas/.local/share/direnv/allow/f8e67865bbc417964d24ac945cd5668824d3a548a5d3e02b7955cbf3d2532519

which direnv Output:
/nix/store/map2i1pdw1c30xlqh7y429kqa3rcbk2h-ghc-8.10.3-with-packages/bin/ghci

default.nix:
let
    ihp = builtins.fetchGit {
        url = "https://github.com/digitallyinduced/ihp.git";
        ref = "refs/tags/v0.8.0";
    };

OS:
macOS-11.1-x86_64-i386-64bit
```

**Comment by mpscholten** [comment]
Output looks good to me. Can you run `DEBUG=1 ./start` and paste the output?

**Comment by NiekPas** [comment]
Output here: https://gist.github.com/NiekPas/dcfb8f6f859fbb5ca29ede2e241f9a4b

**Comment by mpscholten** [comment]
Looks fine as well.

Can you manually start the postgres server by running `postgres -D build/db/state -k $PWD/build/db -c "listen_addresses="` and again provide the output of that command?

**Comment by NiekPas** [comment]
Ah, I think I've found it. Got the following output:

```
2021-01-28 08:53:46.305 CET [32310] FATAL:  data directory "/Users/niekvandepas/Documents/code/haskell-practice/blog/build/db/state" has invalid permissions
2021-01-28 08:53:46.305 CET [32310] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
```

`chmod 0700 build/db/state` seems to have fixed it (I'm still getting `psql: FATAL: database "app" does not exist`, but that's a different issue and should be easy to fix).

Not sure what caused the permissions to be wonky — I definitely didn't do anything to change them myself.

**Comment by NiekPas** [comment]
Okay, looks like I spoke a bit too soon 😅. Every time I re-run `./start`, the permissions problem pops up again. So effectively I have to run `chmod 0700 build/db/state && ./start` every time in order to get it working. Perhaps there is some bug in IHP that incorrectly sets the permissions on the `db` directory on server startup? I'm not super familiar with Haskell so I don't think I can be of much help in debugging, sorry.

**Comment by mpscholten** [comment]
That's very strange. There's no code that sets any permissions on that folder. Can you try to do a new clean build by removing the whole `build` directory and running `./start` again?

Maybe you can also try generating another project like `ihp-new other-proj` and see whether that then works?

**Comment by mpscholten** [comment]
After a few minutes of think I think a possible workaround might also be that we detect this permission problem in our [Postgres Process Manager](https://github.com/digitallyinduced/ihp/blob/master/IDE/IHP/IDE/Postgres.hs) and then automatically run the requires chmod command for these kind of errors.

We already have special case handling for other postgres errors in there.

**Comment by NiekPas** [comment]
The plot thickens!

After `rm`ing the `build` directory, everything works fine and the DB updates successfully. Once. When I kill the dev server and run `./start` again, however, the same problem pops up again.

The same thing happens when I create a new project. First run is successful, but killing and restarting the server means I have to `chmod` again.

**Comment by mpscholten** [comment]
Can you do another iteration of this with `DEBUG=1 ./start`? Maybe there's something inside the log output on the first run

**Comment by NiekPas** [comment]
Okay so somehow, the issue has consistently disappeared now, in both the old and new projects. I didn't restart my computer or reinstall/redo anything, so I have no idea what changed (or if it will come back).

I've still provided the output below.

First run: https://gist.github.com/NiekPas/132c5be7d111f54bfb9c22af5c59eda5

Second run: https://gist.github.com/NiekPas/26d121b2ff8c945c195ce56b95f68f52

**Comment by mpscholten** [comment]
Closing this as the issue has likely resolved itself :)
