### ISSUE TITLE
libpq: failed (FATAL: sorry, too many clients already )

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#726]
This is the error message received during development and using autoRefresh.

**Comment by mpscholten** [comment]
Looks like it's related to the internal issue https://linear.app/digitally-induced/issue/CLOUD-36/fix-libpq-failed-fatal-sorry-too-many-clients-already There's also a few steps to reproduce the issue in that ticket.

**Comment by s0kil** [comment]
It seems that the `DevServer` does not clean up connections, since looking at the system resources monitor there are close to 80/90 Postgres processes that are idle, and another 10 or so that are unique. The default connection limit in Postgres is 100, so that is when the error message shows up.

This can be reproduced by making a change, waiting half a second and making a change again to trigger a rebuild, if done 80 or so times, the GC won't have enough time to close all the leftover connections before they reach 80/90 and hit the limit.

Note, it seems the GC has a timeout of about 2 minutes before it cleans up a leftover/idle connection.

**Comment by mpscholten** [comment]
Any updates on this one?

**Comment by harryaskham** [comment]
I'm also facing this. I suspect that @s0kil is correct here as I'm a compulsive saver, meaning I trigger >1 rebuilds in a given second quite frequently.
