### ISSUE TITLE
Request Logger not logging requests anymore

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#738]
It seems that the request logger is not outputting the request log when running in production anymore. I guess this is related to that default log level being `warn`, and the request logger seems to log to `info`.

cc: @zacwood9

**Comment by zacwood9** [comment]
Yes that would do it, this is definitely not desired behavior.

To get around this for now, you can set in Config.hs
```
logger <- liftIO $ newLogger def { level = Info }
option logger
```
This should have the same behavior as before IHP.Log was added.

Should info be the default log level for production?

**Comment by mpscholten** [comment]
> Should info be the default log level for production?

Makes sense to me 👍
