### ISSUE TITLE
AutoRoute not working with non-UUID parameter types

### ISSUE THREAD

**Issue by nghamilton** [digitallyinduced/ihp#763]
The [documentation](https://ihp.digitallyinduced.com/Guide/routing.html#parameter-types) indicates that AutoRoute will work with with non-UUID types (e.g. Text), but this is not the case.

The v0.8.0 implementation of AutoRoute only parses UUIDs: `parseArgument = parseUUIDArgument`

**Comment by mpscholten** [comment]
This was just merged two days ago https://github.com/digitallyinduced/ihp/pull/753 :) The documentation currently is always reflecting the latest master. We'll soon tag v0.9, then the feature should be available. If you don't want to wait you can also update to the latest master using this guide: https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-the-latest-git-commit
