### ISSUE TITLE
Segmentation fault (core dumped) When Typed AutoRoute Tries To Parse UUID Value As Text Type

### ISSUE THREAD

**Issue by s0kil** [digitallyinduced/ihp#766]

**Comment by s0kil** [comment]
Related, when there is a segfault the Postgres processes are not closed.

**Comment by mpscholten** [comment]
Just happend to me when editing an enum

**Comment by s0kil** [comment]
Turns out this error is related to the new Typed AutoRoute introduced in https://github.com/digitallyinduced/ihp/pull/753 and https://github.com/digitallyinduced/ihp/pull/772

Who would have guessed???

**Comment by s0kil** [comment]
The router crashes the DevServer when trying to parse `EditRow?tableName=events&targetPrimaryKey=ea9cd792-107f-49ff-92a1-f610f7a31f31`, more specifically, when the type of the `targetPrimaryKey` is `Text`, the router crashes parsing `ea9cd792-107f-49ff-92a1-f610f7a31f31`.

**Comment by s0kil** [comment]
Looks like I will be visiting a therapist soon. (:
