### ISSUE TITLE
Routing error not helpful

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#775]
Routing failed with: Invalid method, expected one of: [POST] CallStack (from HasCallStack): error, called at ./IHP/RouterSupport.hs:143:73 in ihp-0.8.0-64FXrNpNQGS9ujt1ycZTFl-IHPFramework:IHP.RouterSupport

**Comment by CelestialBoon** [comment]
Specifically, this happened when I tried to manually route to a `Create____Action` eg. `<a href={CreateOrderAction (get #id user) (get #id product)}>Add to cart</a>`

**Comment by mpscholten** [comment]
Error messages have now improved quite a bit in this case https://github.com/digitallyinduced/ihp/commit/e8f50685fd61f0f17cbf948aa15fe74c41651378 :)
