### ISSUE TITLE
Websocket documentation notes

### ISSUE THREAD

**Issue by kodeFant** [digitallyinduced/ihp#796]
Hi! I am pretty new to WebSockets, so I have run into some roadblocks following the docs. Figured it could be useful to highlight some of these, as there are probably many beginners in this field :) 

I will happily contribute as I best can of course. And will add to my Elm+IHP tutorial when I have grasped this :)

1. Is there a way of creating some kind of subscription to database changes triggering a message to the WebSocket, like what's possible with AutoRefresh? That would be great for example for having an Elm component that subscribes to the database and updates without performing a page refresh as other critical stuff is happening other places in the app.

2. I am able to use the setState function, but I understand very little of what to do next after such a setState.

I tried to write it like below, but I seem to never get sent to the `Connected` state in any way, or at least not able to use it in a meaningful way. 

Like you see in the messy example below, I have tried many different places to set state and print with `putStrLn`, but no feedback other than from the `putStrLn "run Connecting"`:

```haskell
module Web.Controller.HelloWorld where

import Web.Controller.Prelude

instance WSApp HelloWorldController where
    initialState = Connecting

    run = do
        state <- getState
        case state of
            Connecting -> do
                putStrLn "run Connecting"
                sendTextData ("Connecting" :: Text)
                setState Connected

            Connected -> do
                putStrLn "run Connected"
                name <- receiveData @Text
                sendTextData ("Hello" <> name <> "! You are connected!")
                forever receiveDataMessage

    onClose = do
        state <- getState
        case state of
            Connecting -> do
                putStrLn "onClose Connecting"
                setState Connected
            Connected -> do
                putStrLn "onClose Connected"
        putStrLn "Close"

```

3. I can't seem to in any way get further to the onClose lifecycle event, for example

```haskell
    onClose = do
        state <- getState
        case state of
            WaitForName -> pure () -- Do nothing in case the connection is closed before a name was entered
            NameEntered { name } -> do
                let message :: Text = name <> " has left!"
                putStrLn message
```
Nothing is ever printed to my console. I never get that "has left" message, so I am unsure whether it's a bug or something else.

**Comment by mpscholten** [comment]
> Is there a way of creating some kind of subscription to database changes triggering a message to the WebSocket, like what's possible with AutoRefresh? That would be great for example for having an Elm component that subscribes to the database and updates without performing a page refresh as other critical stuff is happening other places in the app.

Yes :)

Here's an example code that subscribes to the `messages` table and sends any new chat message over the websocket to the current user:

```haskell
module Web.Controller.MessageNotifications where

import Web.Controller.Prelude
import qualified IHP.PGNotify as PGNotify

import qualified Database.PostgreSQL.Simple as PG
import qualified Database.PostgreSQL.Simple.Types as PG
import qualified Database.PostgreSQL.Simple.Notification as PG
import Control.Concurrent.Async

import Data.Aeson as Aeson

instance WSApp MessageNotificationsController where
    initialState = MessageNotificationsController

    run = do
        sqlExec (PG.Query $ notificationTrigger) ()

        let listenStatement = "LISTEN " <> (PG.Query "did_create_message")

        forever do
            notification <- withDatabaseConnection \databaseConnection -> do
                PG.execute databaseConnection listenStatement ()
                PG.getNotification databaseConnection

            let payload = notification |> get #notificationData |> cs
            case Aeson.decode payload of
                Just message@(DidCreateMessage { id, toUserId }) | toUserId == get #id currentUser -> do
                    sendTextData (encode message)
                _ -> pure ()


notificationTrigger :: ByteString
notificationTrigger = "CREATE OR REPLACE FUNCTION notify_created_message() RETURNS TRIGGER AS $$"
        <> "BEGIN\n"
        <> "    PERFORM pg_notify('did_create_message', json_build_object('record', row_to_json(NEW))::text);\n"
        <> "    RETURN new;"
        <> "END;\n"
        <> "$$ language plpgsql;"
        <> "DROP TRIGGER IF EXISTS did_insert_message ON messages; CREATE TRIGGER did_insert_message AFTER INSERT ON \"messages\" FOR EACH ROW EXECUTE PROCEDURE notify_created_message();\n"

data DidCreateMessage = DidCreateMessage { id :: Id Message, body :: Text, fromUserId :: Id User, toUserId :: Id User}


instance FromJSON DidCreateMessage where
    parseJSON = withObject "DidCreateMessage" $ \v -> do
        record <- v .: "record"

        id <- Id <$> record .: "id"
        body <- record .: "body"
        fromUserId <- Id <$> record .: "from_user_id"
        toUserId <- Id <$> record .: "to_user_id"

        pure DidCreateMessage { .. }


instance ToJSON DidCreateMessage where
    toJSON message = object
        [ "id" .= get #id message
        , "fromUserId" .= get #fromUserId message
        , "toUserId" .= get #toUserId message
        , "body" .= get #body message
        ]
```

It would be nice to have this built-in. But right now the functions in our [PG notify module](https://github.com/digitallyinduced/ihp/blob/master/IHP/PGNotify.hs) are not covering this well enough, that's why this `MessageNotifcationsController` has this implemented itself.

--

> I am able to use the setState function, but I understand very little of what to do next after such a setState.

Likely you want to have a `forever` loop inside the `run`:

```haskell
    run = do
        forever do
            state <- getState
            case state of
                Connecting -> do
                    putStrLn "run Connecting"
                    sendTextData ("Connecting" :: Text)
                    setState Connected
    
                Connected -> do
                    putStrLn "run Connected"
                    name <- receiveData @Text
                    sendTextData ("Hello" <> name <> "! You are connected!")
                    forever receiveDataMessage
```



> I can't seem to in any way get further to the onClose lifecycle event, for example

Just looked at the code and I think you found a bug 👍  Right now the `onClose` is only triggered if the client disconnects, but not if the server finishes running it's `run` function (I usually have a `forever` in my websockets, so they're always closed from the client)

**Comment by kodeFant** [comment]
Great, hope to get time to check this out in the weekend, will report back :)

**Comment by nomoredarts** [comment]
Thank you for that, I was going to ask the same

**Comment by mpscholten** [comment]
Regarding:

> I can't seem to in any way get further to the onClose lifecycle event, for example

I just pushed a fix for that onto master: https://github.com/digitallyinduced/ihp/commit/9e4c172f1b23bdcd63fe04f54bbb1a719ddd1a1d

**Comment by nomoredarts** [comment]
@mpscholten I was trying to recreate your example, but without User table.

I've ended up with this error.
```
Web/Controller/MessageNotifications.hs:18:9
    * Could not deduce: ?modelContext::ModelContext
        arising from a use of `sqlExec'
      from the context: (?state::IORef MessageNotificationsController,
                         ?context::ControllerContext,
                         ?applicationContext::IHP.ApplicationContext.ApplicationContext,
                         ?connection::Network.WebSockets.Connection.Connection)
        bound by the type signature for:
                   run :: (?state::IORef MessageNotificationsController,
                           ?context::ControllerContext,
                           ?applicationContext::IHP.ApplicationContext.ApplicationContext,
                           ?connection::Network.WebSockets.Connection.Connection) =>
                          IO ()
        at Web/Controller/MessageNotifications.hs:17:5-7
    * In a stmt of a 'do' block:
        sqlExec (PG.Query $ notificationTrigger) ()
      In the expression:
        do sqlExec (PG.Query $ notificationTrigger) ()
           let listenStatement = "LISTEN " <> (PG.Query "did_create_message")
           forever
             do notification <- withDatabaseConnection
                                  \ databaseConnection -> ...
                let ...
                ....
      In an equation for `run':
          run
            = do sqlExec (PG.Query $ notificationTrigger) ()
                 let listenStatement = ...
                 forever
                   do notification <- withDatabaseConnection ...
                      ....
   |
18 |         sqlExec (PG.Query $ notificationTrigger) ()
```

**Comment by mpscholten** [comment]
Are you running an older version of IHP? This problem has been fixed via https://github.com/digitallyinduced/ihp/commit/ed609d0125d856865ec06dcbcd57c7bbcc144917#diff-106802579bb76587f0d0e884c49c3f18415959531d650e0d3809e675118214c1 already

**Comment by nomoredarts** [comment]
Yes, I had version 0.9 apparently.
Working like a charm in v0.11.0

Many thanks!
