### ISSUE TITLE
App fails in production with locked MVar

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#799]
```
Mar 03 19:04:08 nixos start-app[12488]: CallStack (from HasCallStack):
Mar 03 19:04:08 nixos start-app[12488]:   error, called at ./Control/AutoUpdate.hs:139:48 in auto-update-0.1.6-JjkGYhbyQZt7zynhU75W78:Control.AutoUpdate
Mar 03 19:04:16 nixos start-app[12488]: Control.AutoUpdate.mkAutoUpdate: worker thread exited with exception: thread blocked indefinitely in an MVar operation
Mar 03 19:04:16 nixos start-app[12488]: CallStack (from HasCallStack):
Mar 03 19:04:16 nixos start-app[12488]:   error, called at ./Control/AutoUpdate.hs:139:48 in auto-update-0.1.6-JjkGYhbyQZt7zynhU75W78:Control.AutoUpdate
```

**Comment by s0kil** [comment]
https://github.com/yesodweb/wai/blob/master/auto-update/Control/AutoUpdate.hs#L146-L151

**Comment by mpscholten** [comment]
I've used GitHub search to find all mentions of the `mkAutoUpdate` function. Found one in FastLogger: https://github.com/kazu-yamamoto/logger/blob/74600082334e9af6329a554bda590df1c6983af8/fast-logger/System/Log/FastLogger/Date.hs#L36

Pretty sure this could be the one causing troubles, as the error didn't happen before we've been using FastLogger.

**Comment by mpscholten** [comment]
I tried to reproduce the issue locally using a production binary and `ab`, but nothing is happening.

--- 

Maybe the issue might be related to the use of `unsafePerformIO` here https://github.com/digitallyinduced/ihp/commit/f89d42c437af63d579b4bb6729bee92268da5b25#diff-c6dcec2ec778764bb8b6464e628562657324afa06b4480a04988dfff3ec732b3

To test out this idea I'll update the ihp-website to latest IHP master and then ship it to production with optimization enabled :) If it doesn't crash the next few days, it's very likely been fixed by the `unsafePerformIO`.

**Comment by mpscholten** [comment]
Deployed via https://ihpcloud.com/ShowDeployment?deploymentId=7a80c7d5-77be-423f-97bb-3a21e54563b8

**Comment by mpscholten** [comment]
Updates: The IHP website was down at 12:25 caused by this error, so it's not caused by the `unsafePerformIO`
