### ISSUE TITLE
controller action with id parameter returns 404 when primary key is bigserial

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [digitallyinduced/ihp#812]
Reproduce:
* create project
* define table contracts

-- Your database schema. Use the Schema Designer at http://localhost:8001/ to add some tables.

CREATE TABLE Contracts (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    content TEXT NOT NULL
);

* generate controller, start app, create contract and try to show it:
* Log:

GET /Contracts
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  Status: 200 OK 0.0031182s

GET /NewContract
  Accept: text/html, application/xhtml+xml
  Status: 200 OK 0.0000938s

Query (6.7798ms): "INSERT INTO Contracts (id, content) VALUES (?, ?) RETURNING *" (Default,"")
POST /CreateContract
  Accept: */*
  Status: 302 Found 0.0071586s

Query (0.4782ms): "SELECT Contracts.* FROM Contracts" []
GET /Contracts
  Accept: */*
  Status: 200 OK 0.000644s

GET /ShowContract
  Params: [("contractId","1")]
  Accept: text/html, application/xhtml+xml
  Status: 404 Not Found 0.0000978s

**Comment by zacwood9** [comment]
Hi there, thanks for reporting! Just found a fix for this and will be pushing it soon.

**Comment by Kaeptenblaubaer** [comment]
@zacwood9 
fyi:
Merging #813 did not yet do the trick.
Upgraded to "0a135706417f2550d50b105a63daf5d9b8335bc1" to no avail.

**Comment by zacwood9** [comment]
@mpscholten Does `Bigserial` map to Int or Integer? I only added support for integer since I assumed it would map to that, but if it's Int I can make another PR adding that

**Comment by mpscholten** [comment]
[It maps to `Integer`](https://github.com/digitallyinduced/ihp/blob/master/IHP/SchemaCompiler.hs#L58)

**Comment by zacwood9** [comment]
@Kaeptenblaubaer did you update your AutoRoute instance declaration?

```haskell
instance AutoRoute <your controller> where
    autoRoute = autoRouteWithIdType (parseIntegerId @(Id <your model type>))
```

**Comment by Kaeptenblaubaer** [comment]
@zacwood9 
Thank You! That helped.
