### ISSUE TITLE
Job does not run automatically

### ISSUE THREAD

**Issue by waddlaw** [digitallyinduced/ihp#816]
I think the following parts are affected.

```hs
    -- let run = withBackgroundWorkers frameworkConfig do
    let run = runServer frameworkConfig $
            staticMiddleware $
                sessionMiddleware $
                        requestLoggerMiddleware $
                                methodOverridePost $
                                    application
```
https://github.com/digitallyinduced/ihp/blob/master/IHP/Server.hs#L57-L63

The IHP documentation states:.
> IHP watches the job table in the database for any new records and automatically run the job asynchronously when a new job is added. So to run a job, simply create a new record:

**Comment by mpscholten** [comment]
In production or development mode?

**Comment by waddlaw** [comment]
I tried it in development mode.

**Comment by zacwood9** [comment]
This is my bad - development code that commented out the background workers made it through to master. Just uploaded PR to fix

**Comment by mpscholten** [comment]
@waddlaw check out https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-the-latest-git-commit to update to the latest master of IHP. This should fix the issue 👍
