### ISSUE TITLE
Fix browser navigation forward and backward across form submission pages

### ISSUE THREAD

**Issue by jyoder** [digitallyinduced/ihp#822]
I've noticed what seems like an issue with navigation using the browser back and forward buttons and form submission.

**To Reproduce**
1. Submit a form from page A
2. The action redirects to another page B
3. Click the back button in the browser
4. Click the forward button in the browser

**Expected Behavior**

The user ends up on page B.

**Observed Behavior**

The content of page A is displayed, but the URL is B.

**Other notes**

I reproduced in a fresh ihp install with a single controller/model using the default code from the generator.

I dug into what's going on in helpers.js and noticed that if I change [line 185](https://github.com/digitallyinduced/ihp/blob/0a135706417f2550d50b105a63daf5d9b8335bc1/lib/IHP/static/helpers.js#L185) from:
`history.pushState({}, '', request.responseURL);`

to:
`history.pushState({"turbolinks": "fake"}, '', request.responseURL);`

then navigation in this scenario works as expected. But I'm not super familiar with the internals of Turbolinks, so not sure if I'm breaking something else with that change.

**Comment by mpscholten** [comment]
Thanks for opening an issue :) Could reproduce the issue with the above steps and the suggested fix also solves the problem for me. The change should not break anything, and it seems a similiar approach is also used by other JS libraries that integrate with turbolinks 👍
