### ISSUE TITLE
Brittany (code formatter) doesn't work for the generated code

### ISSUE THREAD

**Issue by mingyuguo** [digitallyinduced/ihp#824]
brittany would replace the following by '_'
fill @["title","body"]

There are a few other places also having issues in the same file

Anyone knows what kind of language extensions I need to turn on for brittany?

**Comment by zacwood9** [comment]
You can see the default language extensions used in IHP in the ihp.cabal file, https://github.com/digitallyinduced/ihp/blob/master/ihp.cabal#L94

**Comment by mingyuguo** [comment]
Thanks! 

I added all extensions to brittany's config file ~/.config/brittany/config.yaml

conf_forward:
  options_ghc:
    - -DataKinds
    - -DefaultSignatures
    - -DeriveDataTypeable
    - -DeriveGeneric
    - -DisambiguateRecordFields
    - -DuplicateRecordFields
    - -ImplicitParams
    - -InstanceSigs
    - -LambdaCase
    - -XBangPatterns
    - -XExplicitForAll
    - -XGADTs
    - -XImplicitParams
    - -XLambdaCase
    - -XMultiWayIf
    - -XPatternGuards
    - -XQuasiQuotes
    - -XRecursiveDo
    - -XTemplateHaskell
    - -XTupleSections
    - -XViewPatterns

(BTW, brittany complains if you add any "non-syntax" extensions, so things like overloadedstrings need to be removed)

However, after adding these extensions, brittany still does one incorrect thing

it splits #title into # title with a space in between.

**Comment by zacwood9** [comment]
That syntax comes from OverloadedLabels. Might be a bug in brittany then, maybe file an issue on that project?

**Comment by s0kil** [comment]
Brittany does not work well with all the GHC extensions that IHP uses.

**Comment by SourOatMilk** [comment]
@mingyuguo I ran into this issue as well and it turns out that Brittany needs more options. Here is what worked for me:

```
conf_forward:
  options_ghc:
    - -XTypeApplications
    - -XPatternSynonyms
    - -XOverloadedLabels
    - -DataKinds
    - -DefaultSignatures
    - -DeriveDataTypeable
    - -DeriveGeneric
    - -DisambiguateRecordFields
    - -DuplicateRecordFields
    - -ImplicitParams
    - -InstanceSigs
    - -LambdaCase
    - -XBangPatterns
    - -XExplicitForAll
    - -XGADTs
    - -XImplicitParams
    - -XLambdaCase
    - -XMultiWayIf
    - -XPatternGuards
    - -XQuasiQuotes
    - -XRecursiveDo
    - -XTemplateHaskell
    - -XTupleSections
    - -XViewPatterns
```

Generated code with `validateField` bit added by hand:

```
   cat Web/Controller/Posts.hs | tail                                                                   

  action DeletePostAction { postId } = do
    post <- fetch postId
    deleteRecord post
    setSuccessMessage "Post deleted"
    redirectTo PostsAction

buildPost post = post
  |> fill @["title" , "body"]
  |> validateField #title nonEmpty
```

And then with Brittany:

```
   brittany Web/Controller/Posts.hs | tail                                                              
        redirectTo PostsAction

  action DeletePostAction { postId } = do
    post <- fetch postId
    deleteRecord post
    setSuccessMessage "Post deleted"
    redirectTo PostsAction

buildPost post =
  post |> fill @'["title" , "body"] |> validateField #title nonEmpty
```
