### ISSUE TITLE
Instead of fileOrNothing enable ParamReader to handle files

### ISSUE THREAD

**Issue by themmes** [digitallyinduced/ihp#827]
## Context

Today I was trying to enable handling for multiple files. Before, I was using the following logic in my `Pictures.hs` controller

```haskell
action CreatePictureAction = do
    let picture = newRecord @Picture

    picture
        |> buildPicture
        |> set #id buildingElementId
        |> s3uploadImageWithOptions pictureOptions #pictureUrl
        >>= ifValid \case
        ...
```

Under the hood `s3uploadImageWithOptions` relies on `fileOrNothing` to read the files from the request. To enable multiple files I adapted `s3uploadImageWithOptions ` to take the file directly and wrote the following:

```haskell
filesOrNothing :: (?context :: ControllerContext) => ByteString -> Maybe [FileInfo LBS.ByteString]
filesOrNothing !name =
    ?context
    |> get #requestContext
    |> get #requestBody
    |> \case
        FormBody { files } -> Just $ map snd files
        _ -> Nothing

action CreatePicturesAction = do
    let pictureFiles = filesOrNothing "pictureUrl"

    case pictureFiles of
        Just pictureFiles -> do
            forM_ pictureFiles $ \pictureFile -> do
                let picture = newRecord @Picture
                picture
                    |> set #buildingPartId buildingPartId
                    |> s3uploadImageWithOptions pictureOptions #pictureUrl pictureFile
                    ...
```

## Proposal

This led me to wonder why files are treated differently than other parameters? Especially since there exists the nice `ParamReader` that already handles many types of parameters. Therefore I wanted to suggest to adapt `ParamReader` to handle files to and enable the following syntax.

```haskell
action CreatePicturesAction = do
    let pictureFiles = paramList @(FileInfo LBS.ByteString) "pictureUrl"
    -- or in the case of a single picture
    -- let pictureFile = paramOrNothing @(FileInfo LBS.ByteString) "pictureUrl"

    forM_ pictureFiles $ \pictureFile -> do
        let picture = newRecord @Picture
        picture
            |> set #buildingPartId buildingPartId
            |> s3uploadImageWithOptions pictureOptions #pictureUrl pictureFile
            ...
```

I would love to hear your thoughts!

**Comment by mpscholten** [comment]
Hey Tom, I think with the [new storage API functions](https://ihp.digitallyinduced.com/Guide/file-storage.html) this not needed anymore :)

I'll close this for now. But still thanks for taking the time for opening up the discussion on this :)
