### ISSUE TITLE
add ihp to Stackage?

### ISSUE THREAD

**Issue by juhp** [digitallyinduced/ihp#837]
I know that nix is your supported method of installation,
but not everyone uses nix and so it would be pleasant
(also for Linux distros) if IHP was added to Stackage
to allow the project to be built more easily without nix.

I am able to start building with:
```
$ echo "resolver: lts-17.8" > stack.yaml
$ stack build primitive-offset bytebuild run-st tuples byteslice contiguous bytesmith natural-arithmetic ip pwstore-fast random-strings wai-session-clientsession http-accept wai-util .
```
at least. Also for `--resolver nightly`.

**Comment by s0kil** [comment]
@juhp Please take a look at https://github.com/digitallyinduced/ihp/issues/819#issuecomment-799548134
