### ISSUE TITLE
MAC / HMAC functions cannot be imported due to ambiguous module name

### ISSUE THREAD

**Issue by njaremko** [digitallyinduced/ihp#845]
Hello,

I'm trying to use cryptonite functions in an IHP project, but I'm getting the follow error when I try to import them:

```haskell
import Crypto.MAC.HMAC (hmac, HMAC)
```

```
Ambiguous module name ‘Crypto.MAC.HMAC’:
  it was found in multiple packages:
  cryptohash-0.11.9 cryptonite-0.27
```

**Comment by jeyj0** [comment]
I just recently ran into the same problem and solved it using [Package-qualified imports](https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/package_qualified_imports.html). The import then becomes `import "package" The.Module`. The extension should be enabled already.

**Comment by njaremko** [comment]
That seems like it'll work. Thanks 😊
