### ISSUE TITLE
Rename IHP.HtmlSupport to IHP.HSX

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#851]

**Comment by afzal442** [comment]
Hi, can I take up this?

**Comment by mpscholten** [comment]
Yes 👍  if you need any help on this let us know on slack :)

**Comment by afzal442** [comment]
@mpscholten I was looking for the solution. Is it like to rename IHP.HtmlSupport to IHP.HSX wherever I see e.g. in this file IHP/HtmlSupport/ToHtml.hs we need to change `module IHP.HtmlSupport.ToHtml where` into `module IHP.HSX.ToHtml...`? Thanks.

**Comment by mpscholten** [comment]
yes, likely also updating the tests
