### ISSUE TITLE
Allow for Type Application in HSX

### ISSUE THREAD

**Issue by zacwood9** [digitallyinduced/ihp#857]
Using type application syntax in HSX currently results in an error. It would be nice for this to work as expected :)

**Comment by mpscholten** [comment]
To support type application I think we need to remove `haskell-src-ext`. That package is used to parse inline haskell expressions inside HSX (e.g. `{myFunc a}`, everything after the `{` until the `}` is parsed using `haskell-src-ext`). The `haskell-src-ext` parser doesn't support many of the new haskell features. E.g. it doesn't support `#` syntax (like `get #name user`), [we kind of patched it into it using some ast transformations after parsing](https://github.com/digitallyinduced/ihp/blob/master/IHP/HtmlSupport/Parser.hs#L429) :)

Recent GHC versions now allow user-land code to access GHC's own parser. So we could use that one to replace `haskell-src-ext` and then support the full spectrum of all haskell syntax. I found https://github.com/guibou/PyF/pull/61 where the `PyF` did a similiar transition. Maybe we can take that as an inspiration.

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/issues/857 👍
