### ISSUE TITLE
Should we add a release.nix file to NixSupport?

### ISSUE THREAD

**Issue by njaremko** [digitallyinduced/ihp#859]
I've included the proposed body below, but the only changes between this and default.nix are:
- Building with O2 instead of O0 make target
- Added `pkgs.which` as a native dependency, since you try to run it when we execute the binary, and it'll fail without it.

We'd probably need a corresponding `release.nix` in the ihp-new template importing this file as well.

If this proposal is accepted, then we can add instructions for how to build a production docker image to the deployment documentation.

```
{ compiler ? "ghc8103", ihp, haskellDeps ? (p: []), otherDeps ? (p: []), projectPath ? ./., withHoogle ? false }:

let
    pkgs = import "${toString projectPath}/Config/nix/nixpkgs-config.nix" { ihp = ihp; };
    ghc = pkgs.haskell.packages.${compiler};
    allHaskellPackages =
      (if withHoogle
      then ghc.ghcWithHoogle
      else ghc.ghcWithPackages)
        (p: (haskellDeps p) );
    allNativePackages = builtins.concatLists [ (otherDeps pkgs) [pkgs.postgresql pkgs.which] (if pkgs.stdenv.isDarwin then [] else []) ];
in
    pkgs.stdenv.mkDerivation {
        name = "app";
        buildPhase = ''
          make -B build/bin/RunOptimizedProdServer
        '';
        installPhase = ''
          mkdir -p $out
          cp -r build/bin $out/bin
        '';
        dontFixup = true;
        src = (import <nixpkgs> {}).nix-gitignore.gitignoreSource [] projectPath;
        buildInputs = builtins.concatLists [[allHaskellPackages] allNativePackages];
        shellHook = "eval $(egrep ^export ${allHaskellPackages}/bin/ghc)";
    }
```

**Comment by mpscholten** [comment]
Like the idea 👍 

When we add the `release.nix` we should make sure that the dependencies don't need to be specified in both files :)

**Comment by mpscholten** [comment]
This has been basically implemented by now.

```bash
# Optional, enable optimized build
make prepare-optimized-nix-build

# The actual build process
nix-build
```

Docs can be found here:
https://github.com/digitallyinduced/ihp/commit/80259d479ccb2df8fea9b294381e2537736e50d5
