### ISSUE TITLE
Why does IHP source need to exist on the path to run prod binary?

### ISSUE THREAD

**Issue by njaremko** [digitallyinduced/ihp#860]
If I try to run `result/bin/RunProdServer` (the result of a nix-build), why does the binary need IHP to exist locally or in the path? (Also, why does it need `which` to be installed?)

On a related note, are there plans to make the compiled binary not need these things? It makes deploying IHP kind of a hassle.

**Comment by mpscholten** [comment]
The app needs to access IHP's `static` directory at https://github.com/digitallyinduced/ihp/tree/master/lib/IHP/static for serving some JS and CSS files bundled with IHP.

`which` is used to find the location of IHP.

I agree that this is not a nice solution right now. Maybe we can bundle the static files into the binary somehow :)

**Comment by njaremko** [comment]
Can we just something like this to the installPhase of the nix file, and change the binary to look there instead?

```
mkdir -p $out/IHP/static
cp -r ${ihp}/lib/IHP/static $out/IHP/static
```

**Comment by mpscholten** [comment]
> Can we do something like this in the installPhase of the nix file, and change the binary to look there instead?

Yes this could be a good solution 👍

**Comment by mpscholten** [comment]
This has been fixed via https://github.com/digitallyinduced/ihp/commit/e51ace8e08b5b5da9f104824ece25fc4a27d0c76 🎉 

You can now do the following:

```bash
$ ihp-new testapp # Create new app
$ cd testapp

# Update to latest master of IHP
$ vim default.nix # Replace `ref = "refs/tags/v0.14.0";` with `ref = "beee68f3f340c3b1e69d097c6e50cb72a98dabd9";`

# Build the app
$ nix-build

# Run the app
$ ./result/bin/RunProdServer
```

Like suggested the static files from IHP are now copied over to the project.
