### ISSUE TITLE
make IHP more "industry compliant"

### ISSUE THREAD

**Issue by admin-brestcc** [digitallyinduced/ihp#865]
Hi ! 
First of all, thanks for your great work ! 
I'm trying IHP and I've a few feedbacks / ideas to share about deployment & configuration.

To give you a bit of context about my remarks, I work in a cloud / security / infra / devops environment, know a bit of Haskell, use nixOS on a daily basis at work and think IHP could be a great way to introduce it at work on small non-critical projects... but 2 things would be just show stoppers and are not provided by default (I had to struggle a bit).

[Here's a repo](https://github.com/brest-computer-club/realworld-app-ihp) where I've put my little experiment.

## Deployment model
The deployment model as explained [here](https://ihp.digitallyinduced.com/Guide/deployment.html#deploying-manually) is very unlikely to be adopted in any env I ever worked in (even on a small & non-critical project). 
To summarize : there's no way for a client whatsoever to initiate a connection to a prod instance, nor to build the code after having tweaked the files on a (supposed short-lived) server... and even less to have this as a deployment model.
People usually do the things the other way round : build and store artifacts (usually docker images these days) so they can be pulled by the server (or cluster / container orchestrator). 

I found a way to build a [working docker image](https://github.com/brest-computer-club/realworld-app-ihp/blob/master/Dockerfile) based on the @zacwood9 's great [post](https://zacwood.me/posts/building-ihp-apps-github-actions/). I must confess I struggled a bit to get it right (and wouldn't have wrote the derivation myself). It would be great to offer that by default.

## Configuration
It's less critical, but nowadays apps are supposed to have build and run stages completely decorrelated. 
Especially they should receive all their configuration at startup time, the [12-factor app](https://12factor.net/) offers simple and good-enough recommendations about that. 
In the same doc, we've to change the environment in `./Config/Config.hs` before building... I don't see why it's not provided at runtime via an environment variable. I [gave a try](https://github.com/brest-computer-club/realworld-app-ihp/blob/4204676d60fa4d0f8a33702643e5eb98b7f16021/Config/Config.hs#L8) and it seems to work fine... maybe I miss something.

That's just my 2 cents, thanks again for your work, I'll keep exploring it ! ;)

**Comment by mpscholten** [comment]
Thanks for your input :)

I agree that we need to improve the docker support. The current deployment documentation is not perfect as we're mostly using IHP Cloud internally. But I guess not that much work is needed to make docker builds work out of the box.

Regarding configuration: I agree with that as well. There's an issue for that already on our internal issue tracker. This will be changed before v1.0 is released:
![image](https://user-images.githubusercontent.com/2072185/116459074-a6e32780-a865-11eb-823e-bb1d2d1c3367.png)

**Comment by admin-brestcc** [comment]
That's great ! Thanks a lot.
I didn't know there's a roadmap to a v1, I guess it's internally.
If I can give a hand, just tell me, I'd be happy to help :)

**Comment by mpscholten** [comment]
There's now an update on this one :) IHP apps can now be easily converted to a docker image using `ihp-app-to-docker-image`. Additionally the app can now be fully configured using env variables and is 12 factor compliant out of the box.

Here's the documentation on how to run IHP with docker in production: https://ihp.digitallyinduced.com/Guide/deployment.html#deploying-with-docker

**Comment by mpscholten** [comment]
This is mostly fixed now. IHP can now be fully configured via env vars, docker images or nix derivations are the default way to build artifacts
