### ISSUE TITLE
Auto-generated Controller has empty new & edit forms

### ISSUE THREAD

**Issue by hendi** [digitallyinduced/ihp#867]
Clicking "New" just creates an empty object, clicking "Edit" results in the following "form":

![image](https://user-images.githubusercontent.com/550218/117120917-3b80e480-ad94-11eb-8b5b-7c353269d5d4.png)

Application/Schema.sql
```
CREATE TYPE immobilien_type AS ENUM ('haus_buy', 'haus_rent');
CREATE TABLE immobilien (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    immobilien_type immobilien_type NOT NULL,
    area_living INT NOT NULL,
    area_garden INT,
    rent_monthly INT DEFAULT NULL,
    price INT DEFAULT NULL
);
```

using

```
    ihp = builtins.fetchGit {
        url = "https://github.com/digitallyinduced/ihp.git";
        ref = "refs/tags/v0.9.0";
    };
```

**Comment by hendi** [comment]
Looks like this is related to "make table names plural"; if I rename `immobilien` (German plural) to `properties` it works.

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/commit/908eaebdc99e0ecd6529f2f204706e5890d05725
