### ISSUE TITLE
Rename database in Schema Designer

### ISSUE THREAD

**Issue by ShalokShalom** [digitallyinduced/ihp#869]
I am stuck

![Screenshot_20210508_142119](https://user-images.githubusercontent.com/6344099/117539065-1fd24400-b009-11eb-9a7e-970b6e792df6.png)

How to update the name?

**Comment by s0kil** [comment]
Try using underscores in the name

**Comment by mpscholten** [comment]
To fix the name use the `Code Editor` toggle at the top left of the screen. Then you need to manually edit the sql to fix by renaming `paint-flights` to `paint_flights` in the sql code. After that use the `Code Editor` toggle to switch back to GUI mode.

**Comment by ShalokShalom** [comment]
I did this. How to save?

**Comment by mpscholten** [comment]
If there’s no save button, try open the Application/Schema.sql in your text editor and Save it there :) this will likely work

**Comment by ShalokShalom** [comment]
There could be a save button 😸
