### ISSUE TITLE
Creating a Nullable text field with no default sets the default to empty string.

### ISSUE THREAD

**Issue by nunocf** [digitallyinduced/ihp#874]
Hello,
I've been using your framework today and I'm very impressed! Thank you for your efforts in this!

I've found something that I consider a bug:

When creating a nullable `TEXT` field, I left the `default` select box as `no default`.

When trying to add a default string in the view, to show that there wasn't a description, I kept receiving back a `Just ""`.

```haskell
<p>{get #description todo |> debug |> fromMaybe defaultDescription}</p>
```

After going into the DB and running a query to update all `""` to `NULL` that `fromMaybe` worked.

Please let me know if I can help with anything else!

**Comment by mpscholten** [comment]
Hey Nuno,

Thanks for reporting! :)

I guess you added the todo using a form, likely with a  `{textField #description}` for the todo description. In that case when the form is submitted, the browser submits an empty string. Then IHP inserts this empty string to the database. IHP by default will not do any implicit transformation here.

In case it's needed, you need to manually transform the empty string to `Nothing`. As this comes up quite often in typical IHP apps, we already have a [`emptyValueToNothing`](https://ihp.digitallyinduced.com/api-docs/IHP-Controller-Param.html#v:emptyValueToNothing) function that can be called from the create or update action to transform any empty string to a null value.

[Here's an example right from the docu:](https://ihp.digitallyinduced.com/api-docs/IHP-Controller-Param.html#v:emptyValueToNothing)

```haskell
action UpdateCompanyAction { companyId } = do
    company <- fetch companyId
    company
        |> fill '["name", "comment"]
        |> emptyValueToNothing #comment
        |> updateRecord
```

Let me know if this fixes the problem :)

**Comment by nunocf** [comment]
Hello!
Yes, that was exactly it!
Thank you for pointing it out for me, it was quite a silly mistake on my side and thank you for providing me links to the docs!
