### ISSUE TITLE
Authorization: ensureIsUser in Controller instance or Action should not deny access to WelcomeView

### ISSUE THREAD

**Issue by fritzfeger** [digitallyinduced/ihp#887]
When autorization for a controller instance or a specific action is added via `ensureIsUser` (as described in [Guide/Auth/Authorization](https://ihp.digitallyinduced.com/Guide/authorization.html), having added [Guide/Auth/Login&Logout AKA Authentication](https://ihp.digitallyinduced.com/Guide/authentication.html) before), the static `WelcomeView` (from "Your First Project" following the IHP Guide) generates an `ERR_EMPTY_RESPONSE`. The auth should rather be limited to the the controller or action, respectively. As expected, http://localhost:8000/NewSession renders the login page, and http://localhost:8000/Posts redirects there too. But http://localhost:8000/ which when logged in renders `WelcomeView`, fails when logged out.

To see the described behaviour check out the [Authentication Feature Branch of the "IHP Guide: Working Examples" Git repository](https://gitlab.com/fritzfeger/ihp-guide/-/tree/authentication).

**Comment by mpscholten** [comment]
This sounds like the expected behavior to me. Why do you want to add a `ensureIsUser` to the `Welcome` controller? Could you provide a small code snippet that reproduces the problem (could not find it in the gitlab)?

**Comment by jeyj0** [comment]
I think I understand the issue, but unless I spend a bit more time investigating, here's how to see the effect using the gitlab repo:

1. `git clone --branch authentication https://gitlab.com/fritzfeger/ihp-guide.git`
2. verify that there is no `ensureIsUser` in `Web/Controller/Static.hs`
3. run the app using `./start`
4. open at `localhost:8000`

The expected behavior is that the Welcome View shows, however instead there's no response.

**Comment by s0kil** [comment]
Yes, there is no response because a runtime error happens, inside the `WelcomeView` there is `{get #email currentUser}` and then an error in the logs stating:
```
Application.Helper.View.currentUser: Not logged in
CallStack (from HasCallStack):
  error, called at ./IHP/Prelude.hs:83:17 in ihp-0.10.0-1TSciuBIvmeET5EC7OXnS:IHP.Prelude
```

`ensureIsUser` is not at fault here, it behaves as expected.

**Comment by s0kil** [comment]
@fritzfeger In the `WelcomeView`, you could do something like this:
```haskell
instance View WelcomeView where
    html WelcomeView = [hsx|
         <div style="background-color: #657b83; padding-top: 2rem; padding-bottom: 2rem; color:hsla(196, 13%, 96%, 1); border-radius: 4px">
              <div style="max-width: 800px; margin-left: auto; margin-right: auto">
                  <h1 style="margin-bottom: 2rem; font-size: 2rem; font-weight: 300; border-bottom: 1px solid white; padding-bottom: 0.25rem; border-color: hsla(196, 13%, 60%, 1)">
                      IHP
                  </h1>

                  <h2 style="margin-top: 0; margin-bottom: 0rem; font-weight: 900; font-size: 3rem">
                      It's working!
                  </h2>

                  <p style="margin-top: 1rem; font-size: 1.75rem; font-weight: 600; color:hsla(196, 13%, 80%, 1)">
                     Your new application is up and running.
                  </p>

                  <a href="https://ihp.digitallyinduced.com/Guide/your-first-project.html" style="margin-top: 2rem; background-color: #268bd2; padding: 1rem; border-radius: 3px; color: hsla(205, 69%, 98%, 1); text-decoration: none; font-weight: bold; display: inline-block; box-shadow: 0 4px 6px hsla(205, 69%, 0%, 0.08);  transition: box-shadow 0.2s; transition: transform 0.2s;" target="_blank">
                     Learn the Next Steps in the Documentation
                  </a>
              </div>
         </div>

         <div style="max-width: 800px; margin-left: auto; margin-right: auto; margin-top: 4rem">
              <img src="/ihp-welcome-icon.svg" alt="/ihp-welcome-icon">
              <p style="color: hsla(196, 13%, 50%, 1); margin-top: 4rem">
                You can modify this start page by making changes to "./Web/View/Static/Welcome.hs".<br>
                <a href={NewSessionAction}>Login</a><br>
                {loggedInAs}
                <a class="js-delete js-delete-no-confirm" href={DeleteSessionAction}>Logout</a>
              </p>
         </div>
    |]
        where
            loggedInAs =
                case currentUserOrNothing of
                    Just user -> [hsx|You are logged in as {get #email user}<br>|]
                    Nothing -> mempty

```

**Comment by fritzfeger** [comment]
@s0kil thank you very much, reads great, yet the problem still persists. I've added a `loggedInAs` function as described in aforementioned [Authentication Feature Branch of the "IHP Guide: Working Examples" Git repository](https://gitlab.com/fritzfeger/ihp-guide/-/tree/authentication). The `Just user` case works as expected whereas the `Nothing` case results in the same error as before. `ResponseException { .. }`.
