### ISSUE TITLE
HSX: Support HTML Entities

### ISSUE THREAD

**Issue by mpscholten** [digitallyinduced/ihp#89]
https://app.clubhouse.io/digitallyinduced/story/1539/hsx-support-html-entities

**Comment by unhammer** [comment]
is there a public version of that clubhouse story?

**Comment by mpscholten** [comment]
Sadly no. But here's the context: In html you can write `&Auml;` for `Ä`. With HSX this will not work. This will output the literal string `&Auml;` instead of `Ä`. This might surprise people who expect html entities to work.

**Comment by s0kil** [comment]
@mpscholten Looks like this has been fixed? I've tried HTML entities inside HSX, and they work as expected.

**Comment by mpscholten** [comment]
This should still be open as it's not implemeneted. What currently works is just using the right unicode symbols, like `Ä`. A real html entity is `&Auml;` which is the code for `Ä` :)

IMO this issue is very low prio, so I'd be ok with closing this for now. What do you think?

**Comment by s0kil** [comment]
Entities are not very commonly used, and we do have [a solution](https://ihp.digitallyinduced.com/Guide/hsx.html#unescaped-strings) for whoever needs them, so lets close this issue.
