### ISSUE TITLE
[IHPCloud] unzip not found

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#892]
Hi! I am trying to deploy to IHPCloud and am getting the following error:

![image](https://user-images.githubusercontent.com/12722104/119562637-90e95980-bd74-11eb-8e64-6dd819732609.png)

This worked the other day. Any idea why this is happening?

Thanks!

**Comment by mpscholten** [comment]
Thanks for reporting :) We did an update yesterday to the base image in which all apps are built with, that likely caused the problem. A fix is deploying right now, can you try again in a couple of minutes? :)

**Comment by CSchank** [comment]
I see it's the same at the moment, just let me know when your deployment has finished and I'll try again :)

**Comment by mpscholten** [comment]
Just manually restarted the job that failed. The initial error is gone now, but there's a new one related to github api permissions. We're investigating that right now.

As a workaround could you try to create a new project using `+ New Project` instead of `Import from GitHub`? This will then use a normal git checkout instead of using the github api.

**Comment by CSchank** [comment]
I was able to deploy through "New Project" by providing an SSH url (since it's a private repo). 

As a sidenote, I might suggest you add some text indicating this limitation to the text underneath the url, as it was a bit confusing/annoying to receive an error only when I'd already copy/pasted it.

Edit: spoke too soon, now it says psql isn't available:

```
/run/current-system/sw/bin/bash: psql: command not found
```

**Comment by mpscholten** [comment]
Sorry, it seems my last change did break that. Should be fixed now. Can you try again?

**Comment by CSchank** [comment]
Hi, yes it appears to be working now, thank you!
