### ISSUE TITLE
Convenience Functions for Pagination

### ISSUE THREAD

**Issue by joshua-obritsch** [digitallyinduced/ihp#898]
I wanted to make a suggestion for a couple of convenience functions for pagination. The first one I made is `fetchPageCount` which fetches the total number of pages for a query. It currently looks like this:

```haskell
fetchPageCount                                                                                                                  
    :: forall (table :: Symbol)                                                                                                 
    .  ( ?modelContext :: ModelContext                                                                                          
       , KnownSymbol table                                                                                                      
       )                                                                                                                        
    => QueryBuilder table                                                                                                       
    -> IO Int                                                                                                                   
fetchPageCount !queryBuilder = do                                                                                               
    let !(theQuery', theParameters) = toSQL' (buildQuery queryBuilder)                                                          
    let theQuery = "SELECT COUNT(*) FROM (" <> theQuery' <> ") AS _count_values"                                                
    trackTableRead (symbolToByteString @table)                                                                                  
    [Only count] <- sqlQuery (Query $! cs theQuery) theParameters :: IO [Only Int]                                              
    pure $ ceiling $ fromIntegral count / fromIntegral pageSize
```
This is useful for displaying how many pages are remaining, e.g. 2/5. Ideally, you would want to pass `pageSize` in as an argument. I'm just using a constant for now. Here is how I'm using it in one of my controllers:

```haskell
pageCount <- query @Bundle |> fetchPageCount
```

The second function I made was `fetchPage` and looks like this:

```haskell
fetchPage                                                                                                                       
    :: forall model (table :: Symbol)                                                                                           
    .  ( ?modelContext :: ModelContext                                                                                          
       , FromRow model                                                                                                          
       , KnownSymbol (GetTableName model)                                                                                       
       , KnownSymbol table                                                                                                      
       )                                                                                                                        
    => Int                                                                                                                      
    -> QueryBuilder table                                                                                                       
    -> IO [model]                                                                                                               
fetchPage page !queryBuilder = do                                                                                               
    let !(theQuery, theParameters) = queryBuilder                                                                               
            |> buildQuery                                                                                                       
            |> setJust #offsetClause ("OFFSET " <> offset)                                                                      
            |> setJust #limitClause ("LIMIT " <> limit)                                                                         
            |> toSQL'                                                                                                           
    trackTableRead (tableNameByteString @model)                                                                                 
    sqlQuery (Query $ cs theQuery) theParameters                                                                                
  where                                                                                                                         
    offset = (concat . toChunks) $ encode $ (page - 1) * pageSize                                                               
    limit = (concat . toChunks) $ encode pageSize
```

Again, `pageSize` should ideally be an argument. Here's how I'm using it:

```haskell
bundles <- query @Bundle                                                                                                      
    |> orderByDesc #createdAt                                                                                                 
    |> fetchPage @Bundle page                                                                                                 
    >>= collectionFetchRelated #studentId
```

I've looked into old issues but couldn't find much about the current status of or future plans for pagination. Would something like this be useful? If so I could make a PR. I think `fetchPage` would go in the `Fetchable` typeclass.

**Comment by mpscholten** [comment]
I think this is a good first step 👍 

Maybe we could also add a data structure like this:

```haskell
data Paginator record = Paginator { items :: [record], totalPages :: Int, remainingPages :: Int, currentPage :: Int }
```

This could be useful for passing all the pagination meta data to the view (e.g. you'd likely want to access the `totalPages` and the `currentPages` in a typical case).

Then we could build a `fetchPaginated` on top of this using `fetchPage` and `fetchPageCount` for constructing a Paginator from a query builder.

**Comment by CSchank** [comment]
Funny the OP brought this up! I have been doing just this the past few days. 

For my own project, I have developed pagination in a slightly different way, but actually remarkably similar to what's discussed here, with helpers functions that you use in your actions and views. I made it very general and have been able to easily apply it to multiple `Index` views in my project with no modifications to the Pagination itself. 

I have a similar `Pagination` type to what @mpscholten describes, but without the items themselves:

```
data Pagination = 
    Pagination
    {
        pageSize :: Int
    ,   totalItems :: Int -- total items in all pages, found by querying the database
    ,   currentPage :: Int
    ,   maxInNavigation :: Int -- max number of pages to show at the bottom (skips some if there are too many)
    }
``` 

Then I have a `paginate` function:

```
paginate :: (?context::ControllerContext, ?modelContext :: ModelContext, ?theAction :: controller, KnownSymbol q) => 
    QueryBuilder q 
    -> IO (QueryBuilder q, Pagination)
```
which is meant to be called as a sort of pipeline in your action:

```
    action UsersAction = do
        (userQ, pagination) <- query @User 
            |> orderBy #email
            |> filterList #email
            |> paginate
        user <- userQ |> fetch
        render IndexView { .. }
```

What `paginate` does is query the number of items in the `QueryBuilder` you give it, looks for a `page` parameter to determine the current page, looks for a `maxItems` parameter to see if it should change the default number per page. Then uses all this information to build the `Paginate` type. Then it applies the correct limit and offset to the query and returns it. The user has to then fetch those values, and the view takes in `paginate` and `user` (note: I think we could probably do the fetching for them, but I ran into some type errors telling me I needed to call fetch as part of my action, I must not have had the right context).

There is then a rendering function which renders a nice Bootstrap view of where the user wants it, e.g. along the bottom:

`renderPagination :: (?context::ControllerContext) => Pagination -> Html`

![image](https://user-images.githubusercontent.com/12722104/120820031-2c6f8c80-c522-11eb-9db8-2d9005d83feb.png)
![image](https://user-images.githubusercontent.com/12722104/120820120-401af300-c522-11eb-94fa-f1d54378a63d.png)

I also have developed a way to filter results in general too: 

![image](https://user-images.githubusercontent.com/12722104/120820781-d8b17300-c522-11eb-8c4c-b4c48f48c234.png)

In this case, you apply this function in your action:

```
filterList :: forall name table model . (?context::ControllerContext, KnownSymbol name, HasField name model Text, model ~ GetModelByTableName table) => 
    Proxy name 
    -> QueryBuilder table 
    -> QueryBuilder table
```

which is shown in the action above actually.

What do you think? Does this approach seem good? If you think it's worth pursuing I could clean it up and put it up as a package, or submit a PR. I think some of the function names could be improved. My personal vote would be to include something like this in the Index views by default (maybe not the filter, since that requires a Text field, but the paginate works on any type of data).

**Comment by mpscholten** [comment]
Really like this approach :) Returning the query also solves problems with `fetchRelated` that would occur with wrapped `Paginator` approach.

If @joshua-obritsch is okay with this I'd suggest that you prepare a PR and we'll give this a try :)

> My personal vote would be to include pagination in the Index views by default 

Yes, let's do this 👍

**Comment by CSchank** [comment]
Awesome! Just because I haven't looked too hard at the actual IHP codebase that much, where would be the best place to include these helper functions? Should the view-based functions and controller-based functions be together in one module? In which case, it doesn't make sense to really put these in `IHP.View` or `IHP.Controller`. But splitting them up seems like too many imports. What do you think?

**Comment by mpscholten** [comment]
I typically split them up, e.g. check out https://github.com/digitallyinduced/ihp/tree/master/IHP/PageTitle

Then I'd import and re-export the functions in `IHP.ViewPrelude` and `IHP.ControllerPrelude`

**Comment by joshua-obritsch** [comment]
I really like this approach. I especially like the filter option. I also implemented something similiar, although I ran into a problem where I wanted to filter by UUID and had to check to see if the text was a valid UUID. I think because of that I couldn't make the function as flexible.

The only suggestion I would make would be to rename `maxInNavigation` to `totalPages`, otherwise I think the naming is good. :)

**Comment by CSchank** [comment]
@joshua-obritsch thank you!! Sorry if I hijacked your issue! 

Hmm, yes, in terms of the filtering, I was hoping to make it a bit more flexible, including being able to search multiple fields. In terms of searching other data types, I'd also like that too, I'm not quite sure how that would work. From what I can tell LIKE is restricted to text-based fields. The other possibility would be to use CONVERT to convert things like numbers into text before searching. Not sure if this is worth the trouble, though I think filtering by a numeric column might be worth it.

> The only suggestion I would make would be to rename `maxInNavigation` to `totalPages`, otherwise I think the naming is good. :)

Ah, that variable is actually what stores the maximum number of pages that should be shown in the selector at the bottom of the screen. I do agree the name isn't the best; knowing this, do you have another name suggestion? The other option would be to not allow the user to change this, but I think we probably should.

**Comment by joshua-obritsch** [comment]
> @joshua-obritsch thank you!! Sorry if I hijacked your issue!
No problem. :+1: 
> Ah, that variable is actually what stores the maximum number of pages that should be shown in the selector at the bottom of the screen.
I get it now. In that case I would call it `pageLimit`.

**Comment by CSchank** [comment]
> I get it now. In that case I would call it `pageLimit`.

My only hesitation with that name is it might sound a bit like it's going to actually limit the number of pages in the pagination. See? It's hard to have a concise name for this! 😆

**Comment by joshua-obritsch** [comment]
You're right. I didn't think of that. Let me summarize the terms we have and their meaning (just to clarify in case of misunderstandings). Given the following pagination:
`1,2,3,4,500`
the field `pageLimit` would be 4; the `500` could either be the total number of pages i.e. `totalPages` or a user-specified maximum i.e. `maxInNavigation`. I can understand the reasoning now behind the naming; so that people don't confuse which maximum/limit, the 4 or the 500. In that case I think `maxInNavigation` is fine. :smile:

**Comment by joshua-obritsch** [comment]
Ah, I think I had it backwards. Given the following pagination:
`1,2,3,4,500`
I thought `maxInNavigation` was referring to the `500`, but it should refer to the `4`. In that case it makes sense. :+1:

**Comment by joshua-obritsch** [comment]
Actually, now that I think about it a bit more, perhaps it would be more clear to refer to the numbers 1-4 in my previous example as visible pages and the number 500 as total pages. Therefore, the limit/max for the former would be `visiblePageLimit` (or `selectablePageLimit`) and if the user wanted to limit the latter, they could write `totalPageLimit`.

**Comment by mpscholten** [comment]
Naming things is hard 😄 

[I just took a look at a popular ruby/rails gem](https://github.com/kaminari/kaminari#specifying-the-inner-window-size-4-by-default). They call it the `window`:

```
<%= paginate @users, window: 2 %>
# This would output something like ... 5 6 7 8 9 ... when 7 is the current page.
```

**Comment by joshua-obritsch** [comment]
`window` is very clever. I like this naming best.

**Comment by CSchank** [comment]
Okay, I like window. Internally I use the idea of a radius which is half of the current `maxInNavigaton`. Maybe the user's interface should just be the radius, this actually reduces annoying checks for whether things are even or odd. And I like `window` too.

**Comment by CSchank** [comment]
So, with the new server-side components, where you actually show a sort of filter example, should I try re-building this with components?

**Comment by mpscholten** [comment]
I'd try to keep it as simple as possible. SSCs would be a bit overkill here IMO (they have quite some overhead, so it mostly makes sense when there's a specific need to follow a more interactive approach).

**Comment by mpscholten** [comment]
This has been merged now :) Good job everyone 👍
