### ISSUE TITLE
`updateRecord` should support explicit casting for postgres

### ISSUE THREAD

**Issue by rametta** [digitallyinduced/ihp#913]
I ran into an issue recently where I was trying to update a field on a record that had the type `[UUID]`, so it was an array of id's being stored in postgres. But when I used `updateRecord` it failed because it was implicitly type [Text].

My original code was:
```hs
item
    |> set #upvotes newUpvotes -- newUpvotes is type [UUID] and so is #upvotes field
    |> updateRecord
```
Which would throw the error: `sqlErrorMsg = "column \"upvotes\" is of type uuid[] but expression is of type text[]` even though my expression was indeed type `uuid[]`.

I had to write manual sql query to add an explicit cast `?::UUID[]` to my update statement.
```hs
result <- sqlQuery "UPDATE public.items SET upvotes = ?::UUID[] WHERE id = ? RETURNING *" (newUpvotesUUID, itemId)
```
[Full sourcecode link](https://github.com/rametta/retros/blob/main/Web/Controller/Items.hs#L36 )

^ So that works, but I would expect IHP to do that automatically with `updateRecord` since it should know the types before executing the query. Or if not automatically, a clean way to do it without writing a raw sql query.

I assume if this change would happen, it would happen here: https://github.com/digitallyinduced/ihp/blob/299e585e0063a5105694687367fc3797d8a9c397/IHP/SchemaCompiler.hs#L422

I can attempt to do this change in a PR, just want to see if I should or not

**Comment by zacwood9** [comment]
I also ran into this when inserting an enum array. Would be a great change 😄

**Comment by mpscholten** [comment]
Thanks for reporting :)

> I assume if this change would happen, it would happen here:

Yes. Do we also need to add it at the place where the `INSERT INTO` is generated?

--

It seems that the type cast is only needed for array values, so maybe we can only add the type cast there to not make our sql queries too verbose.

**Comment by rametta** [comment]
Yes, probably `INSERT` too.

> It seems that the type cast is only needed for array values, so maybe we can only add the type cast there to not make our sql queries too verbose.

I agree, sounds good
