### ISSUE TITLE
ApplyImageMagick doesn't work

### ISSUE THREAD

**Issue by mackdunkan** [digitallyinduced/ihp#943]
![image](https://user-images.githubusercontent.com/16391860/123654385-502aa780-d82e-11eb-9997-dc82d37a586c.png)
![image](https://user-images.githubusercontent.com/16391860/123654541-78b2a180-d82e-11eb-9cc6-e224642361bd.png)

**Comment by s0kil** [comment]
@mpscholten Do you understand what this means?

**Comment by mpscholten** [comment]
Yes 👍

**Comment by mpscholten** [comment]
@mackdunkan I pushed a fix for this to master :) You can follow the docu to update to latest master https://ihp.digitallyinduced.com/Guide/updating.html#updating-to-the-latest-git-commit
