### ISSUE TITLE
Improve adding multiple enum values

### ISSUE THREAD

**Issue by hendi** [digitallyinduced/ihp#956]
When adding many enum values via the schema designer it's tedious to repeatedly add a single one, click "add" button again.

Suggestion:
- when using enter to save an enum value automatically re-open the modal
- press ESC to close the modal
- have two buttons in the modal, "Save" and "Save & add another"

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/commit/016427378d860e5d9f6f2d12374d57b67c714e49 and  https://github.com/digitallyinduced/ihp/commit/bf3baf17155a2ccb239eab12b117e293eb3d738a
