### ISSUE TITLE
Valid postgres enums break generated Haskell code

### ISSUE THREAD

**Issue by hendi** [digitallyinduced/ihp#957]
Creating multiple enum with overlapping values is fine in SQL and accepted by IHP's schema builder

```sql
CREATE TYPE enum1 AS ENUM ('FOO', 'BAR');
CREATE TYPE enum2 AS ENUM ('FOO', 'BAZ');
```

but breaks the `build/Generated/Types.hs` with ```Multiple declarations of `Foo'```

**Comment by mpscholten** [comment]
Fixed via https://github.com/digitallyinduced/ihp/commit/52874d027c2502a3dfac856e449acb1d588260a8
