### ISSUE TITLE
SHA-256 hash mismatch error installing nix for IHP

### ISSUE THREAD

**Issue by dimavin1** [digitallyinduced/ihp#960]
I am trying to install IHP on Mac according to https://ihp.digitallyinduced.com/Guide/installation.html

Installation command for nix:
sh <(curl https://abathur-nix-install-tests.cachix.org/serve/yihf8zbs0jwph2rs9qfh80dnilijxdi2/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
fails with the error:
SHA-256 hash mismatch in 'https://abathur-nix-install-tests.cachix.org/serve/jqr52m6w8dwag5932hw67kq0rvbnji01/nix-2.4pre19700101_eab14a6-x86_64-darwin.tar.xz'; expected @binaryTarball_x86_64-darwin@, got eb40f032d84e2fadb1e875ad7a35a075f9c5b47a4737084a87f925292378b57a

**Comment by mpscholten** [comment]
Thanks for reporting. Looking into this 👍

**Comment by mpscholten** [comment]
Domen (founder of cachix) checked the hash and reported that the hash is okay. So it's likely a network error. Can you try to run the installer again?

**Comment by dimavin1** [comment]
I have tried the script again, the same error. It is consistently reproducible on my MacBook Air silicon. Please see the screenshot attached.
<img width="778" alt="Screen Shot 2021-07-06 at 8 31 20 AM" src="https://user-images.githubusercontent.com/22820477/124600448-b918ad80-de34-11eb-841a-a4b106a88cbe.png">

**Comment by mpscholten** [comment]
Can you try to install using the following command?

```
sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --daemon
```

[Nix added support for M1 just very recently.](https://twitter.com/domenkozar/status/1412368368963919873)

**Comment by dimavin1** [comment]
I have successfully installed nix with this command and one more following https://nixos.org/manual/nix/stable/#sect-macos-installation
After that I installed ihp using nix.

**Comment by mpscholten** [comment]
I've updated the docs to fix the bug for future users https://github.com/digitallyinduced/ihp/commit/f9069c567fecd225261a5ae47d2e4be16288e482 :)
