### ISSUE TITLE
Routes with a parameter of type [Text] are not interpreted correctly when there is one element in the list and the element is formatted as a UUID

### ISSUE THREAD

**Issue by jyoder** [digitallyinduced/ihp#971]
**Steps to Reproduce:**
1. Create a route which takes a `[Text]` parameter such as `NewBarfAction { something :: ![Text] }`
2. Visit this route in the browser with a single element in the list /NewBarfAction?something=4383aa8e-d200-45cb-9c8e-0090f14457ef

**Desired Behavior:**
In the corresponding controller action, `something` contains "4383aa8e-d200-45cb-9c8e-0090f14457ef".

**Observed Behavior:**
In the corresponding controller action, `something` is an empty list. You can see that the parameter is being passed to the controller by accessing it with `param "something"`, but it's not interpreted correctly by AutoRoute.

**Comment by jeyj0** [comment]
Could not reproduce with an action defined as:

```haskell
-- Web/Types.hs
data MyController = TestAction { texts :: ![Text] }

-- MyController:
    action TestAction { texts } = do
        putStrLn $ show texts
        render ShowTextsView { .. }

-- ShowTextsView:
data ShowTextsView = ShowTextsView { texts :: [Text] }

instance View ShowTextsView where
    html ShowTextsView { .. } = [hsx|
        <h1>Hello Texts</h1>
        <ul>
            {forEach texts renderText}
        </ul>
    |]
        where
            renderText t = [hsx|<li>{t}</li>|]
```

A simple request to `http://localhost:8000/Test?texts=test` results in `["test"]` on the command line and the a single list item in the html.

Can you verify, @jyoder ?

**Comment by jyoder** [comment]
Ah, there is a key piece of information missing which I just realized. Try making this request:
`http://localhost:8000/Test?texts=4383aa8e-d200-45cb-9c8e-0090f14457ef`

The string has to be formatted as a UUID to trigger the problematic behavior.

**Comment by jeyj0** [comment]
Successfully reproduced :+1:

**Comment by mpscholten** [comment]
Just fixed this.

We missed to check whether the field type of the action expects an UUID. Before the fix it was only checking whether the input can be parsed as an UUID. Once it could parse the input as an UUID, it tried to apply it to the action, which failed and was ignored. The type was already checked for all the other data types (it's actually required as the input `1337` could be either a string input for `"1337"` or the integer `1337`), it was only missed for the UUID case :)

**Comment by jyoder** [comment]
Sweet! Thank you!
