### ISSUE TITLE
Include functions in Application/Helper/View in Layout.hs (not only in views in the Views folder)

### ISSUE THREAD

**Issue by fritzfeger** [digitallyinduced/ihp#977]
The Guide > Architecture > [Where to place a function I want to use in all my views?](https://ihp.digitallyinduced.com/Guide/architecture.html#where-to-place-a-function-i-want-to-use-in-all-my-views) states that each function placed in `Application/Helper/View.hs` is "also already included in your view files". This is only true for views in the `View` folder but not for `Layout.hs` which is one folder level above. One might of course ´import Application.Helper.View´ manually in `Layout.hs` but life could be easier if IHP did this by default, especially so when there are multiple Apps and thus multiple `Layout.hs` files. Shouldn't for example a menu or footer valid for many or all apps be implemented that way?

**Comment by mpscholten** [comment]
> but life could be easier if IHP did this by default, especially so when there are multiple Apps and thus multiple Layout.hs files

Yes agree 👍  I checked some of our apps and actually we're also importing the view helpers inside the layout a lot. Pushed a change https://github.com/digitallyinduced/ihp/commit/57ddfe49b54b0af25a829e2341a05ea321a760c3

> Shouldn't for example a menu or footer valid for many or all apps be implemented that way?

Yes 👍
