### ISSUE TITLE
cannot delete columns: "Non-exhaustive patterns in Just refTable"

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#984]
When trying to delete columns with the SQL editor, I get the following error on the web:

![image](https://user-images.githubusercontent.com/12722104/126360761-977fc4c7-0715-4942-8e88-10ac74d50ebc.png)

And this shows up in the console: 

```
IHP/SchemaCompiler.hs:(496,17)-(500,50): Non-exhaustive patterns in Just refTable

No match in record selector indexName
```

I made a couple of additions to the SQL file to add a primary key with two fields, but other than that nothing and the "Update DB" option completes successfully.

**Comment by joshua-obritsch** [comment]
Based on line _504_ in _IHP//SchemaCompiler.hs_, it looks like only table creation is handled.

```haskell
|> \case StatementCreateTable CreateTable { columns } -> columns
```

**Comment by CSchank** [comment]
Based on the error message and line numbers given, I think the error might be here, since it pattern matches on `Just` directly? Somehow I've gotten into a state where it's `Nothing` and it shouldn't be? 

```
                (Just refTable) = let (Schema statements) = ?schema in
                        statements
                        |> find \case
                                StatementCreateTable CreateTable { name } -> name == refTableName
                                otherwise -> False
```

**Comment by CSchank** [comment]
Could this be related to [my question on Gitter about not having an `id` field](https://gitter.im/digitallyinduced/ihp?at=60f750fe7331d202b5bfc966)?

**Comment by CSchank** [comment]
Some more information I'll paste here to keep it all together. From @mpscholten on Gitter:

> looks like a bug related to the schema. Haven’t looked deep into this yet

I'll add that this indeed seems to be the case: I deleted the entire schema (after committing my change :) ) and tried making a new table with a column, and then it was delete-able. I will email Marc my full schema for testing. 

Another update: deleting things from certain tables works perfectly fine, but not others :)

**Comment by CSchank** [comment]
I have done even more digging and have found a much smaller example that still triggers the error. This schema will trigger it: 

```sql
CREATE TABLE users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY NOT NULL,
    email TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    locked_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    failed_login_attempts INT DEFAULT 0 NOT NULL,
    hello TEXT NOT NULL
);
CREATE INDEX users_email_index ON users (email);
```

But it only happens if the index is there. At first I thought it was because originally it was a UNIQUE INDEX with LOWER() for case-insensitive lookups, but any old index seems to cause the error, like above.

Trying to delete the example `hello` column results in:

![image](https://user-images.githubusercontent.com/12722104/126697027-a6d796fe-9870-4433-95f6-c7e2a04caa23.png)

on the web and:

`No match in record selector indexName` 

on the console.

No idea if this is the ONLY cause of the error, since other tables in my schema were having the same issue, but it is definitely one of them.

**Comment by mpscholten** [comment]
fyi: The `IHP/SchemaCompiler.hs:(496,17)-(500,50): Non-exhaustive patterns in Just refTable` error above is unrelated to the deleting a column issue 

Maybe you can give the fix a try at https://github.com/digitallyinduced/ihp/commit/318f9b8bc3ff737ca4dd268d85061ee09236131f :)
