### ISSUE TITLE
SQL editor causes Git to say all lines are deleted and re-created?

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#986]
Multiple times I've made some (relatively small) changes to the schema and Git detects it as if I've deleted all lines and re-written them. Has anyone run into this? I'm not sure why this is - could it be line endings?

**Comment by CSchank** [comment]
I think it is indeed line endings; GitHub Desktop reports no changes if you turn on the "ignore whitespace changes" option. 

I wonder if this might just be because I had `Schema.sql` open in VS Code as well, and made some changes there. Either way, we should still investigate to ensure it's not something IHP is doing wrong, or see if there are ways to make it interact better with VS Code if that's the problem.

**Comment by mpscholten** [comment]
The issue has happend to me as well. Not exactly sure what's causing this.

One theory: Multiple developers are working on the project and are using a different OS. Some operating systems encode line breaks differently. When the file is written to disk, the line break breaks will be changed to the one's of the OS of the current developer.

**Comment by s0kil** [comment]
One option is to create an `.gitattributes` file for IHP projects and add
```
# Normalize Line Endings For SQL Files
*.sql -crlf
```
to normalize line endings for SQL files.

**Comment by CSchank** [comment]
> The issue has happend to me as well. Not exactly sure what's causing this.
> 
> One theory: Multiple developers are working on the project and are using a different OS. Some operating systems encode line breaks differently. When the file is written to disk, the line break breaks will be changed to the one's of the OS of the current developer.

Yes; in my case, no one was committing in between those commits. So I wonder if it was VS Code set up weirdly even though I'm on macOS. What is the IHP SQL code generator supposed to spit out? Just "\n", or "\r\n" or either one depending on OS?

**Comment by CSchank** [comment]
> One option is to create an `.gitattributes` file for IHP projects and add
> 
> ```
> # Normalize Line Endings For SQL Files
> *.sql -crlf
> ```
> 
> to normalize line endings for SQL files.

This would work well on a per-project basis, but I'm not sure if IHP would want to adopt this by default, because people on Unix-based OSes wouldn't love this. And similarly it might cause problems for Windows people to go to LF only?

**Comment by mpscholten** [comment]
> What is the IHP SQL code generator supposed to spit out?

It uses `\n`. The file written using `Data.Text.IO.writeFile` which performs newline normalization: ["On both reading and writing, the platform's native newline conversion is performed."](https://hackage.haskell.org/package/text-1.2.4.1/docs/Data-Text-IO.html)

**Comment by mpscholten** [comment]
Looks like normalizing is our best option here. I followed what GHC is doing in their git repo. By default we'll have the linux line endings in the repo. It should be not a problem on windows 👍
