### ISSUE TITLE
minor cosmetic problem with index rendering on dev server

### ISSUE THREAD

**Issue by CSchank** [digitallyinduced/ihp#994]
This is very minor, but I figured I'd report it anyway since it's one of those "polish" things. It seems when there aren't columns in all rows the horizontal separators of the table aren't rendered properly:

![image](https://user-images.githubusercontent.com/12722104/126721821-ffcf4aba-68e7-4fde-a3c3-b2c184d46283.png)

**Comment by mpscholten** [comment]
Thanks 👍  Just fixed this :)
